// Code generated by Cyberia stat-contract. DO NOT EDIT.
package game

const StatCount = 6
const StatModifierMin = -100
const StatModifierMax = 100

func (r ProgressionRules) validScalarBounds() bool {
	return r.MaxLevel >= 1 && r.MaxLevel <= 65535 && r.XpPerLevel >= 1 && r.XpPerLevel <= 1000000 && r.KillXp >= 0 && r.KillXp <= 1000000 && r.QuestXp >= 0 && r.QuestXp <= 1000000 && r.ObjectiveXp >= 0 && r.ObjectiveXp <= 1000000 && r.MinAwardIntervalMs >= 1 && r.MinAwardIntervalMs <= 60000 && r.RepeatWindowMs >= 1000 && r.RepeatWindowMs <= 3600000 && r.MaxRepeatAwards >= 1 && r.MaxRepeatAwards <= 100 && r.MaxAwardsPerWindow >= 1 && r.MaxAwardsPerWindow <= 1000 && r.DefaultBotLevel >= 1 && r.DefaultBotLevel <= 65535
}

var statNames = [StatCount]string{"effect", "resistance", "agility", "range", "intelligence", "utility"}
var statEffectiveFloors = [StatCount]float64{1, 0, -90, 0, 0, 0}

// statScales is what one point of each stat is worth in the simulation.
var statScales = ComputedStats{Effect: 1, Resistance: 1, Agility: 0.01, Range: 50, Intelligence: 0.05, Utility: 0.01}

const statRegenPerResistance = 0.1

type Stats struct {
	Effect       int `json:"effect"`
	Resistance   int `json:"resistance"`
	Agility      int `json:"agility"`
	Range        int `json:"range"`
	Intelligence int `json:"intelligence"`
	Utility      int `json:"utility"`
}
type ComputedStats struct {
	Effect       float64 `json:"effect"`
	Resistance   float64 `json:"resistance"`
	Agility      float64 `json:"agility"`
	Range        float64 `json:"range"`
	Intelligence float64 `json:"intelligence"`
	Utility      float64 `json:"utility"`
}

func (s Stats) computed() ComputedStats {
	return ComputedStats{Effect: float64(s.Effect), Resistance: float64(s.Resistance), Agility: float64(s.Agility), Range: float64(s.Range), Intelligence: float64(s.Intelligence), Utility: float64(s.Utility)}
}
func (s ComputedStats) Values() [StatCount]float64 {
	return [StatCount]float64{s.Effect, s.Resistance, s.Agility, s.Range, s.Intelligence, s.Utility}
}
func statsFromValues(v [StatCount]float64) ComputedStats {
	return ComputedStats{Effect: v[0], Resistance: v[1], Agility: v[2], Range: v[3], Intelligence: v[4], Utility: v[5]}
}
func defaultProgressionRules() ProgressionRules {
	return ProgressionRules{
		MaxLevel:           100,
		XpPerLevel:         100,
		BaseStats:          ComputedStats{5, 10, 0, 0, 0, 0},
		PerLevelStats:      ComputedStats{2, 5, 1, 10, 1, 1},
		KillXp:             25,
		QuestXp:            100,
		ObjectiveXp:        10,
		MinAwardIntervalMs: 500,
		RepeatWindowMs:     60000,
		MaxRepeatAwards:    4,
		MaxAwardsPerWindow: 30,
		DefaultBotLevel:    1,
	}
}
