---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-cyberia-mmo-server-production-blue
  namespace: default
  labels:
    app: dd-cyberia-mmo-server-production-blue
    deploy-id: dd-cyberia-mmo-server-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-cyberia-mmo-server-production-blue
  template:
    metadata:
      labels:
        app: dd-cyberia-mmo-server-production-blue
        deploy-id: dd-cyberia-mmo-server-production
    spec:
      containers:
        - name: dd-cyberia-mmo-server-production-blue
          image: underpost/cyberia-server:v3.2.9
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: underpost-config

          command:
            - /bin/sh
            - -c
            - >
              npm install -g underpost &&
              underpost config set container-status dd-cyberia-mmo-server-production-initializing-deployment &&
              set -a && . /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-server/env/production.env && set +a && export ENGINE_GRPC_ADDRESS=dd-cyberia-grpc-service-production-blue.default.svc.cluster.local:50051 && export READY_CMD='underpost config set container-status dd-cyberia-mmo-server-production-running-deployment' && /home/dd/engine/cyberia-server/server

    
          volumeMounts:
            - name: instance-cyberia-server-dd-cyberia-mmo-server-production-blue
              mountPath: /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-server/env
    
      volumes:
        - name: instance-cyberia-server-dd-cyberia-mmo-server-production-blue
          persistentVolumeClaim:
            claimName: instance-cyberia-server-dd-cyberia-mmo-server-production-blue
    
      
---
apiVersion: v1
kind: Service
metadata:
  name: dd-cyberia-mmo-server-production-blue-service
  namespace: default
spec:
  selector:
    app: dd-cyberia-mmo-server-production-blue
  ports:
    - name: 'tcp-8081'
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: 'udp-8081'
      protocol: UDP
      port: 8081
      targetPort: 8081
  type: LoadBalancer