---
apiVersion: v1
kind: Service
metadata:
  name: dd-cyberia-grpc-service-production-blue
  namespace: default
  labels:
    app: dd-cyberia-grpc-service-production-blue
spec:
  type: ClusterIP
  selector:
    app: dd-cyberia-production-blue
  ports:
    - name: grpc-50051
      protocol: TCP
      port: 50051
      targetPort: 50051
