---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: instance-cyberia-server-dd-cyberia-mmo-server-forest-development-blue
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-worker
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: instance-cyberia-server-dd-cyberia-mmo-server-forest-development-blue
    namespace: default
  hostPath:
    path: /home/dd/engine/volume/instance-cyberia-server-dd-cyberia-mmo-server-forest-development-blue
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instance-cyberia-server-dd-cyberia-mmo-server-forest-development-blue
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: instance-cyberia-server-dd-cyberia-mmo-server-forest-development-blue
  resources:
    requests:
      storage: 5Gi
