---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-cyberia-mmo-server-test-development-blue
  namespace: default
  labels:
    app: dd-cyberia-mmo-server-test-development-blue
    deploy-id: dd-cyberia-mmo-server-test-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-cyberia-mmo-server-test-development-blue
  template:
    metadata:
      labels:
        app: dd-cyberia-mmo-server-test-development-blue
        deploy-id: dd-cyberia-mmo-server-test-development
    spec:
      containers:
        - name: dd-cyberia-mmo-server-test-development-blue
          image: underpost/cyberia-server:v3.2.70
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: underpost-config
          ports:
            - containerPort: 8083

          command:
            - /bin/sh
            - -c
            - >
              set -a && . /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-server-test/env/development.env && set +a && export ENGINE_GRPC_ADDRESS=dd-cyberia-grpc-service-development-blue.default.svc.cluster.local:50051 && export SERVER_PORT=8083 && exec /home/dd/engine/cyberia-server/server
          readinessProbe:
            {
              "tcpSocket": {
                "port": 8083
              },
              "initialDelaySeconds": 3,
              "periodSeconds": 5,
              "timeoutSeconds": 3,
              "failureThreshold": 6
            }
          livenessProbe:
            {
              "tcpSocket": {
                "port": 8083
              },
              "initialDelaySeconds": 30,
              "periodSeconds": 20,
              "timeoutSeconds": 5,
              "failureThreshold": 3
            }
          lifecycle:
            {
              "postStart": {
                "exec": {
                  "command": [
                    "sh",
                    "-c",
                    "underpost config set container-status dd-cyberia-mmo-server-test-development-initializing-deployment || true"
                  ]
                }
              },
              "preStop": {
                "exec": {
                  "command": [
                    "sh",
                    "-c",
                    "underpost config set container-status dd-cyberia-mmo-server-test-development-stopping-deployment || true"
                  ]
                }
              }
            }


    
          volumeMounts:
            - name: instance-cyberia-server-dd-cyberia-mmo-server-test-development-blue
              mountPath: /home/dd/engine/engine-private/conf/dd-cyberia/instances/mmo-server-test/env
    
      volumes:
        - name: instance-cyberia-server-dd-cyberia-mmo-server-test-development-blue
          persistentVolumeClaim:
            claimName: instance-cyberia-server-dd-cyberia-mmo-server-test-development-blue
    
      
---
apiVersion: v1
kind: Service
metadata:
  name: dd-cyberia-mmo-server-test-development-blue-service
  namespace: default
spec:
  selector:
    app: dd-cyberia-mmo-server-test-development-blue
  ports:
    - name: 'tcp-8083'
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: 'udp-8083'
      protocol: UDP
      port: 8083
      targetPort: 8083
  type: LoadBalancer