---
apiVersion: v1
kind: Service
metadata:
  name: dd-cyberia-mmo-server-test-development-traffic-service
  namespace: default
  labels:
    underpost.net/traffic-service: "true"
    underpost.net/deploy-id: dd-cyberia-mmo-server-test-development
spec:
  type: ClusterIP
  selector:
    app: dd-cyberia-mmo-server-test-development-blue
  ports:
    - name: 'tcp-8083'
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: 'udp-8083'
      protocol: UDP
      port: 8083
      targetPort: 8083
