package engine_client

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

// Fixtures in testdata/ are generated by the engine's shared boot assembly
// (src/projects/cyberia/instance-data.js), so these tests pin the REST↔gRPC
// payload contract across both codebases.
func fixtureHandler(t *testing.T, routes map[string]string) http.Handler {
	t.Helper()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		file, ok := routes[r.URL.Path]
		if !ok {
			w.WriteHeader(http.StatusNotFound)
			w.Write([]byte(`{"status":"error","message":"not found"}`))
			return
		}
		body, err := os.ReadFile(file)
		if err != nil {
			t.Fatalf("read fixture %s: %v", file, err)
		}
		w.Write(body)
	})
}

func TestRestClientFetchFullInstanceContract(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/full-instance/contract-test": "testdata/boot_full_instance_fallback.json",
	}))
	defer srv.Close()

	resp, err := NewRestClient(srv.URL).FetchFullInstance(context.Background(), "contract-test")
	if err != nil {
		t.Fatalf("FetchFullInstance: %v", err)
	}
	if resp.GetVersion() != "fallback" {
		t.Errorf("version = %q, want %q", resp.GetVersion(), "fallback")
	}
	if len(resp.GetMaps()) == 0 {
		t.Error("maps empty")
	}
	if len(resp.GetInstance().GetMapCodes()) != len(resp.GetMaps()) {
		t.Errorf("mapCodes (%d) != maps (%d)", len(resp.GetInstance().GetMapCodes()), len(resp.GetMaps()))
	}
	cfg := resp.GetConfig()
	if cfg == nil || cfg.GetTickRate() <= 0 {
		t.Fatalf("config missing or tickRate unset: %+v", cfg)
	}
	if len(cfg.GetEntityDefaults()) == 0 {
		t.Error("entityDefaults empty")
	}
	if len(resp.GetActions()) == 0 || len(resp.GetQuests()) == 0 {
		t.Error("actions/quests empty")
	}
}

func TestRestClientManifestAndPingContract(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/object-layer-manifest": "testdata/boot_manifest.json",
		restBootPath + "/ping":                  "testdata/boot_ping.json",
	}))
	defer srv.Close()
	c := NewRestClient(srv.URL)

	entries, err := c.FetchObjectLayerManifest(context.Background())
	if err != nil {
		t.Fatalf("FetchObjectLayerManifest: %v", err)
	}
	if len(entries) != 1 || entries[0].ItemID != "sword" || entries[0].Sha256 != "abc" {
		t.Errorf("entries = %+v", entries)
	}

	ts, err := c.Ping(context.Background())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}
	if ts <= 0 {
		t.Errorf("serverTimeMs = %d", ts)
	}
}

func TestRestClientErrorEnvelope(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, nil))
	defer srv.Close()

	if _, err := NewRestClient(srv.URL).FetchObjectLayer(context.Background(), "ghost"); err == nil {
		t.Fatal("expected error for 404 envelope")
	}
}
