package engine_client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"reflect"
	"testing"

	"cyberia-server/game"
)

// The identity the engine computes for the contract definition: a change to its canonical
// bytes fails here.
const (
	contractCid         = "bafkreihbdxmw6pzohkabf3pxtvqytnmkfi6h6f3ovmihp7vb6g7im3fule"
	contractRenderCid   = "bafkreidksiktki2pjijlf63djoorcifkov56idvalevbj4clakjz7mvl3q"
	contractMetadataCid = "bafkreigcohqyadv5kpqjoph2m4s53wfmu5pvuaufgwilobl7n4hxgha6hm"
)

// Fixtures in testdata/ are generated by the engine's shared boot assembly
// (src/projects/cyberia/instance-data.js), so these tests pin the REST↔gRPC
// payload contract across both codebases.
func fixtureHandler(t *testing.T, routes map[string]string) http.Handler {
	t.Helper()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		file, ok := routes[r.URL.Path]
		if !ok {
			w.WriteHeader(http.StatusNotFound)
			w.Write([]byte(`{"status":"error","message":"not found"}`))
			return
		}
		body, err := os.ReadFile(file)
		if err != nil {
			t.Fatalf("read fixture %s: %v", file, err)
		}
		w.Write(body)
	})
}

func TestRestClientFetchFullInstanceContract(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/full-instance/contract-test": "testdata/boot_full_instance.json",
	}))
	defer srv.Close()

	resp, err := NewRestClient(srv.URL).FetchFullInstance(context.Background(), "contract-test")
	if err != nil {
		t.Fatalf("FetchFullInstance: %v", err)
	}
	if resp.GetVersion() != "contract-fixture" {
		t.Errorf("version = %q, want %q", resp.GetVersion(), "contract-fixture")
	}
	if len(resp.GetMaps()) == 0 {
		t.Error("maps empty")
	}
	if len(resp.GetInstance().GetMapCodes()) != len(resp.GetMaps()) {
		t.Errorf("mapCodes (%d) != maps (%d)", len(resp.GetInstance().GetMapCodes()), len(resp.GetMaps()))
	}
	cfg := resp.GetConfig()
	if cfg == nil || cfg.GetTickRate() <= 0 {
		t.Fatalf("config missing or tickRate unset: %+v", cfg)
	}
	if cfg.GetProgressionRules().GetMaxLevel() != 100 || resp.GetMaps()[0].GetEntities()[0].GetLevel() != 7 {
		t.Fatal("progression config or entity level missing")
	}
	if stats := resp.GetObjectLayers()[0].GetStats(); stats.GetEffect() != -100 || stats.GetResistance() != 100 {
		t.Fatal("signed stat boundary changed")
	}
	if len(cfg.GetEntityDefaults()) == 0 {
		t.Error("entityDefaults empty")
	}
	if len(resp.GetActions()) == 0 || len(resp.GetQuests()) == 0 {
		t.Error("actions/quests empty")
	}
}

func TestRestClientManifestAndPingContract(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/object-layer-manifest": "testdata/boot_manifest.json",
		restBootPath + "/ping":                  "testdata/boot_ping.json",
	}))
	defer srv.Close()
	c := NewRestClient(srv.URL)

	entries, err := c.FetchObjectLayerManifest(context.Background())
	if err != nil {
		t.Fatalf("FetchObjectLayerManifest: %v", err)
	}
	if len(entries) != 1 || entries[0].ItemID != "sword" || entries[0].Cid != contractCid {
		t.Errorf("entries = %+v", entries)
	}

	ts, err := c.Ping(context.Background())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}
	if ts <= 0 {
		t.Errorf("serverTimeMs = %d", ts)
	}
}

func TestRestClientErrorEnvelope(t *testing.T) {
	srv := httptest.NewServer(fixtureHandler(t, nil))
	defer srv.Close()

	if _, err := NewRestClient(srv.URL).FetchObjectLayer(context.Background(), "ghost"); err == nil {
		t.Fatal("expected error for 404 envelope")
	}
}

func TestRestClientSignedObjectLayer(t *testing.T) {
	server := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/object-layer/sword": "testdata/boot_object_layer.json",
	}))
	defer server.Close()
	layer, err := NewRestClient(server.URL).FetchObjectLayer(context.Background(), "sword")
	if err != nil {
		t.Fatal(err)
	}
	if layer.Data.Stats.Effect != -100 || layer.Data.Stats.Resistance != 100 {
		t.Fatal("signed stat boundaries changed")
	}
}

// The definition the engine serves and the metadata the client parses name one identity: the
// WebSocket fixture the client is tested against is `game.OLMeta` of the REST fixture.
func TestObjectLayerIdentityReachesTheClient(t *testing.T) {
	server := httptest.NewServer(fixtureHandler(t, map[string]string{
		restBootPath + "/object-layer/sword": "testdata/boot_object_layer.json",
	}))
	defer server.Close()
	layer, err := NewRestClient(server.URL).FetchObjectLayer(context.Background(), "sword")
	if err != nil {
		t.Fatal(err)
	}
	if layer.Cid != contractCid {
		t.Fatalf("identity = %q", layer.Cid)
	}
	if render := layer.Data.Render; render == nil || render.Cid != contractRenderCid || render.MetadataCid != contractMetadataCid {
		t.Fatalf("render contract = %+v", render)
	}
	if layer.Data.Ledger != nil {
		t.Fatalf("unregistered definition carries a ledger: %+v", layer.Data.Ledger)
	}

	sent, err := json.Marshal(map[string]*game.OLMeta{
		layer.Data.Item.ID: {Cid: layer.Cid, Data: layer.Data},
	})
	if err != nil {
		t.Fatal(err)
	}
	expected, err := os.ReadFile("../../cyberia-client/tests/testdata/ws_object_layer_metadata.json")
	if err != nil {
		t.Skipf("cyberia-client checkout not beside this repository: %v", err)
	}
	var sentJSON, expectedJSON any
	if err := json.Unmarshal(sent, &sentJSON); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(expected, &expectedJSON); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(sentJSON, expectedJSON) {
		t.Fatalf("client metadata contract drifted:\n%s\nexpected\n%s", sent, expected)
	}
}
