// Protocol Buffers schema for Cyberia Online gRPC data pipeline.
//
// This service runs on the Engine-Cyberia (Node.js) side.
// The Cyberia-Server (Go) acts as the gRPC **client**, calling
// these RPCs to fetch game data for world reconstruction.
//
// Design rules:
//   1. Read-only — no create / update / delete.
//   2. Batch-friendly — large collections streamed or paginated.
//   3. Live-reload aware — version fields let the Go server detect
//      stale data and perform surgical in-memory replacement.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: proto/cyberia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_cyberia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Vec2I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2I) Reset() {
	*x = Vec2I{}
	mi := &file_proto_cyberia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2I) ProtoMessage() {}

func (x *Vec2I) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2I.ProtoReflect.Descriptor instead.
func (*Vec2I) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{1}
}

func (x *Vec2I) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2I) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        int32                  `protobuf:"varint,1,opt,name=effect,proto3" json:"effect,omitempty"`
	Resistance    int32                  `protobuf:"varint,2,opt,name=resistance,proto3" json:"resistance,omitempty"`
	Agility       int32                  `protobuf:"varint,3,opt,name=agility,proto3" json:"agility,omitempty"`
	Range         int32                  `protobuf:"varint,4,opt,name=range,proto3" json:"range,omitempty"`
	Intelligence  int32                  `protobuf:"varint,5,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Utility       int32                  `protobuf:"varint,6,opt,name=utility,proto3" json:"utility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_cyberia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *Stats) GetResistance() int32 {
	if x != nil {
		return x.Resistance
	}
	return 0
}

func (x *Stats) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Stats) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *Stats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Stats) GetUtility() int32 {
	if x != nil {
		return x.Utility
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Activable     bool                   `protobuf:"varint,4,opt,name=activable,proto3" json:"activable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_proto_cyberia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{3}
}

func (x *ItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ItemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemInfo) GetActivable() bool {
	if x != nil {
		return x.Activable
	}
	return false
}

type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // ERC1155 | OFF_CHAIN
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_proto_cyberia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{4}
}

func (x *Ledger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ledger) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ledger) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type Render struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`                                    // IPFS CID atlas PNG
	MetadataCid   string                 `protobuf:"bytes,2,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"` // IPFS CID atlas metadata JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Render) Reset() {
	*x = Render{}
	mi := &file_proto_cyberia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Render) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Render) ProtoMessage() {}

func (x *Render) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Render.ProtoReflect.Descriptor instead.
func (*Render) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{5}
}

func (x *Render) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Render) GetMetadataCid() string {
	if x != nil {
		return x.MetadataCid
	}
	return ""
}

type ObjectLayerMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MongoId string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"` // MongoDB _id
	Stats   *Stats                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Item    *ItemInfo              `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Ledger  *Ledger                `protobuf:"bytes,4,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Render  *Render                `protobuf:"bytes,5,opt,name=render,proto3" json:"render,omitempty"`
	Sha256  string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Cid     string                 `protobuf:"bytes,7,opt,name=cid,proto3" json:"cid,omitempty"` // IPFS CID of the OL data JSON
	// Animation metadata (populated from ObjectLayerRenderFrames ref)
	FrameDuration int32 `protobuf:"varint,8,opt,name=frame_duration,json=frameDuration,proto3" json:"frame_duration,omitempty"` // ms per frame
	IsStateless   bool  `protobuf:"varint,9,opt,name=is_stateless,json=isStateless,proto3" json:"is_stateless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerMessage) Reset() {
	*x = ObjectLayerMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerMessage) ProtoMessage() {}

func (x *ObjectLayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerMessage.ProtoReflect.Descriptor instead.
func (*ObjectLayerMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectLayerMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *ObjectLayerMessage) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ObjectLayerMessage) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ObjectLayerMessage) GetLedger() *Ledger {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *ObjectLayerMessage) GetRender() *Render {
	if x != nil {
		return x.Render
	}
	return nil
}

func (x *ObjectLayerMessage) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ObjectLayerMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ObjectLayerMessage) GetFrameDuration() int32 {
	if x != nil {
		return x.FrameDuration
	}
	return 0
}

func (x *ObjectLayerMessage) GetIsStateless() bool {
	if x != nil {
		return x.IsStateless
	}
	return false
}

type GetObjectLayerBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by item type (e.g. "skin", "weapon").
	// Empty = return all.
	ItemTypeFilter string `protobuf:"bytes,1,opt,name=item_type_filter,json=itemTypeFilter,proto3" json:"item_type_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectLayerBatchRequest) Reset() {
	*x = GetObjectLayerBatchRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerBatchRequest) ProtoMessage() {}

func (x *GetObjectLayerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerBatchRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectLayerBatchRequest) GetItemTypeFilter() string {
	if x != nil {
		return x.ItemTypeFilter
	}
	return ""
}

type GetObjectLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerRequest) Reset() {
	*x = GetObjectLayerRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerRequest) ProtoMessage() {}

func (x *GetObjectLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectLayerRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type FrameMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FrameIndex    int32                  `protobuf:"varint,5,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameMetadata) Reset() {
	*x = FrameMetadata{}
	mi := &file_proto_cyberia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMetadata) ProtoMessage() {}

func (x *FrameMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMetadata.ProtoReflect.Descriptor instead.
func (*FrameMetadata) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{9}
}

func (x *FrameMetadata) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FrameMetadata) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FrameMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameMetadata) GetFrameIndex() int32 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

type DirectionFrames struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpIdle           []*FrameMetadata       `protobuf:"bytes,1,rep,name=up_idle,json=upIdle,proto3" json:"up_idle,omitempty"`
	DownIdle         []*FrameMetadata       `protobuf:"bytes,2,rep,name=down_idle,json=downIdle,proto3" json:"down_idle,omitempty"`
	RightIdle        []*FrameMetadata       `protobuf:"bytes,3,rep,name=right_idle,json=rightIdle,proto3" json:"right_idle,omitempty"`
	LeftIdle         []*FrameMetadata       `protobuf:"bytes,4,rep,name=left_idle,json=leftIdle,proto3" json:"left_idle,omitempty"`
	UpRightIdle      []*FrameMetadata       `protobuf:"bytes,5,rep,name=up_right_idle,json=upRightIdle,proto3" json:"up_right_idle,omitempty"`
	DownRightIdle    []*FrameMetadata       `protobuf:"bytes,6,rep,name=down_right_idle,json=downRightIdle,proto3" json:"down_right_idle,omitempty"`
	UpLeftIdle       []*FrameMetadata       `protobuf:"bytes,7,rep,name=up_left_idle,json=upLeftIdle,proto3" json:"up_left_idle,omitempty"`
	DownLeftIdle     []*FrameMetadata       `protobuf:"bytes,8,rep,name=down_left_idle,json=downLeftIdle,proto3" json:"down_left_idle,omitempty"`
	DefaultIdle      []*FrameMetadata       `protobuf:"bytes,9,rep,name=default_idle,json=defaultIdle,proto3" json:"default_idle,omitempty"`
	UpWalking        []*FrameMetadata       `protobuf:"bytes,10,rep,name=up_walking,json=upWalking,proto3" json:"up_walking,omitempty"`
	DownWalking      []*FrameMetadata       `protobuf:"bytes,11,rep,name=down_walking,json=downWalking,proto3" json:"down_walking,omitempty"`
	RightWalking     []*FrameMetadata       `protobuf:"bytes,12,rep,name=right_walking,json=rightWalking,proto3" json:"right_walking,omitempty"`
	LeftWalking      []*FrameMetadata       `protobuf:"bytes,13,rep,name=left_walking,json=leftWalking,proto3" json:"left_walking,omitempty"`
	UpRightWalking   []*FrameMetadata       `protobuf:"bytes,14,rep,name=up_right_walking,json=upRightWalking,proto3" json:"up_right_walking,omitempty"`
	DownRightWalking []*FrameMetadata       `protobuf:"bytes,15,rep,name=down_right_walking,json=downRightWalking,proto3" json:"down_right_walking,omitempty"`
	UpLeftWalking    []*FrameMetadata       `protobuf:"bytes,16,rep,name=up_left_walking,json=upLeftWalking,proto3" json:"up_left_walking,omitempty"`
	DownLeftWalking  []*FrameMetadata       `protobuf:"bytes,17,rep,name=down_left_walking,json=downLeftWalking,proto3" json:"down_left_walking,omitempty"`
	NoneIdle         []*FrameMetadata       `protobuf:"bytes,18,rep,name=none_idle,json=noneIdle,proto3" json:"none_idle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectionFrames) Reset() {
	*x = DirectionFrames{}
	mi := &file_proto_cyberia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionFrames) ProtoMessage() {}

func (x *DirectionFrames) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionFrames.ProtoReflect.Descriptor instead.
func (*DirectionFrames) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{10}
}

func (x *DirectionFrames) GetUpIdle() []*FrameMetadata {
	if x != nil {
		return x.UpIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownIdle() []*FrameMetadata {
	if x != nil {
		return x.DownIdle
	}
	return nil
}

func (x *DirectionFrames) GetRightIdle() []*FrameMetadata {
	if x != nil {
		return x.RightIdle
	}
	return nil
}

func (x *DirectionFrames) GetLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.LeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpRightIdle() []*FrameMetadata {
	if x != nil {
		return x.UpRightIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownRightIdle() []*FrameMetadata {
	if x != nil {
		return x.DownRightIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.UpLeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.DownLeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetDefaultIdle() []*FrameMetadata {
	if x != nil {
		return x.DefaultIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpWalking() []*FrameMetadata {
	if x != nil {
		return x.UpWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownWalking() []*FrameMetadata {
	if x != nil {
		return x.DownWalking
	}
	return nil
}

func (x *DirectionFrames) GetRightWalking() []*FrameMetadata {
	if x != nil {
		return x.RightWalking
	}
	return nil
}

func (x *DirectionFrames) GetLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.LeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetUpRightWalking() []*FrameMetadata {
	if x != nil {
		return x.UpRightWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownRightWalking() []*FrameMetadata {
	if x != nil {
		return x.DownRightWalking
	}
	return nil
}

func (x *DirectionFrames) GetUpLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.UpLeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.DownLeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetNoneIdle() []*FrameMetadata {
	if x != nil {
		return x.NoneIdle
	}
	return nil
}

type AtlasSpriteSheetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // File doc _id for REST blob fetch
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`                     // IPFS CID of atlas PNG
	ItemKey       string                 `protobuf:"bytes,4,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"`
	AtlasWidth    int32                  `protobuf:"varint,5,opt,name=atlas_width,json=atlasWidth,proto3" json:"atlas_width,omitempty"`
	AtlasHeight   int32                  `protobuf:"varint,6,opt,name=atlas_height,json=atlasHeight,proto3" json:"atlas_height,omitempty"`
	CellPixelDim  int32                  `protobuf:"varint,7,opt,name=cell_pixel_dim,json=cellPixelDim,proto3" json:"cell_pixel_dim,omitempty"`
	Frames        *DirectionFrames       `protobuf:"bytes,8,opt,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtlasSpriteSheetMessage) Reset() {
	*x = AtlasSpriteSheetMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlasSpriteSheetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasSpriteSheetMessage) ProtoMessage() {}

func (x *AtlasSpriteSheetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasSpriteSheetMessage.ProtoReflect.Descriptor instead.
func (*AtlasSpriteSheetMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{11}
}

func (x *AtlasSpriteSheetMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetAtlasWidth() int32 {
	if x != nil {
		return x.AtlasWidth
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetAtlasHeight() int32 {
	if x != nil {
		return x.AtlasHeight
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetCellPixelDim() int32 {
	if x != nil {
		return x.CellPixelDim
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetFrames() *DirectionFrames {
	if x != nil {
		return x.Frames
	}
	return nil
}

type GetAtlasSpriteSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemKey       string                 `protobuf:"bytes,1,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtlasSpriteSheetRequest) Reset() {
	*x = GetAtlasSpriteSheetRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtlasSpriteSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtlasSpriteSheetRequest) ProtoMessage() {}

func (x *GetAtlasSpriteSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtlasSpriteSheetRequest.ProtoReflect.Descriptor instead.
func (*GetAtlasSpriteSheetRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{12}
}

func (x *GetAtlasSpriteSheetRequest) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

type GetAtlasSpriteSheetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtlasSpriteSheetBatchRequest) Reset() {
	*x = GetAtlasSpriteSheetBatchRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtlasSpriteSheetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtlasSpriteSheetBatchRequest) ProtoMessage() {}

func (x *GetAtlasSpriteSheetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtlasSpriteSheetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetAtlasSpriteSheetBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{13}
}

type PortalEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceMapCode string                 `protobuf:"bytes,1,opt,name=source_map_code,json=sourceMapCode,proto3" json:"source_map_code,omitempty"`
	SourceCellX   int32                  `protobuf:"varint,2,opt,name=source_cell_x,json=sourceCellX,proto3" json:"source_cell_x,omitempty"`
	SourceCellY   int32                  `protobuf:"varint,3,opt,name=source_cell_y,json=sourceCellY,proto3" json:"source_cell_y,omitempty"`
	TargetMapCode string                 `protobuf:"bytes,4,opt,name=target_map_code,json=targetMapCode,proto3" json:"target_map_code,omitempty"`
	TargetCellX   int32                  `protobuf:"varint,5,opt,name=target_cell_x,json=targetCellX,proto3" json:"target_cell_x,omitempty"`
	TargetCellY   int32                  `protobuf:"varint,6,opt,name=target_cell_y,json=targetCellY,proto3" json:"target_cell_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalEdge) Reset() {
	*x = PortalEdge{}
	mi := &file_proto_cyberia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalEdge) ProtoMessage() {}

func (x *PortalEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalEdge.ProtoReflect.Descriptor instead.
func (*PortalEdge) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{14}
}

func (x *PortalEdge) GetSourceMapCode() string {
	if x != nil {
		return x.SourceMapCode
	}
	return ""
}

func (x *PortalEdge) GetSourceCellX() int32 {
	if x != nil {
		return x.SourceCellX
	}
	return 0
}

func (x *PortalEdge) GetSourceCellY() int32 {
	if x != nil {
		return x.SourceCellY
	}
	return 0
}

func (x *PortalEdge) GetTargetMapCode() string {
	if x != nil {
		return x.TargetMapCode
	}
	return ""
}

func (x *PortalEdge) GetTargetCellX() int32 {
	if x != nil {
		return x.TargetCellX
	}
	return 0
}

func (x *PortalEdge) GetTargetCellY() int32 {
	if x != nil {
		return x.TargetCellY
	}
	return 0
}

type InstanceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	MapCodes      []string               `protobuf:"bytes,6,rep,name=map_codes,json=mapCodes,proto3" json:"map_codes,omitempty"` // vertex set
	Portals       []*PortalEdge          `protobuf:"bytes,7,rep,name=portals,proto3" json:"portals,omitempty"`                   // edge set
	TopologyMode  string                 `protobuf:"bytes,8,opt,name=topology_mode,json=topologyMode,proto3" json:"topology_mode,omitempty"`
	Seed          string                 `protobuf:"bytes,9,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceMessage) Reset() {
	*x = InstanceMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMessage) ProtoMessage() {}

func (x *InstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMessage.ProtoReflect.Descriptor instead.
func (*InstanceMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{15}
}

func (x *InstanceMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *InstanceMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstanceMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InstanceMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InstanceMessage) GetMapCodes() []string {
	if x != nil {
		return x.MapCodes
	}
	return nil
}

func (x *InstanceMessage) GetPortals() []*PortalEdge {
	if x != nil {
		return x.Portals
	}
	return nil
}

func (x *InstanceMessage) GetTopologyMode() string {
	if x != nil {
		return x.TopologyMode
	}
	return ""
}

func (x *InstanceMessage) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type GetFullInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceCode  string                 `protobuf:"bytes,1,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceRequest) Reset() {
	*x = GetFullInstanceRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceRequest) ProtoMessage() {}

func (x *GetFullInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetFullInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{16}
}

func (x *GetFullInstanceRequest) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

type GetFullInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *InstanceMessage       `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Maps          []*MapDataMessage      `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`                                     // pre-populated for convenience
	ObjectLayers  []*ObjectLayerMessage  `protobuf:"bytes,3,rep,name=object_layers,json=objectLayers,proto3" json:"object_layers,omitempty"` // all OLs referenced by entities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceResponse) Reset() {
	*x = GetFullInstanceResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceResponse) ProtoMessage() {}

func (x *GetFullInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetFullInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{17}
}

func (x *GetFullInstanceResponse) GetInstance() *InstanceMessage {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetFullInstanceResponse) GetMaps() []*MapDataMessage {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *GetFullInstanceResponse) GetObjectLayers() []*ObjectLayerMessage {
	if x != nil {
		return x.ObjectLayers
	}
	return nil
}

type EntityMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityType         string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	InitCellX          int32                  `protobuf:"varint,2,opt,name=init_cell_x,json=initCellX,proto3" json:"init_cell_x,omitempty"`
	InitCellY          int32                  `protobuf:"varint,3,opt,name=init_cell_y,json=initCellY,proto3" json:"init_cell_y,omitempty"`
	DimX               int32                  `protobuf:"varint,4,opt,name=dim_x,json=dimX,proto3" json:"dim_x,omitempty"`
	DimY               int32                  `protobuf:"varint,5,opt,name=dim_y,json=dimY,proto3" json:"dim_y,omitempty"`
	Color              string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	ObjectLayerItemIds []string               `protobuf:"bytes,7,rep,name=object_layer_item_ids,json=objectLayerItemIds,proto3" json:"object_layer_item_ids,omitempty"`
	// Bot-specific fields
	SpawnRadius   float64 `protobuf:"fixed64,8,opt,name=spawn_radius,json=spawnRadius,proto3" json:"spawn_radius,omitempty"` // wandering radius (0 = use server default)
	AggroRange    float64 `protobuf:"fixed64,9,opt,name=aggro_range,json=aggroRange,proto3" json:"aggro_range,omitempty"`    // aggro detection range (0 = use server default)
	MaxLife       float64 `protobuf:"fixed64,10,opt,name=max_life,json=maxLife,proto3" json:"max_life,omitempty"`            // base max life (0 = use server default)
	LifeRegen     float64 `protobuf:"fixed64,11,opt,name=life_regen,json=lifeRegen,proto3" json:"life_regen,omitempty"`      // life regen rate (0 = use server default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMessage) Reset() {
	*x = EntityMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMessage) ProtoMessage() {}

func (x *EntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMessage.ProtoReflect.Descriptor instead.
func (*EntityMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{18}
}

func (x *EntityMessage) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityMessage) GetInitCellX() int32 {
	if x != nil {
		return x.InitCellX
	}
	return 0
}

func (x *EntityMessage) GetInitCellY() int32 {
	if x != nil {
		return x.InitCellY
	}
	return 0
}

func (x *EntityMessage) GetDimX() int32 {
	if x != nil {
		return x.DimX
	}
	return 0
}

func (x *EntityMessage) GetDimY() int32 {
	if x != nil {
		return x.DimY
	}
	return 0
}

func (x *EntityMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EntityMessage) GetObjectLayerItemIds() []string {
	if x != nil {
		return x.ObjectLayerItemIds
	}
	return nil
}

func (x *EntityMessage) GetSpawnRadius() float64 {
	if x != nil {
		return x.SpawnRadius
	}
	return 0
}

func (x *EntityMessage) GetAggroRange() float64 {
	if x != nil {
		return x.AggroRange
	}
	return 0
}

func (x *EntityMessage) GetMaxLife() float64 {
	if x != nil {
		return x.MaxLife
	}
	return 0
}

func (x *EntityMessage) GetLifeRegen() float64 {
	if x != nil {
		return x.LifeRegen
	}
	return 0
}

type MapDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GridX         int32                  `protobuf:"varint,4,opt,name=grid_x,json=gridX,proto3" json:"grid_x,omitempty"`
	GridY         int32                  `protobuf:"varint,5,opt,name=grid_y,json=gridY,proto3" json:"grid_y,omitempty"`
	CellWidth     int32                  `protobuf:"varint,6,opt,name=cell_width,json=cellWidth,proto3" json:"cell_width,omitempty"`
	CellHeight    int32                  `protobuf:"varint,7,opt,name=cell_height,json=cellHeight,proto3" json:"cell_height,omitempty"`
	Entities      []*EntityMessage       `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDataMessage) Reset() {
	*x = MapDataMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDataMessage) ProtoMessage() {}

func (x *MapDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDataMessage.ProtoReflect.Descriptor instead.
func (*MapDataMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{19}
}

func (x *MapDataMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *MapDataMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MapDataMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapDataMessage) GetGridX() int32 {
	if x != nil {
		return x.GridX
	}
	return 0
}

func (x *MapDataMessage) GetGridY() int32 {
	if x != nil {
		return x.GridY
	}
	return 0
}

func (x *MapDataMessage) GetCellWidth() int32 {
	if x != nil {
		return x.CellWidth
	}
	return 0
}

func (x *MapDataMessage) GetCellHeight() int32 {
	if x != nil {
		return x.CellHeight
	}
	return 0
}

func (x *MapDataMessage) GetEntities() []*EntityMessage {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetMapDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapCode       string                 `protobuf:"bytes,1,opt,name=map_code,json=mapCode,proto3" json:"map_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataRequest) Reset() {
	*x = GetMapDataRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataRequest) ProtoMessage() {}

func (x *GetMapDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataRequest.ProtoReflect.Descriptor instead.
func (*GetMapDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{20}
}

func (x *GetMapDataRequest) GetMapCode() string {
	if x != nil {
		return x.MapCode
	}
	return ""
}

type GetMapDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapDataMessage        `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataResponse) Reset() {
	*x = GetMapDataResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataResponse) ProtoMessage() {}

func (x *GetMapDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataResponse.ProtoReflect.Descriptor instead.
func (*GetMapDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{21}
}

func (x *GetMapDataResponse) GetMap() *MapDataMessage {
	if x != nil {
		return x.Map
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{22}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeMs  int64                  `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{23}
}

func (x *PingResponse) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type ObjectLayerManifestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerManifestEntry) Reset() {
	*x = ObjectLayerManifestEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerManifestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerManifestEntry) ProtoMessage() {}

func (x *ObjectLayerManifestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerManifestEntry.ProtoReflect.Descriptor instead.
func (*ObjectLayerManifestEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{24}
}

func (x *ObjectLayerManifestEntry) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ObjectLayerManifestEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetObjectLayerManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestRequest) Reset() {
	*x = GetObjectLayerManifestRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestRequest) ProtoMessage() {}

func (x *GetObjectLayerManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{25}
}

type GetObjectLayerManifestResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*ObjectLayerManifestEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestResponse) Reset() {
	*x = GetObjectLayerManifestResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestResponse) ProtoMessage() {}

func (x *GetObjectLayerManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestResponse.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{26}
}

func (x *GetObjectLayerManifestResponse) GetEntries() []*ObjectLayerManifestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_cyberia_proto protoreflect.FileDescriptor

const file_proto_cyberia_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cyberia.proto\x12\acyberia\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"#\n" +
	"\x05Vec2I\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xad\x01\n" +
	"\x05Stats\x12\x16\n" +
	"\x06effect\x18\x01 \x01(\x05R\x06effect\x12\x1e\n" +
	"\n" +
	"resistance\x18\x02 \x01(\x05R\n" +
	"resistance\x12\x18\n" +
	"\aagility\x18\x03 \x01(\x05R\aagility\x12\x14\n" +
	"\x05range\x18\x04 \x01(\x05R\x05range\x12\"\n" +
	"\fintelligence\x18\x05 \x01(\x05R\fintelligence\x12\x18\n" +
	"\autility\x18\x06 \x01(\x05R\autility\"n\n" +
	"\bItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tactivable\x18\x04 \x01(\bR\tactivable\"Q\n" +
	"\x06Ledger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"=\n" +
	"\x06Render\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12!\n" +
	"\fmetadata_cid\x18\x02 \x01(\tR\vmetadataCid\"\xc2\x02\n" +
	"\x12ObjectLayerMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12$\n" +
	"\x05stats\x18\x02 \x01(\v2\x0e.cyberia.StatsR\x05stats\x12%\n" +
	"\x04item\x18\x03 \x01(\v2\x11.cyberia.ItemInfoR\x04item\x12'\n" +
	"\x06ledger\x18\x04 \x01(\v2\x0f.cyberia.LedgerR\x06ledger\x12'\n" +
	"\x06render\x18\x05 \x01(\v2\x0f.cyberia.RenderR\x06render\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03cid\x18\a \x01(\tR\x03cid\x12%\n" +
	"\x0eframe_duration\x18\b \x01(\x05R\rframeDuration\x12!\n" +
	"\fis_stateless\x18\t \x01(\bR\visStateless\"F\n" +
	"\x1aGetObjectLayerBatchRequest\x12(\n" +
	"\x10item_type_filter\x18\x01 \x01(\tR\x0eitemTypeFilter\"0\n" +
	"\x15GetObjectLayerRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"z\n" +
	"\rFrameMetadata\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1f\n" +
	"\vframe_index\x18\x05 \x01(\x05R\n" +
	"frameIndex\"\xbd\b\n" +
	"\x0fDirectionFrames\x12/\n" +
	"\aup_idle\x18\x01 \x03(\v2\x16.cyberia.FrameMetadataR\x06upIdle\x123\n" +
	"\tdown_idle\x18\x02 \x03(\v2\x16.cyberia.FrameMetadataR\bdownIdle\x125\n" +
	"\n" +
	"right_idle\x18\x03 \x03(\v2\x16.cyberia.FrameMetadataR\trightIdle\x123\n" +
	"\tleft_idle\x18\x04 \x03(\v2\x16.cyberia.FrameMetadataR\bleftIdle\x12:\n" +
	"\rup_right_idle\x18\x05 \x03(\v2\x16.cyberia.FrameMetadataR\vupRightIdle\x12>\n" +
	"\x0fdown_right_idle\x18\x06 \x03(\v2\x16.cyberia.FrameMetadataR\rdownRightIdle\x128\n" +
	"\fup_left_idle\x18\a \x03(\v2\x16.cyberia.FrameMetadataR\n" +
	"upLeftIdle\x12<\n" +
	"\x0edown_left_idle\x18\b \x03(\v2\x16.cyberia.FrameMetadataR\fdownLeftIdle\x129\n" +
	"\fdefault_idle\x18\t \x03(\v2\x16.cyberia.FrameMetadataR\vdefaultIdle\x125\n" +
	"\n" +
	"up_walking\x18\n" +
	" \x03(\v2\x16.cyberia.FrameMetadataR\tupWalking\x129\n" +
	"\fdown_walking\x18\v \x03(\v2\x16.cyberia.FrameMetadataR\vdownWalking\x12;\n" +
	"\rright_walking\x18\f \x03(\v2\x16.cyberia.FrameMetadataR\frightWalking\x129\n" +
	"\fleft_walking\x18\r \x03(\v2\x16.cyberia.FrameMetadataR\vleftWalking\x12@\n" +
	"\x10up_right_walking\x18\x0e \x03(\v2\x16.cyberia.FrameMetadataR\x0eupRightWalking\x12D\n" +
	"\x12down_right_walking\x18\x0f \x03(\v2\x16.cyberia.FrameMetadataR\x10downRightWalking\x12>\n" +
	"\x0fup_left_walking\x18\x10 \x03(\v2\x16.cyberia.FrameMetadataR\rupLeftWalking\x12B\n" +
	"\x11down_left_walking\x18\x11 \x03(\v2\x16.cyberia.FrameMetadataR\x0fdownLeftWalking\x123\n" +
	"\tnone_idle\x18\x12 \x03(\v2\x16.cyberia.FrameMetadataR\bnoneIdle\"\x96\x02\n" +
	"\x17AtlasSpriteSheetMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid\x12\x19\n" +
	"\bitem_key\x18\x04 \x01(\tR\aitemKey\x12\x1f\n" +
	"\vatlas_width\x18\x05 \x01(\x05R\n" +
	"atlasWidth\x12!\n" +
	"\fatlas_height\x18\x06 \x01(\x05R\vatlasHeight\x12$\n" +
	"\x0ecell_pixel_dim\x18\a \x01(\x05R\fcellPixelDim\x120\n" +
	"\x06frames\x18\b \x01(\v2\x18.cyberia.DirectionFramesR\x06frames\"7\n" +
	"\x1aGetAtlasSpriteSheetRequest\x12\x19\n" +
	"\bitem_key\x18\x01 \x01(\tR\aitemKey\"!\n" +
	"\x1fGetAtlasSpriteSheetBatchRequest\"\xec\x01\n" +
	"\n" +
	"PortalEdge\x12&\n" +
	"\x0fsource_map_code\x18\x01 \x01(\tR\rsourceMapCode\x12\"\n" +
	"\rsource_cell_x\x18\x02 \x01(\x05R\vsourceCellX\x12\"\n" +
	"\rsource_cell_y\x18\x03 \x01(\x05R\vsourceCellY\x12&\n" +
	"\x0ftarget_map_code\x18\x04 \x01(\tR\rtargetMapCode\x12\"\n" +
	"\rtarget_cell_x\x18\x05 \x01(\x05R\vtargetCellX\x12\"\n" +
	"\rtarget_cell_y\x18\x06 \x01(\x05R\vtargetCellY\"\x8f\x02\n" +
	"\x0fInstanceMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tmap_codes\x18\x06 \x03(\tR\bmapCodes\x12-\n" +
	"\aportals\x18\a \x03(\v2\x13.cyberia.PortalEdgeR\aportals\x12#\n" +
	"\rtopology_mode\x18\b \x01(\tR\ftopologyMode\x12\x12\n" +
	"\x04seed\x18\t \x01(\tR\x04seed\"=\n" +
	"\x16GetFullInstanceRequest\x12#\n" +
	"\rinstance_code\x18\x01 \x01(\tR\finstanceCode\"\xbe\x01\n" +
	"\x17GetFullInstanceResponse\x124\n" +
	"\binstance\x18\x01 \x01(\v2\x18.cyberia.InstanceMessageR\binstance\x12+\n" +
	"\x04maps\x18\x02 \x03(\v2\x17.cyberia.MapDataMessageR\x04maps\x12@\n" +
	"\robject_layers\x18\x03 \x03(\v2\x1b.cyberia.ObjectLayerMessageR\fobjectLayers\"\xe1\x02\n" +
	"\rEntityMessage\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1e\n" +
	"\vinit_cell_x\x18\x02 \x01(\x05R\tinitCellX\x12\x1e\n" +
	"\vinit_cell_y\x18\x03 \x01(\x05R\tinitCellY\x12\x13\n" +
	"\x05dim_x\x18\x04 \x01(\x05R\x04dimX\x12\x13\n" +
	"\x05dim_y\x18\x05 \x01(\x05R\x04dimY\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x121\n" +
	"\x15object_layer_item_ids\x18\a \x03(\tR\x12objectLayerItemIds\x12!\n" +
	"\fspawn_radius\x18\b \x01(\x01R\vspawnRadius\x12\x1f\n" +
	"\vaggro_range\x18\t \x01(\x01R\n" +
	"aggroRange\x12\x19\n" +
	"\bmax_life\x18\n" +
	" \x01(\x01R\amaxLife\x12\x1d\n" +
	"\n" +
	"life_regen\x18\v \x01(\x01R\tlifeRegen\"\xf5\x01\n" +
	"\x0eMapDataMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06grid_x\x18\x04 \x01(\x05R\x05gridX\x12\x15\n" +
	"\x06grid_y\x18\x05 \x01(\x05R\x05gridY\x12\x1d\n" +
	"\n" +
	"cell_width\x18\x06 \x01(\x05R\tcellWidth\x12\x1f\n" +
	"\vcell_height\x18\a \x01(\x05R\n" +
	"cellHeight\x122\n" +
	"\bentities\x18\b \x03(\v2\x16.cyberia.EntityMessageR\bentities\".\n" +
	"\x11GetMapDataRequest\x12\x19\n" +
	"\bmap_code\x18\x01 \x01(\tR\amapCode\"?\n" +
	"\x12GetMapDataResponse\x12)\n" +
	"\x03map\x18\x01 \x01(\v2\x17.cyberia.MapDataMessageR\x03map\"\r\n" +
	"\vPingRequest\"4\n" +
	"\fPingResponse\x12$\n" +
	"\x0eserver_time_ms\x18\x01 \x01(\x03R\fserverTimeMs\"K\n" +
	"\x18ObjectLayerManifestEntry\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x1f\n" +
	"\x1dGetObjectLayerManifestRequest\"]\n" +
	"\x1eGetObjectLayerManifestResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.cyberia.ObjectLayerManifestEntryR\aentries2\xc3\x05\n" +
	"\x12CyberiaDataService\x12T\n" +
	"\x0fGetFullInstance\x12\x1f.cyberia.GetFullInstanceRequest\x1a .cyberia.GetFullInstanceResponse\x12E\n" +
	"\n" +
	"GetMapData\x12\x1a.cyberia.GetMapDataRequest\x1a\x1b.cyberia.GetMapDataResponse\x12Y\n" +
	"\x13GetObjectLayerBatch\x12#.cyberia.GetObjectLayerBatchRequest\x1a\x1b.cyberia.ObjectLayerMessage0\x01\x12M\n" +
	"\x0eGetObjectLayer\x12\x1e.cyberia.GetObjectLayerRequest\x1a\x1b.cyberia.ObjectLayerMessage\x12\\\n" +
	"\x13GetAtlasSpriteSheet\x12#.cyberia.GetAtlasSpriteSheetRequest\x1a .cyberia.AtlasSpriteSheetMessage\x12h\n" +
	"\x18GetAtlasSpriteSheetBatch\x12(.cyberia.GetAtlasSpriteSheetBatchRequest\x1a .cyberia.AtlasSpriteSheetMessage0\x01\x123\n" +
	"\x04Ping\x12\x14.cyberia.PingRequest\x1a\x15.cyberia.PingResponse\x12i\n" +
	"\x16GetObjectLayerManifest\x12&.cyberia.GetObjectLayerManifestRequest\x1a'.cyberia.GetObjectLayerManifestResponseB\x16Z\x14cyberia-server/protob\x06proto3"

var (
	file_proto_cyberia_proto_rawDescOnce sync.Once
	file_proto_cyberia_proto_rawDescData []byte
)

func file_proto_cyberia_proto_rawDescGZIP() []byte {
	file_proto_cyberia_proto_rawDescOnce.Do(func() {
		file_proto_cyberia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)))
	})
	return file_proto_cyberia_proto_rawDescData
}

var file_proto_cyberia_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_cyberia_proto_goTypes = []any{
	(*Vec2)(nil),                            // 0: cyberia.Vec2
	(*Vec2I)(nil),                           // 1: cyberia.Vec2I
	(*Stats)(nil),                           // 2: cyberia.Stats
	(*ItemInfo)(nil),                        // 3: cyberia.ItemInfo
	(*Ledger)(nil),                          // 4: cyberia.Ledger
	(*Render)(nil),                          // 5: cyberia.Render
	(*ObjectLayerMessage)(nil),              // 6: cyberia.ObjectLayerMessage
	(*GetObjectLayerBatchRequest)(nil),      // 7: cyberia.GetObjectLayerBatchRequest
	(*GetObjectLayerRequest)(nil),           // 8: cyberia.GetObjectLayerRequest
	(*FrameMetadata)(nil),                   // 9: cyberia.FrameMetadata
	(*DirectionFrames)(nil),                 // 10: cyberia.DirectionFrames
	(*AtlasSpriteSheetMessage)(nil),         // 11: cyberia.AtlasSpriteSheetMessage
	(*GetAtlasSpriteSheetRequest)(nil),      // 12: cyberia.GetAtlasSpriteSheetRequest
	(*GetAtlasSpriteSheetBatchRequest)(nil), // 13: cyberia.GetAtlasSpriteSheetBatchRequest
	(*PortalEdge)(nil),                      // 14: cyberia.PortalEdge
	(*InstanceMessage)(nil),                 // 15: cyberia.InstanceMessage
	(*GetFullInstanceRequest)(nil),          // 16: cyberia.GetFullInstanceRequest
	(*GetFullInstanceResponse)(nil),         // 17: cyberia.GetFullInstanceResponse
	(*EntityMessage)(nil),                   // 18: cyberia.EntityMessage
	(*MapDataMessage)(nil),                  // 19: cyberia.MapDataMessage
	(*GetMapDataRequest)(nil),               // 20: cyberia.GetMapDataRequest
	(*GetMapDataResponse)(nil),              // 21: cyberia.GetMapDataResponse
	(*PingRequest)(nil),                     // 22: cyberia.PingRequest
	(*PingResponse)(nil),                    // 23: cyberia.PingResponse
	(*ObjectLayerManifestEntry)(nil),        // 24: cyberia.ObjectLayerManifestEntry
	(*GetObjectLayerManifestRequest)(nil),   // 25: cyberia.GetObjectLayerManifestRequest
	(*GetObjectLayerManifestResponse)(nil),  // 26: cyberia.GetObjectLayerManifestResponse
}
var file_proto_cyberia_proto_depIdxs = []int32{
	2,  // 0: cyberia.ObjectLayerMessage.stats:type_name -> cyberia.Stats
	3,  // 1: cyberia.ObjectLayerMessage.item:type_name -> cyberia.ItemInfo
	4,  // 2: cyberia.ObjectLayerMessage.ledger:type_name -> cyberia.Ledger
	5,  // 3: cyberia.ObjectLayerMessage.render:type_name -> cyberia.Render
	9,  // 4: cyberia.DirectionFrames.up_idle:type_name -> cyberia.FrameMetadata
	9,  // 5: cyberia.DirectionFrames.down_idle:type_name -> cyberia.FrameMetadata
	9,  // 6: cyberia.DirectionFrames.right_idle:type_name -> cyberia.FrameMetadata
	9,  // 7: cyberia.DirectionFrames.left_idle:type_name -> cyberia.FrameMetadata
	9,  // 8: cyberia.DirectionFrames.up_right_idle:type_name -> cyberia.FrameMetadata
	9,  // 9: cyberia.DirectionFrames.down_right_idle:type_name -> cyberia.FrameMetadata
	9,  // 10: cyberia.DirectionFrames.up_left_idle:type_name -> cyberia.FrameMetadata
	9,  // 11: cyberia.DirectionFrames.down_left_idle:type_name -> cyberia.FrameMetadata
	9,  // 12: cyberia.DirectionFrames.default_idle:type_name -> cyberia.FrameMetadata
	9,  // 13: cyberia.DirectionFrames.up_walking:type_name -> cyberia.FrameMetadata
	9,  // 14: cyberia.DirectionFrames.down_walking:type_name -> cyberia.FrameMetadata
	9,  // 15: cyberia.DirectionFrames.right_walking:type_name -> cyberia.FrameMetadata
	9,  // 16: cyberia.DirectionFrames.left_walking:type_name -> cyberia.FrameMetadata
	9,  // 17: cyberia.DirectionFrames.up_right_walking:type_name -> cyberia.FrameMetadata
	9,  // 18: cyberia.DirectionFrames.down_right_walking:type_name -> cyberia.FrameMetadata
	9,  // 19: cyberia.DirectionFrames.up_left_walking:type_name -> cyberia.FrameMetadata
	9,  // 20: cyberia.DirectionFrames.down_left_walking:type_name -> cyberia.FrameMetadata
	9,  // 21: cyberia.DirectionFrames.none_idle:type_name -> cyberia.FrameMetadata
	10, // 22: cyberia.AtlasSpriteSheetMessage.frames:type_name -> cyberia.DirectionFrames
	14, // 23: cyberia.InstanceMessage.portals:type_name -> cyberia.PortalEdge
	15, // 24: cyberia.GetFullInstanceResponse.instance:type_name -> cyberia.InstanceMessage
	19, // 25: cyberia.GetFullInstanceResponse.maps:type_name -> cyberia.MapDataMessage
	6,  // 26: cyberia.GetFullInstanceResponse.object_layers:type_name -> cyberia.ObjectLayerMessage
	18, // 27: cyberia.MapDataMessage.entities:type_name -> cyberia.EntityMessage
	19, // 28: cyberia.GetMapDataResponse.map:type_name -> cyberia.MapDataMessage
	24, // 29: cyberia.GetObjectLayerManifestResponse.entries:type_name -> cyberia.ObjectLayerManifestEntry
	16, // 30: cyberia.CyberiaDataService.GetFullInstance:input_type -> cyberia.GetFullInstanceRequest
	20, // 31: cyberia.CyberiaDataService.GetMapData:input_type -> cyberia.GetMapDataRequest
	7,  // 32: cyberia.CyberiaDataService.GetObjectLayerBatch:input_type -> cyberia.GetObjectLayerBatchRequest
	8,  // 33: cyberia.CyberiaDataService.GetObjectLayer:input_type -> cyberia.GetObjectLayerRequest
	12, // 34: cyberia.CyberiaDataService.GetAtlasSpriteSheet:input_type -> cyberia.GetAtlasSpriteSheetRequest
	13, // 35: cyberia.CyberiaDataService.GetAtlasSpriteSheetBatch:input_type -> cyberia.GetAtlasSpriteSheetBatchRequest
	22, // 36: cyberia.CyberiaDataService.Ping:input_type -> cyberia.PingRequest
	25, // 37: cyberia.CyberiaDataService.GetObjectLayerManifest:input_type -> cyberia.GetObjectLayerManifestRequest
	17, // 38: cyberia.CyberiaDataService.GetFullInstance:output_type -> cyberia.GetFullInstanceResponse
	21, // 39: cyberia.CyberiaDataService.GetMapData:output_type -> cyberia.GetMapDataResponse
	6,  // 40: cyberia.CyberiaDataService.GetObjectLayerBatch:output_type -> cyberia.ObjectLayerMessage
	6,  // 41: cyberia.CyberiaDataService.GetObjectLayer:output_type -> cyberia.ObjectLayerMessage
	11, // 42: cyberia.CyberiaDataService.GetAtlasSpriteSheet:output_type -> cyberia.AtlasSpriteSheetMessage
	11, // 43: cyberia.CyberiaDataService.GetAtlasSpriteSheetBatch:output_type -> cyberia.AtlasSpriteSheetMessage
	23, // 44: cyberia.CyberiaDataService.Ping:output_type -> cyberia.PingResponse
	26, // 45: cyberia.CyberiaDataService.GetObjectLayerManifest:output_type -> cyberia.GetObjectLayerManifestResponse
	38, // [38:46] is the sub-list for method output_type
	30, // [30:38] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_cyberia_proto_init() }
func file_proto_cyberia_proto_init() {
	if File_proto_cyberia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cyberia_proto_goTypes,
		DependencyIndexes: file_proto_cyberia_proto_depIdxs,
		MessageInfos:      file_proto_cyberia_proto_msgTypes,
	}.Build()
	File_proto_cyberia_proto = out.File
	file_proto_cyberia_proto_goTypes = nil
	file_proto_cyberia_proto_depIdxs = nil
}
