// Protocol Buffers schema for Cyberia Online gRPC data pipeline.
//
// This service runs on the Engine-Cyberia (Node.js) side.
// The Cyberia-Server (Go) acts as the gRPC **client**, calling
// these RPCs to fetch game data for world reconstruction.
//
// Design rules:
//   1. Read-only — no create / update / delete.
//   2. Batch-friendly — large collections streamed or paginated.
//   3. Live-reload aware — version fields let the Go server detect
//      stale data and perform surgical in-memory replacement.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: proto/cyberia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_cyberia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Vec2I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2I) Reset() {
	*x = Vec2I{}
	mi := &file_proto_cyberia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2I) ProtoMessage() {}

func (x *Vec2I) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2I.ProtoReflect.Descriptor instead.
func (*Vec2I) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{1}
}

func (x *Vec2I) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2I) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        int32                  `protobuf:"varint,1,opt,name=effect,proto3" json:"effect,omitempty"`
	Resistance    int32                  `protobuf:"varint,2,opt,name=resistance,proto3" json:"resistance,omitempty"`
	Agility       int32                  `protobuf:"varint,3,opt,name=agility,proto3" json:"agility,omitempty"`
	Range         int32                  `protobuf:"varint,4,opt,name=range,proto3" json:"range,omitempty"`
	Intelligence  int32                  `protobuf:"varint,5,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Utility       int32                  `protobuf:"varint,6,opt,name=utility,proto3" json:"utility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_cyberia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *Stats) GetResistance() int32 {
	if x != nil {
		return x.Resistance
	}
	return 0
}

func (x *Stats) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Stats) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *Stats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Stats) GetUtility() int32 {
	if x != nil {
		return x.Utility
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Activable     bool                   `protobuf:"varint,4,opt,name=activable,proto3" json:"activable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_proto_cyberia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{3}
}

func (x *ItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ItemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemInfo) GetActivable() bool {
	if x != nil {
		return x.Activable
	}
	return false
}

type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // ERC1155 | OFF_CHAIN
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_proto_cyberia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{4}
}

func (x *Ledger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ledger) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ledger) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type Render struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`                                    // IPFS CID atlas PNG
	MetadataCid   string                 `protobuf:"bytes,2,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"` // IPFS CID atlas metadata JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Render) Reset() {
	*x = Render{}
	mi := &file_proto_cyberia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Render) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Render) ProtoMessage() {}

func (x *Render) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Render.ProtoReflect.Descriptor instead.
func (*Render) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{5}
}

func (x *Render) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Render) GetMetadataCid() string {
	if x != nil {
		return x.MetadataCid
	}
	return ""
}

type ObjectLayerMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MongoId string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"` // MongoDB _id
	Stats   *Stats                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Item    *ItemInfo              `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Ledger  *Ledger                `protobuf:"bytes,4,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Render  *Render                `protobuf:"bytes,5,opt,name=render,proto3" json:"render,omitempty"`
	Sha256  string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Cid     string                 `protobuf:"bytes,7,opt,name=cid,proto3" json:"cid,omitempty"` // IPFS CID of the OL data JSON
	// Animation metadata (populated from ObjectLayerRenderFrames ref)
	FrameDuration int32 `protobuf:"varint,8,opt,name=frame_duration,json=frameDuration,proto3" json:"frame_duration,omitempty"` // ms per frame
	IsStateless   bool  `protobuf:"varint,9,opt,name=is_stateless,json=isStateless,proto3" json:"is_stateless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerMessage) Reset() {
	*x = ObjectLayerMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerMessage) ProtoMessage() {}

func (x *ObjectLayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerMessage.ProtoReflect.Descriptor instead.
func (*ObjectLayerMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectLayerMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *ObjectLayerMessage) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ObjectLayerMessage) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ObjectLayerMessage) GetLedger() *Ledger {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *ObjectLayerMessage) GetRender() *Render {
	if x != nil {
		return x.Render
	}
	return nil
}

func (x *ObjectLayerMessage) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ObjectLayerMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ObjectLayerMessage) GetFrameDuration() int32 {
	if x != nil {
		return x.FrameDuration
	}
	return 0
}

func (x *ObjectLayerMessage) GetIsStateless() bool {
	if x != nil {
		return x.IsStateless
	}
	return false
}

type GetObjectLayerBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by item type (e.g. "skin", "weapon").
	// Empty = return all.
	ItemTypeFilter string `protobuf:"bytes,1,opt,name=item_type_filter,json=itemTypeFilter,proto3" json:"item_type_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectLayerBatchRequest) Reset() {
	*x = GetObjectLayerBatchRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerBatchRequest) ProtoMessage() {}

func (x *GetObjectLayerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerBatchRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectLayerBatchRequest) GetItemTypeFilter() string {
	if x != nil {
		return x.ItemTypeFilter
	}
	return ""
}

type GetObjectLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerRequest) Reset() {
	*x = GetObjectLayerRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerRequest) ProtoMessage() {}

func (x *GetObjectLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectLayerRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type FrameMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FrameIndex    int32                  `protobuf:"varint,5,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameMetadata) Reset() {
	*x = FrameMetadata{}
	mi := &file_proto_cyberia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMetadata) ProtoMessage() {}

func (x *FrameMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMetadata.ProtoReflect.Descriptor instead.
func (*FrameMetadata) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{9}
}

func (x *FrameMetadata) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FrameMetadata) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FrameMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameMetadata) GetFrameIndex() int32 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

type DirectionFrames struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpIdle           []*FrameMetadata       `protobuf:"bytes,1,rep,name=up_idle,json=upIdle,proto3" json:"up_idle,omitempty"`
	DownIdle         []*FrameMetadata       `protobuf:"bytes,2,rep,name=down_idle,json=downIdle,proto3" json:"down_idle,omitempty"`
	RightIdle        []*FrameMetadata       `protobuf:"bytes,3,rep,name=right_idle,json=rightIdle,proto3" json:"right_idle,omitempty"`
	LeftIdle         []*FrameMetadata       `protobuf:"bytes,4,rep,name=left_idle,json=leftIdle,proto3" json:"left_idle,omitempty"`
	UpRightIdle      []*FrameMetadata       `protobuf:"bytes,5,rep,name=up_right_idle,json=upRightIdle,proto3" json:"up_right_idle,omitempty"`
	DownRightIdle    []*FrameMetadata       `protobuf:"bytes,6,rep,name=down_right_idle,json=downRightIdle,proto3" json:"down_right_idle,omitempty"`
	UpLeftIdle       []*FrameMetadata       `protobuf:"bytes,7,rep,name=up_left_idle,json=upLeftIdle,proto3" json:"up_left_idle,omitempty"`
	DownLeftIdle     []*FrameMetadata       `protobuf:"bytes,8,rep,name=down_left_idle,json=downLeftIdle,proto3" json:"down_left_idle,omitempty"`
	DefaultIdle      []*FrameMetadata       `protobuf:"bytes,9,rep,name=default_idle,json=defaultIdle,proto3" json:"default_idle,omitempty"`
	UpWalking        []*FrameMetadata       `protobuf:"bytes,10,rep,name=up_walking,json=upWalking,proto3" json:"up_walking,omitempty"`
	DownWalking      []*FrameMetadata       `protobuf:"bytes,11,rep,name=down_walking,json=downWalking,proto3" json:"down_walking,omitempty"`
	RightWalking     []*FrameMetadata       `protobuf:"bytes,12,rep,name=right_walking,json=rightWalking,proto3" json:"right_walking,omitempty"`
	LeftWalking      []*FrameMetadata       `protobuf:"bytes,13,rep,name=left_walking,json=leftWalking,proto3" json:"left_walking,omitempty"`
	UpRightWalking   []*FrameMetadata       `protobuf:"bytes,14,rep,name=up_right_walking,json=upRightWalking,proto3" json:"up_right_walking,omitempty"`
	DownRightWalking []*FrameMetadata       `protobuf:"bytes,15,rep,name=down_right_walking,json=downRightWalking,proto3" json:"down_right_walking,omitempty"`
	UpLeftWalking    []*FrameMetadata       `protobuf:"bytes,16,rep,name=up_left_walking,json=upLeftWalking,proto3" json:"up_left_walking,omitempty"`
	DownLeftWalking  []*FrameMetadata       `protobuf:"bytes,17,rep,name=down_left_walking,json=downLeftWalking,proto3" json:"down_left_walking,omitempty"`
	NoneIdle         []*FrameMetadata       `protobuf:"bytes,18,rep,name=none_idle,json=noneIdle,proto3" json:"none_idle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectionFrames) Reset() {
	*x = DirectionFrames{}
	mi := &file_proto_cyberia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectionFrames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectionFrames) ProtoMessage() {}

func (x *DirectionFrames) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectionFrames.ProtoReflect.Descriptor instead.
func (*DirectionFrames) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{10}
}

func (x *DirectionFrames) GetUpIdle() []*FrameMetadata {
	if x != nil {
		return x.UpIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownIdle() []*FrameMetadata {
	if x != nil {
		return x.DownIdle
	}
	return nil
}

func (x *DirectionFrames) GetRightIdle() []*FrameMetadata {
	if x != nil {
		return x.RightIdle
	}
	return nil
}

func (x *DirectionFrames) GetLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.LeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpRightIdle() []*FrameMetadata {
	if x != nil {
		return x.UpRightIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownRightIdle() []*FrameMetadata {
	if x != nil {
		return x.DownRightIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.UpLeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetDownLeftIdle() []*FrameMetadata {
	if x != nil {
		return x.DownLeftIdle
	}
	return nil
}

func (x *DirectionFrames) GetDefaultIdle() []*FrameMetadata {
	if x != nil {
		return x.DefaultIdle
	}
	return nil
}

func (x *DirectionFrames) GetUpWalking() []*FrameMetadata {
	if x != nil {
		return x.UpWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownWalking() []*FrameMetadata {
	if x != nil {
		return x.DownWalking
	}
	return nil
}

func (x *DirectionFrames) GetRightWalking() []*FrameMetadata {
	if x != nil {
		return x.RightWalking
	}
	return nil
}

func (x *DirectionFrames) GetLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.LeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetUpRightWalking() []*FrameMetadata {
	if x != nil {
		return x.UpRightWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownRightWalking() []*FrameMetadata {
	if x != nil {
		return x.DownRightWalking
	}
	return nil
}

func (x *DirectionFrames) GetUpLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.UpLeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetDownLeftWalking() []*FrameMetadata {
	if x != nil {
		return x.DownLeftWalking
	}
	return nil
}

func (x *DirectionFrames) GetNoneIdle() []*FrameMetadata {
	if x != nil {
		return x.NoneIdle
	}
	return nil
}

type AtlasSpriteSheetMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // File doc _id for REST blob fetch
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`                     // IPFS CID of atlas PNG
	ItemKey       string                 `protobuf:"bytes,4,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"`
	AtlasWidth    int32                  `protobuf:"varint,5,opt,name=atlas_width,json=atlasWidth,proto3" json:"atlas_width,omitempty"`
	AtlasHeight   int32                  `protobuf:"varint,6,opt,name=atlas_height,json=atlasHeight,proto3" json:"atlas_height,omitempty"`
	CellPixelDim  int32                  `protobuf:"varint,7,opt,name=cell_pixel_dim,json=cellPixelDim,proto3" json:"cell_pixel_dim,omitempty"`
	Frames        *DirectionFrames       `protobuf:"bytes,8,opt,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtlasSpriteSheetMessage) Reset() {
	*x = AtlasSpriteSheetMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtlasSpriteSheetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtlasSpriteSheetMessage) ProtoMessage() {}

func (x *AtlasSpriteSheetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtlasSpriteSheetMessage.ProtoReflect.Descriptor instead.
func (*AtlasSpriteSheetMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{11}
}

func (x *AtlasSpriteSheetMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

func (x *AtlasSpriteSheetMessage) GetAtlasWidth() int32 {
	if x != nil {
		return x.AtlasWidth
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetAtlasHeight() int32 {
	if x != nil {
		return x.AtlasHeight
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetCellPixelDim() int32 {
	if x != nil {
		return x.CellPixelDim
	}
	return 0
}

func (x *AtlasSpriteSheetMessage) GetFrames() *DirectionFrames {
	if x != nil {
		return x.Frames
	}
	return nil
}

type GetAtlasSpriteSheetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemKey       string                 `protobuf:"bytes,1,opt,name=item_key,json=itemKey,proto3" json:"item_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtlasSpriteSheetRequest) Reset() {
	*x = GetAtlasSpriteSheetRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtlasSpriteSheetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtlasSpriteSheetRequest) ProtoMessage() {}

func (x *GetAtlasSpriteSheetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtlasSpriteSheetRequest.ProtoReflect.Descriptor instead.
func (*GetAtlasSpriteSheetRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{12}
}

func (x *GetAtlasSpriteSheetRequest) GetItemKey() string {
	if x != nil {
		return x.ItemKey
	}
	return ""
}

type GetAtlasSpriteSheetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAtlasSpriteSheetBatchRequest) Reset() {
	*x = GetAtlasSpriteSheetBatchRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAtlasSpriteSheetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAtlasSpriteSheetBatchRequest) ProtoMessage() {}

func (x *GetAtlasSpriteSheetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAtlasSpriteSheetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetAtlasSpriteSheetBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{13}
}

type PortalEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceMapCode string                 `protobuf:"bytes,1,opt,name=source_map_code,json=sourceMapCode,proto3" json:"source_map_code,omitempty"`
	SourceCellX   int32                  `protobuf:"varint,2,opt,name=source_cell_x,json=sourceCellX,proto3" json:"source_cell_x,omitempty"`
	SourceCellY   int32                  `protobuf:"varint,3,opt,name=source_cell_y,json=sourceCellY,proto3" json:"source_cell_y,omitempty"`
	TargetMapCode string                 `protobuf:"bytes,4,opt,name=target_map_code,json=targetMapCode,proto3" json:"target_map_code,omitempty"`
	TargetCellX   int32                  `protobuf:"varint,5,opt,name=target_cell_x,json=targetCellX,proto3" json:"target_cell_x,omitempty"`
	TargetCellY   int32                  `protobuf:"varint,6,opt,name=target_cell_y,json=targetCellY,proto3" json:"target_cell_y,omitempty"`
	// Transport behaviour: inter-portal | inter-random | intra-random | intra-portal
	PortalMode    string `protobuf:"bytes,7,opt,name=portal_mode,json=portalMode,proto3" json:"portal_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalEdge) Reset() {
	*x = PortalEdge{}
	mi := &file_proto_cyberia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalEdge) ProtoMessage() {}

func (x *PortalEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalEdge.ProtoReflect.Descriptor instead.
func (*PortalEdge) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{14}
}

func (x *PortalEdge) GetSourceMapCode() string {
	if x != nil {
		return x.SourceMapCode
	}
	return ""
}

func (x *PortalEdge) GetSourceCellX() int32 {
	if x != nil {
		return x.SourceCellX
	}
	return 0
}

func (x *PortalEdge) GetSourceCellY() int32 {
	if x != nil {
		return x.SourceCellY
	}
	return 0
}

func (x *PortalEdge) GetTargetMapCode() string {
	if x != nil {
		return x.TargetMapCode
	}
	return ""
}

func (x *PortalEdge) GetTargetCellX() int32 {
	if x != nil {
		return x.TargetCellX
	}
	return 0
}

func (x *PortalEdge) GetTargetCellY() int32 {
	if x != nil {
		return x.TargetCellY
	}
	return 0
}

func (x *PortalEdge) GetPortalMode() string {
	if x != nil {
		return x.PortalMode
	}
	return ""
}

type InstanceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	MapCodes      []string               `protobuf:"bytes,6,rep,name=map_codes,json=mapCodes,proto3" json:"map_codes,omitempty"` // vertex set
	Portals       []*PortalEdge          `protobuf:"bytes,7,rep,name=portals,proto3" json:"portals,omitempty"`                   // edge set
	TopologyMode  string                 `protobuf:"bytes,8,opt,name=topology_mode,json=topologyMode,proto3" json:"topology_mode,omitempty"`
	Seed          string                 `protobuf:"bytes,9,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceMessage) Reset() {
	*x = InstanceMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMessage) ProtoMessage() {}

func (x *InstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMessage.ProtoReflect.Descriptor instead.
func (*InstanceMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{15}
}

func (x *InstanceMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *InstanceMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstanceMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InstanceMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InstanceMessage) GetMapCodes() []string {
	if x != nil {
		return x.MapCodes
	}
	return nil
}

func (x *InstanceMessage) GetPortals() []*PortalEdge {
	if x != nil {
		return x.Portals
	}
	return nil
}

func (x *InstanceMessage) GetTopologyMode() string {
	if x != nil {
		return x.TopologyMode
	}
	return ""
}

func (x *InstanceMessage) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type GetFullInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceCode  string                 `protobuf:"bytes,1,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceRequest) Reset() {
	*x = GetFullInstanceRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceRequest) ProtoMessage() {}

func (x *GetFullInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetFullInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{16}
}

func (x *GetFullInstanceRequest) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

type GetFullInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *InstanceMessage       `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Maps          []*MapDataMessage      `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`
	ObjectLayers  []*ObjectLayerMessage  `protobuf:"bytes,3,rep,name=object_layers,json=objectLayers,proto3" json:"object_layers,omitempty"`
	Config        *InstanceConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceResponse) Reset() {
	*x = GetFullInstanceResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceResponse) ProtoMessage() {}

func (x *GetFullInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetFullInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{17}
}

func (x *GetFullInstanceResponse) GetInstance() *InstanceMessage {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetFullInstanceResponse) GetMaps() []*MapDataMessage {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *GetFullInstanceResponse) GetObjectLayers() []*ObjectLayerMessage {
	if x != nil {
		return x.ObjectLayers
	}
	return nil
}

func (x *GetFullInstanceResponse) GetConfig() *InstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ColorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	R             int32                  `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G             int32                  `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B             int32                  `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	A             int32                  `protobuf:"varint,5,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorEntry) Reset() {
	*x = ColorEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorEntry) ProtoMessage() {}

func (x *ColorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorEntry.ProtoReflect.Descriptor instead.
func (*ColorEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{18}
}

func (x *ColorEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ColorEntry) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *ColorEntry) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *ColorEntry) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ColorEntry) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type DefaultObjectLayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultObjectLayerState) Reset() {
	*x = DefaultObjectLayerState{}
	mi := &file_proto_cyberia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultObjectLayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultObjectLayerState) ProtoMessage() {}

func (x *DefaultObjectLayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultObjectLayerState.ProtoReflect.Descriptor instead.
func (*DefaultObjectLayerState) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{19}
}

func (x *DefaultObjectLayerState) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DefaultObjectLayerState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DefaultObjectLayerState) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SkillConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerItemId string                 `protobuf:"bytes,1,opt,name=trigger_item_id,json=triggerItemId,proto3" json:"trigger_item_id,omitempty"` // item that triggers the skill
	LogicEventIds []string               `protobuf:"bytes,4,rep,name=logic_event_ids,json=logicEventIds,proto3" json:"logic_event_ids,omitempty"` // ordered list of skill handler keys to execute ("atlas_pistol_mk2_logic", "doppelganger", …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillConfigEntry) Reset() {
	*x = SkillConfigEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillConfigEntry) ProtoMessage() {}

func (x *SkillConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillConfigEntry.ProtoReflect.Descriptor instead.
func (*SkillConfigEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{20}
}

func (x *SkillConfigEntry) GetTriggerItemId() string {
	if x != nil {
		return x.TriggerItemId
	}
	return ""
}

func (x *SkillConfigEntry) GetLogicEventIds() []string {
	if x != nil {
		return x.LogicEventIds
	}
	return nil
}

// SkillRules groups the numeric tuning parameters for each skill archetype.
// These are instance-level defaults; individual SkillConfigEntry entries define
// WHICH items trigger WHICH logic, while SkillRules defines HOW that logic behaves.
type SkillRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Projectile skill ──
	ProjectileSpawnChance     float64 `protobuf:"fixed64,1,opt,name=projectile_spawn_chance,json=projectileSpawnChance,proto3" json:"projectile_spawn_chance,omitempty"`             // base probability [0,1] per action tick
	ProjectileLifetimeMs      int32   `protobuf:"varint,2,opt,name=projectile_lifetime_ms,json=projectileLifetimeMs,proto3" json:"projectile_lifetime_ms,omitempty"`                 // base projectile TTL in ms (Range stat adds extra)
	ProjectileWidth           float64 `protobuf:"fixed64,3,opt,name=projectile_width,json=projectileWidth,proto3" json:"projectile_width,omitempty"`                                 // projectile entity width in grid cells
	ProjectileHeight          float64 `protobuf:"fixed64,4,opt,name=projectile_height,json=projectileHeight,proto3" json:"projectile_height,omitempty"`                              // projectile entity height in grid cells
	ProjectileSpeedMultiplier float64 `protobuf:"fixed64,5,opt,name=projectile_speed_multiplier,json=projectileSpeedMultiplier,proto3" json:"projectile_speed_multiplier,omitempty"` // multiplier applied on top of entity_base_speed
	// ── Doppelganger skill ──
	DoppelgangerSpawnChance         float64 `protobuf:"fixed64,6,opt,name=doppelganger_spawn_chance,json=doppelgangerSpawnChance,proto3" json:"doppelganger_spawn_chance,omitempty"`                           // base probability [0,1] per action tick
	DoppelgangerLifetimeMs          int32   `protobuf:"varint,7,opt,name=doppelganger_lifetime_ms,json=doppelgangerLifetimeMs,proto3" json:"doppelganger_lifetime_ms,omitempty"`                               // base doppelganger TTL in ms (Range adds extra)
	DoppelgangerSpawnRadius         float64 `protobuf:"fixed64,8,opt,name=doppelganger_spawn_radius,json=doppelgangerSpawnRadius,proto3" json:"doppelganger_spawn_radius,omitempty"`                           // wander radius around spawn point in cells
	DoppelgangerInitialLifeFraction float64 `protobuf:"fixed64,9,opt,name=doppelganger_initial_life_fraction,json=doppelgangerInitialLifeFraction,proto3" json:"doppelganger_initial_life_fraction,omitempty"` // fraction of entity_base_max_life at spawn
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *SkillRules) Reset() {
	*x = SkillRules{}
	mi := &file_proto_cyberia_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRules) ProtoMessage() {}

func (x *SkillRules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRules.ProtoReflect.Descriptor instead.
func (*SkillRules) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{21}
}

func (x *SkillRules) GetProjectileSpawnChance() float64 {
	if x != nil {
		return x.ProjectileSpawnChance
	}
	return 0
}

func (x *SkillRules) GetProjectileLifetimeMs() int32 {
	if x != nil {
		return x.ProjectileLifetimeMs
	}
	return 0
}

func (x *SkillRules) GetProjectileWidth() float64 {
	if x != nil {
		return x.ProjectileWidth
	}
	return 0
}

func (x *SkillRules) GetProjectileHeight() float64 {
	if x != nil {
		return x.ProjectileHeight
	}
	return 0
}

func (x *SkillRules) GetProjectileSpeedMultiplier() float64 {
	if x != nil {
		return x.ProjectileSpeedMultiplier
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerSpawnChance() float64 {
	if x != nil {
		return x.DoppelgangerSpawnChance
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerLifetimeMs() int32 {
	if x != nil {
		return x.DoppelgangerLifetimeMs
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerSpawnRadius() float64 {
	if x != nil {
		return x.DoppelgangerSpawnRadius
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerInitialLifeFraction() float64 {
	if x != nil {
		return x.DoppelgangerInitialLifeFraction
	}
	return 0
}

type InstanceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Rendering / camera ──
	CellSize                  float64       `protobuf:"fixed64,1,opt,name=cell_size,json=cellSize,proto3" json:"cell_size,omitempty"`
	Fps                       int32         `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	InterpolationMs           int32         `protobuf:"varint,3,opt,name=interpolation_ms,json=interpolationMs,proto3" json:"interpolation_ms,omitempty"`
	DefaultObjWidth           float64       `protobuf:"fixed64,4,opt,name=default_obj_width,json=defaultObjWidth,proto3" json:"default_obj_width,omitempty"`
	DefaultObjHeight          float64       `protobuf:"fixed64,5,opt,name=default_obj_height,json=defaultObjHeight,proto3" json:"default_obj_height,omitempty"`
	CameraSmoothing           float64       `protobuf:"fixed64,6,opt,name=camera_smoothing,json=cameraSmoothing,proto3" json:"camera_smoothing,omitempty"`
	CameraZoom                float64       `protobuf:"fixed64,7,opt,name=camera_zoom,json=cameraZoom,proto3" json:"camera_zoom,omitempty"`
	DefaultWidthScreenFactor  float64       `protobuf:"fixed64,8,opt,name=default_width_screen_factor,json=defaultWidthScreenFactor,proto3" json:"default_width_screen_factor,omitempty"`
	DefaultHeightScreenFactor float64       `protobuf:"fixed64,9,opt,name=default_height_screen_factor,json=defaultHeightScreenFactor,proto3" json:"default_height_screen_factor,omitempty"`
	DevUi                     bool          `protobuf:"varint,10,opt,name=dev_ui,json=devUi,proto3" json:"dev_ui,omitempty"`
	Colors                    []*ColorEntry `protobuf:"bytes,11,rep,name=colors,proto3" json:"colors,omitempty"`
	// ── World / AOI ──
	AoiRadius         float64 `protobuf:"fixed64,12,opt,name=aoi_radius,json=aoiRadius,proto3" json:"aoi_radius,omitempty"`
	PortalHoldTimeMs  int32   `protobuf:"varint,13,opt,name=portal_hold_time_ms,json=portalHoldTimeMs,proto3" json:"portal_hold_time_ms,omitempty"`
	PortalSpawnRadius float64 `protobuf:"fixed64,14,opt,name=portal_spawn_radius,json=portalSpawnRadius,proto3" json:"portal_spawn_radius,omitempty"`
	// ── Entity base stats ──
	EntityBaseSpeed               float64 `protobuf:"fixed64,15,opt,name=entity_base_speed,json=entityBaseSpeed,proto3" json:"entity_base_speed,omitempty"`
	EntityBaseMaxLife             float64 `protobuf:"fixed64,16,opt,name=entity_base_max_life,json=entityBaseMaxLife,proto3" json:"entity_base_max_life,omitempty"`
	EntityBaseActionCooldownMs    int32   `protobuf:"varint,17,opt,name=entity_base_action_cooldown_ms,json=entityBaseActionCooldownMs,proto3" json:"entity_base_action_cooldown_ms,omitempty"`
	EntityBaseMinActionCooldownMs int32   `protobuf:"varint,18,opt,name=entity_base_min_action_cooldown_ms,json=entityBaseMinActionCooldownMs,proto3" json:"entity_base_min_action_cooldown_ms,omitempty"`
	// ── Bot defaults ──
	BotAggroRange float64 `protobuf:"fixed64,19,opt,name=bot_aggro_range,json=botAggroRange,proto3" json:"bot_aggro_range,omitempty"`
	// ── Player defaults ──
	DefaultPlayerWidth        float64                    `protobuf:"fixed64,20,opt,name=default_player_width,json=defaultPlayerWidth,proto3" json:"default_player_width,omitempty"`
	DefaultPlayerHeight       float64                    `protobuf:"fixed64,21,opt,name=default_player_height,json=defaultPlayerHeight,proto3" json:"default_player_height,omitempty"`
	PlayerBaseLifeRegenMin    float64                    `protobuf:"fixed64,22,opt,name=player_base_life_regen_min,json=playerBaseLifeRegenMin,proto3" json:"player_base_life_regen_min,omitempty"`
	PlayerBaseLifeRegenMax    float64                    `protobuf:"fixed64,23,opt,name=player_base_life_regen_max,json=playerBaseLifeRegenMax,proto3" json:"player_base_life_regen_max,omitempty"`
	SumStatsLimit             int32                      `protobuf:"varint,24,opt,name=sum_stats_limit,json=sumStatsLimit,proto3" json:"sum_stats_limit,omitempty"`
	MaxActiveLayers           int32                      `protobuf:"varint,25,opt,name=max_active_layers,json=maxActiveLayers,proto3" json:"max_active_layers,omitempty"`
	InitialLifeFraction       float64                    `protobuf:"fixed64,26,opt,name=initial_life_fraction,json=initialLifeFraction,proto3" json:"initial_life_fraction,omitempty"`
	DefaultPlayerObjectLayers []*DefaultObjectLayerState `protobuf:"bytes,27,rep,name=default_player_object_layers,json=defaultPlayerObjectLayers,proto3" json:"default_player_object_layers,omitempty"`
	// ── Combat / death ──
	RespawnDurationMs int32   `protobuf:"varint,28,opt,name=respawn_duration_ms,json=respawnDurationMs,proto3" json:"respawn_duration_ms,omitempty"`
	CollisionLifeLoss float64 `protobuf:"fixed64,30,opt,name=collision_life_loss,json=collisionLifeLoss,proto3" json:"collision_life_loss,omitempty"`
	// ── Economy ──
	DefaultCoinQuantity int32 `protobuf:"varint,32,opt,name=default_coin_quantity,json=defaultCoinQuantity,proto3" json:"default_coin_quantity,omitempty"`
	// ── Regen ──
	LifeRegenChance float64 `protobuf:"fixed64,33,opt,name=life_regen_chance,json=lifeRegenChance,proto3" json:"life_regen_chance,omitempty"`
	MaxChance       float64 `protobuf:"fixed64,34,opt,name=max_chance,json=maxChance,proto3" json:"max_chance,omitempty"`
	// ── Skill map (trigger → logic + items) ──
	SkillConfig []*SkillConfigEntry `protobuf:"bytes,45,rep,name=skill_config,json=skillConfig,proto3" json:"skill_config,omitempty"`
	// ── Skill tuning parameters ──
	SkillRules *SkillRules `protobuf:"bytes,47,opt,name=skill_rules,json=skillRules,proto3" json:"skill_rules,omitempty"`
	// ── Entity type rendering defaults ─────────────────────────────────────────
	// Structured per-entity-type configuration replacing the former flat item ID
	// fields.  Each entry defines the live OL, dead OL, and palette colour key
	// for one entity type ('player', 'bot', 'skill', 'coin', 'floor', …).
	// The Go server derives ghost/coin/floor item IDs from this repeated field.
	EntityDefaults []*EntityTypeDefault `protobuf:"bytes,52,rep,name=entity_defaults,json=entityDefaults,proto3" json:"entity_defaults,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceConfig) Reset() {
	*x = InstanceConfig{}
	mi := &file_proto_cyberia_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceConfig) ProtoMessage() {}

func (x *InstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceConfig.ProtoReflect.Descriptor instead.
func (*InstanceConfig) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{22}
}

func (x *InstanceConfig) GetCellSize() float64 {
	if x != nil {
		return x.CellSize
	}
	return 0
}

func (x *InstanceConfig) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *InstanceConfig) GetInterpolationMs() int32 {
	if x != nil {
		return x.InterpolationMs
	}
	return 0
}

func (x *InstanceConfig) GetDefaultObjWidth() float64 {
	if x != nil {
		return x.DefaultObjWidth
	}
	return 0
}

func (x *InstanceConfig) GetDefaultObjHeight() float64 {
	if x != nil {
		return x.DefaultObjHeight
	}
	return 0
}

func (x *InstanceConfig) GetCameraSmoothing() float64 {
	if x != nil {
		return x.CameraSmoothing
	}
	return 0
}

func (x *InstanceConfig) GetCameraZoom() float64 {
	if x != nil {
		return x.CameraZoom
	}
	return 0
}

func (x *InstanceConfig) GetDefaultWidthScreenFactor() float64 {
	if x != nil {
		return x.DefaultWidthScreenFactor
	}
	return 0
}

func (x *InstanceConfig) GetDefaultHeightScreenFactor() float64 {
	if x != nil {
		return x.DefaultHeightScreenFactor
	}
	return 0
}

func (x *InstanceConfig) GetDevUi() bool {
	if x != nil {
		return x.DevUi
	}
	return false
}

func (x *InstanceConfig) GetColors() []*ColorEntry {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *InstanceConfig) GetAoiRadius() float64 {
	if x != nil {
		return x.AoiRadius
	}
	return 0
}

func (x *InstanceConfig) GetPortalHoldTimeMs() int32 {
	if x != nil {
		return x.PortalHoldTimeMs
	}
	return 0
}

func (x *InstanceConfig) GetPortalSpawnRadius() float64 {
	if x != nil {
		return x.PortalSpawnRadius
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseSpeed() float64 {
	if x != nil {
		return x.EntityBaseSpeed
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseMaxLife() float64 {
	if x != nil {
		return x.EntityBaseMaxLife
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseActionCooldownMs() int32 {
	if x != nil {
		return x.EntityBaseActionCooldownMs
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseMinActionCooldownMs() int32 {
	if x != nil {
		return x.EntityBaseMinActionCooldownMs
	}
	return 0
}

func (x *InstanceConfig) GetBotAggroRange() float64 {
	if x != nil {
		return x.BotAggroRange
	}
	return 0
}

func (x *InstanceConfig) GetDefaultPlayerWidth() float64 {
	if x != nil {
		return x.DefaultPlayerWidth
	}
	return 0
}

func (x *InstanceConfig) GetDefaultPlayerHeight() float64 {
	if x != nil {
		return x.DefaultPlayerHeight
	}
	return 0
}

func (x *InstanceConfig) GetPlayerBaseLifeRegenMin() float64 {
	if x != nil {
		return x.PlayerBaseLifeRegenMin
	}
	return 0
}

func (x *InstanceConfig) GetPlayerBaseLifeRegenMax() float64 {
	if x != nil {
		return x.PlayerBaseLifeRegenMax
	}
	return 0
}

func (x *InstanceConfig) GetSumStatsLimit() int32 {
	if x != nil {
		return x.SumStatsLimit
	}
	return 0
}

func (x *InstanceConfig) GetMaxActiveLayers() int32 {
	if x != nil {
		return x.MaxActiveLayers
	}
	return 0
}

func (x *InstanceConfig) GetInitialLifeFraction() float64 {
	if x != nil {
		return x.InitialLifeFraction
	}
	return 0
}

func (x *InstanceConfig) GetDefaultPlayerObjectLayers() []*DefaultObjectLayerState {
	if x != nil {
		return x.DefaultPlayerObjectLayers
	}
	return nil
}

func (x *InstanceConfig) GetRespawnDurationMs() int32 {
	if x != nil {
		return x.RespawnDurationMs
	}
	return 0
}

func (x *InstanceConfig) GetCollisionLifeLoss() float64 {
	if x != nil {
		return x.CollisionLifeLoss
	}
	return 0
}

func (x *InstanceConfig) GetDefaultCoinQuantity() int32 {
	if x != nil {
		return x.DefaultCoinQuantity
	}
	return 0
}

func (x *InstanceConfig) GetLifeRegenChance() float64 {
	if x != nil {
		return x.LifeRegenChance
	}
	return 0
}

func (x *InstanceConfig) GetMaxChance() float64 {
	if x != nil {
		return x.MaxChance
	}
	return 0
}

func (x *InstanceConfig) GetSkillConfig() []*SkillConfigEntry {
	if x != nil {
		return x.SkillConfig
	}
	return nil
}

func (x *InstanceConfig) GetSkillRules() *SkillRules {
	if x != nil {
		return x.SkillRules
	}
	return nil
}

func (x *InstanceConfig) GetEntityDefaults() []*EntityTypeDefault {
	if x != nil {
		return x.EntityDefaults
	}
	return nil
}

// ── Entity type defaults (per-entity visual + color configuration) ──────────
// Replaces the former flat string fields: ghost_item_id (29), coin_item_id (31),
// default_floor_item_id (44), bot_default_item_id (48), user_default_item_id (49).
type EntityTypeDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`      // matches entity_type_str / bot Behavior in game engine
	LiveItemIds   []string               `protobuf:"bytes,2,rep,name=live_item_ids,json=liveItemIds,proto3" json:"live_item_ids,omitempty"` // OL item IDs for the alive/active state
	DeadItemIds   []string               `protobuf:"bytes,3,rep,name=dead_item_ids,json=deadItemIds,proto3" json:"dead_item_ids,omitempty"` // OL item IDs for the dead/ghost/respawning state
	ColorKey      string                 `protobuf:"bytes,4,opt,name=color_key,json=colorKey,proto3" json:"color_key,omitempty"`            // palette key for solid-color fallback (no OL items)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityTypeDefault) Reset() {
	*x = EntityTypeDefault{}
	mi := &file_proto_cyberia_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityTypeDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityTypeDefault) ProtoMessage() {}

func (x *EntityTypeDefault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityTypeDefault.ProtoReflect.Descriptor instead.
func (*EntityTypeDefault) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{23}
}

func (x *EntityTypeDefault) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityTypeDefault) GetLiveItemIds() []string {
	if x != nil {
		return x.LiveItemIds
	}
	return nil
}

func (x *EntityTypeDefault) GetDeadItemIds() []string {
	if x != nil {
		return x.DeadItemIds
	}
	return nil
}

func (x *EntityTypeDefault) GetColorKey() string {
	if x != nil {
		return x.ColorKey
	}
	return ""
}

type EntityMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityType         string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	InitCellX          int32                  `protobuf:"varint,2,opt,name=init_cell_x,json=initCellX,proto3" json:"init_cell_x,omitempty"`
	InitCellY          int32                  `protobuf:"varint,3,opt,name=init_cell_y,json=initCellY,proto3" json:"init_cell_y,omitempty"`
	DimX               int32                  `protobuf:"varint,4,opt,name=dim_x,json=dimX,proto3" json:"dim_x,omitempty"`
	DimY               int32                  `protobuf:"varint,5,opt,name=dim_y,json=dimY,proto3" json:"dim_y,omitempty"`
	Color              string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	ObjectLayerItemIds []string               `protobuf:"bytes,7,rep,name=object_layer_item_ids,json=objectLayerItemIds,proto3" json:"object_layer_item_ids,omitempty"`
	// Bot-specific fields
	SpawnRadius float64 `protobuf:"fixed64,8,opt,name=spawn_radius,json=spawnRadius,proto3" json:"spawn_radius,omitempty"` // wandering radius (0 = use server default)
	AggroRange  float64 `protobuf:"fixed64,9,opt,name=aggro_range,json=aggroRange,proto3" json:"aggro_range,omitempty"`    // aggro detection range (0 = use server default)
	MaxLife     float64 `protobuf:"fixed64,10,opt,name=max_life,json=maxLife,proto3" json:"max_life,omitempty"`            // base max life (0 = use server default)
	LifeRegen   float64 `protobuf:"fixed64,11,opt,name=life_regen,json=lifeRegen,proto3" json:"life_regen,omitempty"`      // life regen rate (0 = use server default)
	// Portal-specific field
	PortalSubtype string `protobuf:"bytes,12,opt,name=portal_subtype,json=portalSubtype,proto3" json:"portal_subtype,omitempty"` // inter-portal | inter-random | intra-random | intra-portal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMessage) Reset() {
	*x = EntityMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMessage) ProtoMessage() {}

func (x *EntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMessage.ProtoReflect.Descriptor instead.
func (*EntityMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{24}
}

func (x *EntityMessage) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityMessage) GetInitCellX() int32 {
	if x != nil {
		return x.InitCellX
	}
	return 0
}

func (x *EntityMessage) GetInitCellY() int32 {
	if x != nil {
		return x.InitCellY
	}
	return 0
}

func (x *EntityMessage) GetDimX() int32 {
	if x != nil {
		return x.DimX
	}
	return 0
}

func (x *EntityMessage) GetDimY() int32 {
	if x != nil {
		return x.DimY
	}
	return 0
}

func (x *EntityMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EntityMessage) GetObjectLayerItemIds() []string {
	if x != nil {
		return x.ObjectLayerItemIds
	}
	return nil
}

func (x *EntityMessage) GetSpawnRadius() float64 {
	if x != nil {
		return x.SpawnRadius
	}
	return 0
}

func (x *EntityMessage) GetAggroRange() float64 {
	if x != nil {
		return x.AggroRange
	}
	return 0
}

func (x *EntityMessage) GetMaxLife() float64 {
	if x != nil {
		return x.MaxLife
	}
	return 0
}

func (x *EntityMessage) GetLifeRegen() float64 {
	if x != nil {
		return x.LifeRegen
	}
	return 0
}

func (x *EntityMessage) GetPortalSubtype() string {
	if x != nil {
		return x.PortalSubtype
	}
	return ""
}

type MapDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GridX         int32                  `protobuf:"varint,4,opt,name=grid_x,json=gridX,proto3" json:"grid_x,omitempty"`
	GridY         int32                  `protobuf:"varint,5,opt,name=grid_y,json=gridY,proto3" json:"grid_y,omitempty"`
	CellWidth     int32                  `protobuf:"varint,6,opt,name=cell_width,json=cellWidth,proto3" json:"cell_width,omitempty"`
	CellHeight    int32                  `protobuf:"varint,7,opt,name=cell_height,json=cellHeight,proto3" json:"cell_height,omitempty"`
	Entities      []*EntityMessage       `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDataMessage) Reset() {
	*x = MapDataMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDataMessage) ProtoMessage() {}

func (x *MapDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDataMessage.ProtoReflect.Descriptor instead.
func (*MapDataMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{25}
}

func (x *MapDataMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *MapDataMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MapDataMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapDataMessage) GetGridX() int32 {
	if x != nil {
		return x.GridX
	}
	return 0
}

func (x *MapDataMessage) GetGridY() int32 {
	if x != nil {
		return x.GridY
	}
	return 0
}

func (x *MapDataMessage) GetCellWidth() int32 {
	if x != nil {
		return x.CellWidth
	}
	return 0
}

func (x *MapDataMessage) GetCellHeight() int32 {
	if x != nil {
		return x.CellHeight
	}
	return 0
}

func (x *MapDataMessage) GetEntities() []*EntityMessage {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetMapDataRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MapCode string                 `protobuf:"bytes,1,opt,name=map_code,json=mapCode,proto3" json:"map_code,omitempty"`
	// Code of the Go instance making the request — used by the Engine
	// to update the cyberia-global-map-code-registry live tracking table.
	InstanceCode  string `protobuf:"bytes,2,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataRequest) Reset() {
	*x = GetMapDataRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataRequest) ProtoMessage() {}

func (x *GetMapDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataRequest.ProtoReflect.Descriptor instead.
func (*GetMapDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{26}
}

func (x *GetMapDataRequest) GetMapCode() string {
	if x != nil {
		return x.MapCode
	}
	return ""
}

func (x *GetMapDataRequest) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

type GetMapDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapDataMessage        `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataResponse) Reset() {
	*x = GetMapDataResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataResponse) ProtoMessage() {}

func (x *GetMapDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataResponse.ProtoReflect.Descriptor instead.
func (*GetMapDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{27}
}

func (x *GetMapDataResponse) GetMap() *MapDataMessage {
	if x != nil {
		return x.Map
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{28}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeMs  int64                  `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{29}
}

func (x *PingResponse) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type ObjectLayerManifestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerManifestEntry) Reset() {
	*x = ObjectLayerManifestEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerManifestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerManifestEntry) ProtoMessage() {}

func (x *ObjectLayerManifestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerManifestEntry.ProtoReflect.Descriptor instead.
func (*ObjectLayerManifestEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{30}
}

func (x *ObjectLayerManifestEntry) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ObjectLayerManifestEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetObjectLayerManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestRequest) Reset() {
	*x = GetObjectLayerManifestRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestRequest) ProtoMessage() {}

func (x *GetObjectLayerManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{31}
}

type GetObjectLayerManifestResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*ObjectLayerManifestEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestResponse) Reset() {
	*x = GetObjectLayerManifestResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestResponse) ProtoMessage() {}

func (x *GetObjectLayerManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestResponse.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{32}
}

func (x *GetObjectLayerManifestResponse) GetEntries() []*ObjectLayerManifestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_cyberia_proto protoreflect.FileDescriptor

const file_proto_cyberia_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cyberia.proto\x12\acyberia\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"#\n" +
	"\x05Vec2I\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xad\x01\n" +
	"\x05Stats\x12\x16\n" +
	"\x06effect\x18\x01 \x01(\x05R\x06effect\x12\x1e\n" +
	"\n" +
	"resistance\x18\x02 \x01(\x05R\n" +
	"resistance\x12\x18\n" +
	"\aagility\x18\x03 \x01(\x05R\aagility\x12\x14\n" +
	"\x05range\x18\x04 \x01(\x05R\x05range\x12\"\n" +
	"\fintelligence\x18\x05 \x01(\x05R\fintelligence\x12\x18\n" +
	"\autility\x18\x06 \x01(\x05R\autility\"n\n" +
	"\bItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tactivable\x18\x04 \x01(\bR\tactivable\"Q\n" +
	"\x06Ledger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"=\n" +
	"\x06Render\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12!\n" +
	"\fmetadata_cid\x18\x02 \x01(\tR\vmetadataCid\"\xc2\x02\n" +
	"\x12ObjectLayerMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12$\n" +
	"\x05stats\x18\x02 \x01(\v2\x0e.cyberia.StatsR\x05stats\x12%\n" +
	"\x04item\x18\x03 \x01(\v2\x11.cyberia.ItemInfoR\x04item\x12'\n" +
	"\x06ledger\x18\x04 \x01(\v2\x0f.cyberia.LedgerR\x06ledger\x12'\n" +
	"\x06render\x18\x05 \x01(\v2\x0f.cyberia.RenderR\x06render\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03cid\x18\a \x01(\tR\x03cid\x12%\n" +
	"\x0eframe_duration\x18\b \x01(\x05R\rframeDuration\x12!\n" +
	"\fis_stateless\x18\t \x01(\bR\visStateless\"F\n" +
	"\x1aGetObjectLayerBatchRequest\x12(\n" +
	"\x10item_type_filter\x18\x01 \x01(\tR\x0eitemTypeFilter\"0\n" +
	"\x15GetObjectLayerRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"z\n" +
	"\rFrameMetadata\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1f\n" +
	"\vframe_index\x18\x05 \x01(\x05R\n" +
	"frameIndex\"\xbd\b\n" +
	"\x0fDirectionFrames\x12/\n" +
	"\aup_idle\x18\x01 \x03(\v2\x16.cyberia.FrameMetadataR\x06upIdle\x123\n" +
	"\tdown_idle\x18\x02 \x03(\v2\x16.cyberia.FrameMetadataR\bdownIdle\x125\n" +
	"\n" +
	"right_idle\x18\x03 \x03(\v2\x16.cyberia.FrameMetadataR\trightIdle\x123\n" +
	"\tleft_idle\x18\x04 \x03(\v2\x16.cyberia.FrameMetadataR\bleftIdle\x12:\n" +
	"\rup_right_idle\x18\x05 \x03(\v2\x16.cyberia.FrameMetadataR\vupRightIdle\x12>\n" +
	"\x0fdown_right_idle\x18\x06 \x03(\v2\x16.cyberia.FrameMetadataR\rdownRightIdle\x128\n" +
	"\fup_left_idle\x18\a \x03(\v2\x16.cyberia.FrameMetadataR\n" +
	"upLeftIdle\x12<\n" +
	"\x0edown_left_idle\x18\b \x03(\v2\x16.cyberia.FrameMetadataR\fdownLeftIdle\x129\n" +
	"\fdefault_idle\x18\t \x03(\v2\x16.cyberia.FrameMetadataR\vdefaultIdle\x125\n" +
	"\n" +
	"up_walking\x18\n" +
	" \x03(\v2\x16.cyberia.FrameMetadataR\tupWalking\x129\n" +
	"\fdown_walking\x18\v \x03(\v2\x16.cyberia.FrameMetadataR\vdownWalking\x12;\n" +
	"\rright_walking\x18\f \x03(\v2\x16.cyberia.FrameMetadataR\frightWalking\x129\n" +
	"\fleft_walking\x18\r \x03(\v2\x16.cyberia.FrameMetadataR\vleftWalking\x12@\n" +
	"\x10up_right_walking\x18\x0e \x03(\v2\x16.cyberia.FrameMetadataR\x0eupRightWalking\x12D\n" +
	"\x12down_right_walking\x18\x0f \x03(\v2\x16.cyberia.FrameMetadataR\x10downRightWalking\x12>\n" +
	"\x0fup_left_walking\x18\x10 \x03(\v2\x16.cyberia.FrameMetadataR\rupLeftWalking\x12B\n" +
	"\x11down_left_walking\x18\x11 \x03(\v2\x16.cyberia.FrameMetadataR\x0fdownLeftWalking\x123\n" +
	"\tnone_idle\x18\x12 \x03(\v2\x16.cyberia.FrameMetadataR\bnoneIdle\"\x96\x02\n" +
	"\x17AtlasSpriteSheetMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid\x12\x19\n" +
	"\bitem_key\x18\x04 \x01(\tR\aitemKey\x12\x1f\n" +
	"\vatlas_width\x18\x05 \x01(\x05R\n" +
	"atlasWidth\x12!\n" +
	"\fatlas_height\x18\x06 \x01(\x05R\vatlasHeight\x12$\n" +
	"\x0ecell_pixel_dim\x18\a \x01(\x05R\fcellPixelDim\x120\n" +
	"\x06frames\x18\b \x01(\v2\x18.cyberia.DirectionFramesR\x06frames\"7\n" +
	"\x1aGetAtlasSpriteSheetRequest\x12\x19\n" +
	"\bitem_key\x18\x01 \x01(\tR\aitemKey\"!\n" +
	"\x1fGetAtlasSpriteSheetBatchRequest\"\x8d\x02\n" +
	"\n" +
	"PortalEdge\x12&\n" +
	"\x0fsource_map_code\x18\x01 \x01(\tR\rsourceMapCode\x12\"\n" +
	"\rsource_cell_x\x18\x02 \x01(\x05R\vsourceCellX\x12\"\n" +
	"\rsource_cell_y\x18\x03 \x01(\x05R\vsourceCellY\x12&\n" +
	"\x0ftarget_map_code\x18\x04 \x01(\tR\rtargetMapCode\x12\"\n" +
	"\rtarget_cell_x\x18\x05 \x01(\x05R\vtargetCellX\x12\"\n" +
	"\rtarget_cell_y\x18\x06 \x01(\x05R\vtargetCellY\x12\x1f\n" +
	"\vportal_mode\x18\a \x01(\tR\n" +
	"portalMode\"\x8f\x02\n" +
	"\x0fInstanceMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tmap_codes\x18\x06 \x03(\tR\bmapCodes\x12-\n" +
	"\aportals\x18\a \x03(\v2\x13.cyberia.PortalEdgeR\aportals\x12#\n" +
	"\rtopology_mode\x18\b \x01(\tR\ftopologyMode\x12\x12\n" +
	"\x04seed\x18\t \x01(\tR\x04seed\"=\n" +
	"\x16GetFullInstanceRequest\x12#\n" +
	"\rinstance_code\x18\x01 \x01(\tR\finstanceCode\"\xef\x01\n" +
	"\x17GetFullInstanceResponse\x124\n" +
	"\binstance\x18\x01 \x01(\v2\x18.cyberia.InstanceMessageR\binstance\x12+\n" +
	"\x04maps\x18\x02 \x03(\v2\x17.cyberia.MapDataMessageR\x04maps\x12@\n" +
	"\robject_layers\x18\x03 \x03(\v2\x1b.cyberia.ObjectLayerMessageR\fobjectLayers\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.cyberia.InstanceConfigR\x06config\"V\n" +
	"\n" +
	"ColorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\f\n" +
	"\x01r\x18\x02 \x01(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x03 \x01(\x05R\x01g\x12\f\n" +
	"\x01b\x18\x04 \x01(\x05R\x01b\x12\f\n" +
	"\x01a\x18\x05 \x01(\x05R\x01a\"f\n" +
	"\x17DefaultObjectLayerState\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x90\x01\n" +
	"\x10SkillConfigEntry\x12&\n" +
	"\x0ftrigger_item_id\x18\x01 \x01(\tR\rtriggerItemId\x12&\n" +
	"\x0flogic_event_ids\x18\x04 \x03(\tR\rlogicEventIdsJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x10spawned_item_idsR\x0elogic_event_id\"\x91\x04\n" +
	"\n" +
	"SkillRules\x126\n" +
	"\x17projectile_spawn_chance\x18\x01 \x01(\x01R\x15projectileSpawnChance\x124\n" +
	"\x16projectile_lifetime_ms\x18\x02 \x01(\x05R\x14projectileLifetimeMs\x12)\n" +
	"\x10projectile_width\x18\x03 \x01(\x01R\x0fprojectileWidth\x12+\n" +
	"\x11projectile_height\x18\x04 \x01(\x01R\x10projectileHeight\x12>\n" +
	"\x1bprojectile_speed_multiplier\x18\x05 \x01(\x01R\x19projectileSpeedMultiplier\x12:\n" +
	"\x19doppelganger_spawn_chance\x18\x06 \x01(\x01R\x17doppelgangerSpawnChance\x128\n" +
	"\x18doppelganger_lifetime_ms\x18\a \x01(\x05R\x16doppelgangerLifetimeMs\x12:\n" +
	"\x19doppelganger_spawn_radius\x18\b \x01(\x01R\x17doppelgangerSpawnRadius\x12K\n" +
	"\"doppelganger_initial_life_fraction\x18\t \x01(\x01R\x1fdoppelgangerInitialLifeFraction\"\xa5\x11\n" +
	"\x0eInstanceConfig\x12\x1b\n" +
	"\tcell_size\x18\x01 \x01(\x01R\bcellSize\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x05R\x03fps\x12)\n" +
	"\x10interpolation_ms\x18\x03 \x01(\x05R\x0finterpolationMs\x12*\n" +
	"\x11default_obj_width\x18\x04 \x01(\x01R\x0fdefaultObjWidth\x12,\n" +
	"\x12default_obj_height\x18\x05 \x01(\x01R\x10defaultObjHeight\x12)\n" +
	"\x10camera_smoothing\x18\x06 \x01(\x01R\x0fcameraSmoothing\x12\x1f\n" +
	"\vcamera_zoom\x18\a \x01(\x01R\n" +
	"cameraZoom\x12=\n" +
	"\x1bdefault_width_screen_factor\x18\b \x01(\x01R\x18defaultWidthScreenFactor\x12?\n" +
	"\x1cdefault_height_screen_factor\x18\t \x01(\x01R\x19defaultHeightScreenFactor\x12\x15\n" +
	"\x06dev_ui\x18\n" +
	" \x01(\bR\x05devUi\x12+\n" +
	"\x06colors\x18\v \x03(\v2\x13.cyberia.ColorEntryR\x06colors\x12\x1d\n" +
	"\n" +
	"aoi_radius\x18\f \x01(\x01R\taoiRadius\x12-\n" +
	"\x13portal_hold_time_ms\x18\r \x01(\x05R\x10portalHoldTimeMs\x12.\n" +
	"\x13portal_spawn_radius\x18\x0e \x01(\x01R\x11portalSpawnRadius\x12*\n" +
	"\x11entity_base_speed\x18\x0f \x01(\x01R\x0fentityBaseSpeed\x12/\n" +
	"\x14entity_base_max_life\x18\x10 \x01(\x01R\x11entityBaseMaxLife\x12B\n" +
	"\x1eentity_base_action_cooldown_ms\x18\x11 \x01(\x05R\x1aentityBaseActionCooldownMs\x12I\n" +
	"\"entity_base_min_action_cooldown_ms\x18\x12 \x01(\x05R\x1dentityBaseMinActionCooldownMs\x12&\n" +
	"\x0fbot_aggro_range\x18\x13 \x01(\x01R\rbotAggroRange\x120\n" +
	"\x14default_player_width\x18\x14 \x01(\x01R\x12defaultPlayerWidth\x122\n" +
	"\x15default_player_height\x18\x15 \x01(\x01R\x13defaultPlayerHeight\x12:\n" +
	"\x1aplayer_base_life_regen_min\x18\x16 \x01(\x01R\x16playerBaseLifeRegenMin\x12:\n" +
	"\x1aplayer_base_life_regen_max\x18\x17 \x01(\x01R\x16playerBaseLifeRegenMax\x12&\n" +
	"\x0fsum_stats_limit\x18\x18 \x01(\x05R\rsumStatsLimit\x12*\n" +
	"\x11max_active_layers\x18\x19 \x01(\x05R\x0fmaxActiveLayers\x122\n" +
	"\x15initial_life_fraction\x18\x1a \x01(\x01R\x13initialLifeFraction\x12a\n" +
	"\x1cdefault_player_object_layers\x18\x1b \x03(\v2 .cyberia.DefaultObjectLayerStateR\x19defaultPlayerObjectLayers\x12.\n" +
	"\x13respawn_duration_ms\x18\x1c \x01(\x05R\x11respawnDurationMs\x12.\n" +
	"\x13collision_life_loss\x18\x1e \x01(\x01R\x11collisionLifeLoss\x122\n" +
	"\x15default_coin_quantity\x18  \x01(\x05R\x13defaultCoinQuantity\x12*\n" +
	"\x11life_regen_chance\x18! \x01(\x01R\x0flifeRegenChance\x12\x1d\n" +
	"\n" +
	"max_chance\x18\" \x01(\x01R\tmaxChance\x12<\n" +
	"\fskill_config\x18- \x03(\v2\x19.cyberia.SkillConfigEntryR\vskillConfig\x124\n" +
	"\vskill_rules\x18/ \x01(\v2\x13.cyberia.SkillRulesR\n" +
	"skillRules\x12C\n" +
	"\x0fentity_defaults\x184 \x03(\v2\x1a.cyberia.EntityTypeDefaultR\x0eentityDefaultsJ\x04\b#\x10$J\x04\b$\x10%J\x04\b%\x10&J\x04\b&\x10'J\x04\b'\x10(J\x04\b(\x10)J\x04\b)\x10*J\x04\b*\x10+J\x04\b+\x10,J\x04\b.\x10/J\x04\b\x1d\x10\x1eJ\x04\b\x1f\x10 J\x04\b,\x10-J\x04\b0\x101J\x04\b1\x102J\x04\b2\x103J\x04\b3\x104R\x13bullet_spawn_chanceR\x12bullet_lifetime_msR\fbullet_widthR\rbullet_heightR\x17bullet_speed_multiplierR\x19doppelganger_spawn_chanceR\x18doppelganger_lifetime_msR\x19doppelganger_spawn_radiusR\"doppelganger_initial_life_fractionR\x14default_player_colorR\rghost_item_idR\fcoin_item_idR\x15default_floor_item_idR\x13bot_default_item_idR\x14user_default_item_idR\x16weapon_default_item_idR\x16bullet_default_item_id\"\x99\x01\n" +
	"\x11EntityTypeDefault\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\"\n" +
	"\rlive_item_ids\x18\x02 \x03(\tR\vliveItemIds\x12\"\n" +
	"\rdead_item_ids\x18\x03 \x03(\tR\vdeadItemIds\x12\x1b\n" +
	"\tcolor_key\x18\x04 \x01(\tR\bcolorKey\"\x88\x03\n" +
	"\rEntityMessage\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1e\n" +
	"\vinit_cell_x\x18\x02 \x01(\x05R\tinitCellX\x12\x1e\n" +
	"\vinit_cell_y\x18\x03 \x01(\x05R\tinitCellY\x12\x13\n" +
	"\x05dim_x\x18\x04 \x01(\x05R\x04dimX\x12\x13\n" +
	"\x05dim_y\x18\x05 \x01(\x05R\x04dimY\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x121\n" +
	"\x15object_layer_item_ids\x18\a \x03(\tR\x12objectLayerItemIds\x12!\n" +
	"\fspawn_radius\x18\b \x01(\x01R\vspawnRadius\x12\x1f\n" +
	"\vaggro_range\x18\t \x01(\x01R\n" +
	"aggroRange\x12\x19\n" +
	"\bmax_life\x18\n" +
	" \x01(\x01R\amaxLife\x12\x1d\n" +
	"\n" +
	"life_regen\x18\v \x01(\x01R\tlifeRegen\x12%\n" +
	"\x0eportal_subtype\x18\f \x01(\tR\rportalSubtype\"\xf5\x01\n" +
	"\x0eMapDataMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06grid_x\x18\x04 \x01(\x05R\x05gridX\x12\x15\n" +
	"\x06grid_y\x18\x05 \x01(\x05R\x05gridY\x12\x1d\n" +
	"\n" +
	"cell_width\x18\x06 \x01(\x05R\tcellWidth\x12\x1f\n" +
	"\vcell_height\x18\a \x01(\x05R\n" +
	"cellHeight\x122\n" +
	"\bentities\x18\b \x03(\v2\x16.cyberia.EntityMessageR\bentities\"S\n" +
	"\x11GetMapDataRequest\x12\x19\n" +
	"\bmap_code\x18\x01 \x01(\tR\amapCode\x12#\n" +
	"\rinstance_code\x18\x02 \x01(\tR\finstanceCode\"?\n" +
	"\x12GetMapDataResponse\x12)\n" +
	"\x03map\x18\x01 \x01(\v2\x17.cyberia.MapDataMessageR\x03map\"\r\n" +
	"\vPingRequest\"4\n" +
	"\fPingResponse\x12$\n" +
	"\x0eserver_time_ms\x18\x01 \x01(\x03R\fserverTimeMs\"K\n" +
	"\x18ObjectLayerManifestEntry\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x1f\n" +
	"\x1dGetObjectLayerManifestRequest\"]\n" +
	"\x1eGetObjectLayerManifestResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.cyberia.ObjectLayerManifestEntryR\aentries2\xc3\x05\n" +
	"\x12CyberiaDataService\x12T\n" +
	"\x0fGetFullInstance\x12\x1f.cyberia.GetFullInstanceRequest\x1a .cyberia.GetFullInstanceResponse\x12E\n" +
	"\n" +
	"GetMapData\x12\x1a.cyberia.GetMapDataRequest\x1a\x1b.cyberia.GetMapDataResponse\x12Y\n" +
	"\x13GetObjectLayerBatch\x12#.cyberia.GetObjectLayerBatchRequest\x1a\x1b.cyberia.ObjectLayerMessage0\x01\x12M\n" +
	"\x0eGetObjectLayer\x12\x1e.cyberia.GetObjectLayerRequest\x1a\x1b.cyberia.ObjectLayerMessage\x12\\\n" +
	"\x13GetAtlasSpriteSheet\x12#.cyberia.GetAtlasSpriteSheetRequest\x1a .cyberia.AtlasSpriteSheetMessage\x12h\n" +
	"\x18GetAtlasSpriteSheetBatch\x12(.cyberia.GetAtlasSpriteSheetBatchRequest\x1a .cyberia.AtlasSpriteSheetMessage0\x01\x123\n" +
	"\x04Ping\x12\x14.cyberia.PingRequest\x1a\x15.cyberia.PingResponse\x12i\n" +
	"\x16GetObjectLayerManifest\x12&.cyberia.GetObjectLayerManifestRequest\x1a'.cyberia.GetObjectLayerManifestResponseB\x16Z\x14cyberia-server/protob\x06proto3"

var (
	file_proto_cyberia_proto_rawDescOnce sync.Once
	file_proto_cyberia_proto_rawDescData []byte
)

func file_proto_cyberia_proto_rawDescGZIP() []byte {
	file_proto_cyberia_proto_rawDescOnce.Do(func() {
		file_proto_cyberia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)))
	})
	return file_proto_cyberia_proto_rawDescData
}

var file_proto_cyberia_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_cyberia_proto_goTypes = []any{
	(*Vec2)(nil),                            // 0: cyberia.Vec2
	(*Vec2I)(nil),                           // 1: cyberia.Vec2I
	(*Stats)(nil),                           // 2: cyberia.Stats
	(*ItemInfo)(nil),                        // 3: cyberia.ItemInfo
	(*Ledger)(nil),                          // 4: cyberia.Ledger
	(*Render)(nil),                          // 5: cyberia.Render
	(*ObjectLayerMessage)(nil),              // 6: cyberia.ObjectLayerMessage
	(*GetObjectLayerBatchRequest)(nil),      // 7: cyberia.GetObjectLayerBatchRequest
	(*GetObjectLayerRequest)(nil),           // 8: cyberia.GetObjectLayerRequest
	(*FrameMetadata)(nil),                   // 9: cyberia.FrameMetadata
	(*DirectionFrames)(nil),                 // 10: cyberia.DirectionFrames
	(*AtlasSpriteSheetMessage)(nil),         // 11: cyberia.AtlasSpriteSheetMessage
	(*GetAtlasSpriteSheetRequest)(nil),      // 12: cyberia.GetAtlasSpriteSheetRequest
	(*GetAtlasSpriteSheetBatchRequest)(nil), // 13: cyberia.GetAtlasSpriteSheetBatchRequest
	(*PortalEdge)(nil),                      // 14: cyberia.PortalEdge
	(*InstanceMessage)(nil),                 // 15: cyberia.InstanceMessage
	(*GetFullInstanceRequest)(nil),          // 16: cyberia.GetFullInstanceRequest
	(*GetFullInstanceResponse)(nil),         // 17: cyberia.GetFullInstanceResponse
	(*ColorEntry)(nil),                      // 18: cyberia.ColorEntry
	(*DefaultObjectLayerState)(nil),         // 19: cyberia.DefaultObjectLayerState
	(*SkillConfigEntry)(nil),                // 20: cyberia.SkillConfigEntry
	(*SkillRules)(nil),                      // 21: cyberia.SkillRules
	(*InstanceConfig)(nil),                  // 22: cyberia.InstanceConfig
	(*EntityTypeDefault)(nil),               // 23: cyberia.EntityTypeDefault
	(*EntityMessage)(nil),                   // 24: cyberia.EntityMessage
	(*MapDataMessage)(nil),                  // 25: cyberia.MapDataMessage
	(*GetMapDataRequest)(nil),               // 26: cyberia.GetMapDataRequest
	(*GetMapDataResponse)(nil),              // 27: cyberia.GetMapDataResponse
	(*PingRequest)(nil),                     // 28: cyberia.PingRequest
	(*PingResponse)(nil),                    // 29: cyberia.PingResponse
	(*ObjectLayerManifestEntry)(nil),        // 30: cyberia.ObjectLayerManifestEntry
	(*GetObjectLayerManifestRequest)(nil),   // 31: cyberia.GetObjectLayerManifestRequest
	(*GetObjectLayerManifestResponse)(nil),  // 32: cyberia.GetObjectLayerManifestResponse
}
var file_proto_cyberia_proto_depIdxs = []int32{
	2,  // 0: cyberia.ObjectLayerMessage.stats:type_name -> cyberia.Stats
	3,  // 1: cyberia.ObjectLayerMessage.item:type_name -> cyberia.ItemInfo
	4,  // 2: cyberia.ObjectLayerMessage.ledger:type_name -> cyberia.Ledger
	5,  // 3: cyberia.ObjectLayerMessage.render:type_name -> cyberia.Render
	9,  // 4: cyberia.DirectionFrames.up_idle:type_name -> cyberia.FrameMetadata
	9,  // 5: cyberia.DirectionFrames.down_idle:type_name -> cyberia.FrameMetadata
	9,  // 6: cyberia.DirectionFrames.right_idle:type_name -> cyberia.FrameMetadata
	9,  // 7: cyberia.DirectionFrames.left_idle:type_name -> cyberia.FrameMetadata
	9,  // 8: cyberia.DirectionFrames.up_right_idle:type_name -> cyberia.FrameMetadata
	9,  // 9: cyberia.DirectionFrames.down_right_idle:type_name -> cyberia.FrameMetadata
	9,  // 10: cyberia.DirectionFrames.up_left_idle:type_name -> cyberia.FrameMetadata
	9,  // 11: cyberia.DirectionFrames.down_left_idle:type_name -> cyberia.FrameMetadata
	9,  // 12: cyberia.DirectionFrames.default_idle:type_name -> cyberia.FrameMetadata
	9,  // 13: cyberia.DirectionFrames.up_walking:type_name -> cyberia.FrameMetadata
	9,  // 14: cyberia.DirectionFrames.down_walking:type_name -> cyberia.FrameMetadata
	9,  // 15: cyberia.DirectionFrames.right_walking:type_name -> cyberia.FrameMetadata
	9,  // 16: cyberia.DirectionFrames.left_walking:type_name -> cyberia.FrameMetadata
	9,  // 17: cyberia.DirectionFrames.up_right_walking:type_name -> cyberia.FrameMetadata
	9,  // 18: cyberia.DirectionFrames.down_right_walking:type_name -> cyberia.FrameMetadata
	9,  // 19: cyberia.DirectionFrames.up_left_walking:type_name -> cyberia.FrameMetadata
	9,  // 20: cyberia.DirectionFrames.down_left_walking:type_name -> cyberia.FrameMetadata
	9,  // 21: cyberia.DirectionFrames.none_idle:type_name -> cyberia.FrameMetadata
	10, // 22: cyberia.AtlasSpriteSheetMessage.frames:type_name -> cyberia.DirectionFrames
	14, // 23: cyberia.InstanceMessage.portals:type_name -> cyberia.PortalEdge
	15, // 24: cyberia.GetFullInstanceResponse.instance:type_name -> cyberia.InstanceMessage
	25, // 25: cyberia.GetFullInstanceResponse.maps:type_name -> cyberia.MapDataMessage
	6,  // 26: cyberia.GetFullInstanceResponse.object_layers:type_name -> cyberia.ObjectLayerMessage
	22, // 27: cyberia.GetFullInstanceResponse.config:type_name -> cyberia.InstanceConfig
	18, // 28: cyberia.InstanceConfig.colors:type_name -> cyberia.ColorEntry
	19, // 29: cyberia.InstanceConfig.default_player_object_layers:type_name -> cyberia.DefaultObjectLayerState
	20, // 30: cyberia.InstanceConfig.skill_config:type_name -> cyberia.SkillConfigEntry
	21, // 31: cyberia.InstanceConfig.skill_rules:type_name -> cyberia.SkillRules
	23, // 32: cyberia.InstanceConfig.entity_defaults:type_name -> cyberia.EntityTypeDefault
	24, // 33: cyberia.MapDataMessage.entities:type_name -> cyberia.EntityMessage
	25, // 34: cyberia.GetMapDataResponse.map:type_name -> cyberia.MapDataMessage
	30, // 35: cyberia.GetObjectLayerManifestResponse.entries:type_name -> cyberia.ObjectLayerManifestEntry
	16, // 36: cyberia.CyberiaDataService.GetFullInstance:input_type -> cyberia.GetFullInstanceRequest
	26, // 37: cyberia.CyberiaDataService.GetMapData:input_type -> cyberia.GetMapDataRequest
	7,  // 38: cyberia.CyberiaDataService.GetObjectLayerBatch:input_type -> cyberia.GetObjectLayerBatchRequest
	8,  // 39: cyberia.CyberiaDataService.GetObjectLayer:input_type -> cyberia.GetObjectLayerRequest
	12, // 40: cyberia.CyberiaDataService.GetAtlasSpriteSheet:input_type -> cyberia.GetAtlasSpriteSheetRequest
	13, // 41: cyberia.CyberiaDataService.GetAtlasSpriteSheetBatch:input_type -> cyberia.GetAtlasSpriteSheetBatchRequest
	28, // 42: cyberia.CyberiaDataService.Ping:input_type -> cyberia.PingRequest
	31, // 43: cyberia.CyberiaDataService.GetObjectLayerManifest:input_type -> cyberia.GetObjectLayerManifestRequest
	17, // 44: cyberia.CyberiaDataService.GetFullInstance:output_type -> cyberia.GetFullInstanceResponse
	27, // 45: cyberia.CyberiaDataService.GetMapData:output_type -> cyberia.GetMapDataResponse
	6,  // 46: cyberia.CyberiaDataService.GetObjectLayerBatch:output_type -> cyberia.ObjectLayerMessage
	6,  // 47: cyberia.CyberiaDataService.GetObjectLayer:output_type -> cyberia.ObjectLayerMessage
	11, // 48: cyberia.CyberiaDataService.GetAtlasSpriteSheet:output_type -> cyberia.AtlasSpriteSheetMessage
	11, // 49: cyberia.CyberiaDataService.GetAtlasSpriteSheetBatch:output_type -> cyberia.AtlasSpriteSheetMessage
	29, // 50: cyberia.CyberiaDataService.Ping:output_type -> cyberia.PingResponse
	32, // 51: cyberia.CyberiaDataService.GetObjectLayerManifest:output_type -> cyberia.GetObjectLayerManifestResponse
	44, // [44:52] is the sub-list for method output_type
	36, // [36:44] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_cyberia_proto_init() }
func file_proto_cyberia_proto_init() {
	if File_proto_cyberia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cyberia_proto_goTypes,
		DependencyIndexes: file_proto_cyberia_proto_depIdxs,
		MessageInfos:      file_proto_cyberia_proto_msgTypes,
	}.Build()
	File_proto_cyberia_proto = out.File
	file_proto_cyberia_proto_goTypes = nil
	file_proto_cyberia_proto_depIdxs = nil
}
