// Protocol Buffers schema for Cyberia Online gRPC data pipeline.
//
// This service runs on the Engine-Cyberia (Node.js) side.
// The Cyberia-Server (Go) acts as the gRPC **client**, calling
// these RPCs to fetch game data for world reconstruction.
//
// Design rules:
//   1. Read-only — no create / update / delete.
//   2. Batch-friendly — large collections streamed or paginated.
//   3. Live-reload aware — version fields let the Go server detect
//      stale data and perform surgical in-memory replacement.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.14.0
// source: cyberia.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CyberiaDataService_GetFullInstance_FullMethodName          = "/cyberia.CyberiaDataService/GetFullInstance"
	CyberiaDataService_GetMapData_FullMethodName               = "/cyberia.CyberiaDataService/GetMapData"
	CyberiaDataService_GetObjectLayerBatch_FullMethodName      = "/cyberia.CyberiaDataService/GetObjectLayerBatch"
	CyberiaDataService_GetObjectLayer_FullMethodName           = "/cyberia.CyberiaDataService/GetObjectLayer"
	CyberiaDataService_GetAtlasSpriteSheet_FullMethodName      = "/cyberia.CyberiaDataService/GetAtlasSpriteSheet"
	CyberiaDataService_GetAtlasSpriteSheetBatch_FullMethodName = "/cyberia.CyberiaDataService/GetAtlasSpriteSheetBatch"
	CyberiaDataService_Ping_FullMethodName                     = "/cyberia.CyberiaDataService/Ping"
	CyberiaDataService_GetObjectLayerManifest_FullMethodName   = "/cyberia.CyberiaDataService/GetObjectLayerManifest"
)

// CyberiaDataServiceClient is the client API for CyberiaDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CyberiaDataServiceClient interface {
	// ── Instance / World Graph ──────────────────────────────────────
	// Returns the full instance graph (maps + portals) for a given
	// instance code.  Used at startup or during hot-reload.
	GetFullInstance(ctx context.Context, in *GetFullInstanceRequest, opts ...grpc.CallOption) (*GetFullInstanceResponse, error)
	// ── Maps ────────────────────────────────────────────────────────
	// Returns map data (grid, entities, metadata) for one map code.
	GetMapData(ctx context.Context, in *GetMapDataRequest, opts ...grpc.CallOption) (*GetMapDataResponse, error)
	// ── Object Layers ───────────────────────────────────────────────
	// Streams all ObjectLayers in the database.
	// Useful for initial cache warm-up on the Go server.
	GetObjectLayerBatch(ctx context.Context, in *GetObjectLayerBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectLayerMessage], error)
	// Returns a single ObjectLayer by item ID.
	GetObjectLayer(ctx context.Context, in *GetObjectLayerRequest, opts ...grpc.CallOption) (*ObjectLayerMessage, error)
	// ── Atlas Sprite Sheets ─────────────────────────────────────────
	// Returns atlas metadata (frame positions, dimensions) for an item.
	// The actual PNG binary is served via REST (/api/file/blob/:fileId).
	GetAtlasSpriteSheet(ctx context.Context, in *GetAtlasSpriteSheetRequest, opts ...grpc.CallOption) (*AtlasSpriteSheetMessage, error)
	// Streams all AtlasSpriteSheets in the database.
	// Used at startup to populate the Go server's atlas cache.
	GetAtlasSpriteSheetBatch(ctx context.Context, in *GetAtlasSpriteSheetBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AtlasSpriteSheetMessage], error)
	// ── Reload / Health ─────────────────────────────────────────────
	// Lightweight ping to check Engine liveness before hot-reload.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Returns a manifest of all ObjectLayer item IDs + sha256 hashes
	// so the Go server can diff against its cache and only re-fetch
	// what changed (incremental hot-reload).
	GetObjectLayerManifest(ctx context.Context, in *GetObjectLayerManifestRequest, opts ...grpc.CallOption) (*GetObjectLayerManifestResponse, error)
}

type cyberiaDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCyberiaDataServiceClient(cc grpc.ClientConnInterface) CyberiaDataServiceClient {
	return &cyberiaDataServiceClient{cc}
}

func (c *cyberiaDataServiceClient) GetFullInstance(ctx context.Context, in *GetFullInstanceRequest, opts ...grpc.CallOption) (*GetFullInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFullInstanceResponse)
	err := c.cc.Invoke(ctx, CyberiaDataService_GetFullInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberiaDataServiceClient) GetMapData(ctx context.Context, in *GetMapDataRequest, opts ...grpc.CallOption) (*GetMapDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMapDataResponse)
	err := c.cc.Invoke(ctx, CyberiaDataService_GetMapData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberiaDataServiceClient) GetObjectLayerBatch(ctx context.Context, in *GetObjectLayerBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ObjectLayerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CyberiaDataService_ServiceDesc.Streams[0], CyberiaDataService_GetObjectLayerBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectLayerBatchRequest, ObjectLayerMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CyberiaDataService_GetObjectLayerBatchClient = grpc.ServerStreamingClient[ObjectLayerMessage]

func (c *cyberiaDataServiceClient) GetObjectLayer(ctx context.Context, in *GetObjectLayerRequest, opts ...grpc.CallOption) (*ObjectLayerMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectLayerMessage)
	err := c.cc.Invoke(ctx, CyberiaDataService_GetObjectLayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberiaDataServiceClient) GetAtlasSpriteSheet(ctx context.Context, in *GetAtlasSpriteSheetRequest, opts ...grpc.CallOption) (*AtlasSpriteSheetMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AtlasSpriteSheetMessage)
	err := c.cc.Invoke(ctx, CyberiaDataService_GetAtlasSpriteSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberiaDataServiceClient) GetAtlasSpriteSheetBatch(ctx context.Context, in *GetAtlasSpriteSheetBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AtlasSpriteSheetMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CyberiaDataService_ServiceDesc.Streams[1], CyberiaDataService_GetAtlasSpriteSheetBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetAtlasSpriteSheetBatchRequest, AtlasSpriteSheetMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CyberiaDataService_GetAtlasSpriteSheetBatchClient = grpc.ServerStreamingClient[AtlasSpriteSheetMessage]

func (c *cyberiaDataServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, CyberiaDataService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cyberiaDataServiceClient) GetObjectLayerManifest(ctx context.Context, in *GetObjectLayerManifestRequest, opts ...grpc.CallOption) (*GetObjectLayerManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectLayerManifestResponse)
	err := c.cc.Invoke(ctx, CyberiaDataService_GetObjectLayerManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CyberiaDataServiceServer is the server API for CyberiaDataService service.
// All implementations must embed UnimplementedCyberiaDataServiceServer
// for forward compatibility.
type CyberiaDataServiceServer interface {
	// ── Instance / World Graph ──────────────────────────────────────
	// Returns the full instance graph (maps + portals) for a given
	// instance code.  Used at startup or during hot-reload.
	GetFullInstance(context.Context, *GetFullInstanceRequest) (*GetFullInstanceResponse, error)
	// ── Maps ────────────────────────────────────────────────────────
	// Returns map data (grid, entities, metadata) for one map code.
	GetMapData(context.Context, *GetMapDataRequest) (*GetMapDataResponse, error)
	// ── Object Layers ───────────────────────────────────────────────
	// Streams all ObjectLayers in the database.
	// Useful for initial cache warm-up on the Go server.
	GetObjectLayerBatch(*GetObjectLayerBatchRequest, grpc.ServerStreamingServer[ObjectLayerMessage]) error
	// Returns a single ObjectLayer by item ID.
	GetObjectLayer(context.Context, *GetObjectLayerRequest) (*ObjectLayerMessage, error)
	// ── Atlas Sprite Sheets ─────────────────────────────────────────
	// Returns atlas metadata (frame positions, dimensions) for an item.
	// The actual PNG binary is served via REST (/api/file/blob/:fileId).
	GetAtlasSpriteSheet(context.Context, *GetAtlasSpriteSheetRequest) (*AtlasSpriteSheetMessage, error)
	// Streams all AtlasSpriteSheets in the database.
	// Used at startup to populate the Go server's atlas cache.
	GetAtlasSpriteSheetBatch(*GetAtlasSpriteSheetBatchRequest, grpc.ServerStreamingServer[AtlasSpriteSheetMessage]) error
	// ── Reload / Health ─────────────────────────────────────────────
	// Lightweight ping to check Engine liveness before hot-reload.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Returns a manifest of all ObjectLayer item IDs + sha256 hashes
	// so the Go server can diff against its cache and only re-fetch
	// what changed (incremental hot-reload).
	GetObjectLayerManifest(context.Context, *GetObjectLayerManifestRequest) (*GetObjectLayerManifestResponse, error)
	mustEmbedUnimplementedCyberiaDataServiceServer()
}

// UnimplementedCyberiaDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCyberiaDataServiceServer struct{}

func (UnimplementedCyberiaDataServiceServer) GetFullInstance(context.Context, *GetFullInstanceRequest) (*GetFullInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFullInstance not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetMapData(context.Context, *GetMapDataRequest) (*GetMapDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapData not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetObjectLayerBatch(*GetObjectLayerBatchRequest, grpc.ServerStreamingServer[ObjectLayerMessage]) error {
	return status.Error(codes.Unimplemented, "method GetObjectLayerBatch not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetObjectLayer(context.Context, *GetObjectLayerRequest) (*ObjectLayerMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectLayer not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetAtlasSpriteSheet(context.Context, *GetAtlasSpriteSheetRequest) (*AtlasSpriteSheetMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAtlasSpriteSheet not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetAtlasSpriteSheetBatch(*GetAtlasSpriteSheetBatchRequest, grpc.ServerStreamingServer[AtlasSpriteSheetMessage]) error {
	return status.Error(codes.Unimplemented, "method GetAtlasSpriteSheetBatch not implemented")
}
func (UnimplementedCyberiaDataServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCyberiaDataServiceServer) GetObjectLayerManifest(context.Context, *GetObjectLayerManifestRequest) (*GetObjectLayerManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectLayerManifest not implemented")
}
func (UnimplementedCyberiaDataServiceServer) mustEmbedUnimplementedCyberiaDataServiceServer() {}
func (UnimplementedCyberiaDataServiceServer) testEmbeddedByValue()                            {}

// UnsafeCyberiaDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CyberiaDataServiceServer will
// result in compilation errors.
type UnsafeCyberiaDataServiceServer interface {
	mustEmbedUnimplementedCyberiaDataServiceServer()
}

func RegisterCyberiaDataServiceServer(s grpc.ServiceRegistrar, srv CyberiaDataServiceServer) {
	// If the following call panics, it indicates UnimplementedCyberiaDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CyberiaDataService_ServiceDesc, srv)
}

func _CyberiaDataService_GetFullInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFullInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).GetFullInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_GetFullInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).GetFullInstance(ctx, req.(*GetFullInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberiaDataService_GetMapData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).GetMapData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_GetMapData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).GetMapData(ctx, req.(*GetMapDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberiaDataService_GetObjectLayerBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectLayerBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CyberiaDataServiceServer).GetObjectLayerBatch(m, &grpc.GenericServerStream[GetObjectLayerBatchRequest, ObjectLayerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CyberiaDataService_GetObjectLayerBatchServer = grpc.ServerStreamingServer[ObjectLayerMessage]

func _CyberiaDataService_GetObjectLayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectLayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).GetObjectLayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_GetObjectLayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).GetObjectLayer(ctx, req.(*GetObjectLayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberiaDataService_GetAtlasSpriteSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAtlasSpriteSheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).GetAtlasSpriteSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_GetAtlasSpriteSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).GetAtlasSpriteSheet(ctx, req.(*GetAtlasSpriteSheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberiaDataService_GetAtlasSpriteSheetBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAtlasSpriteSheetBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CyberiaDataServiceServer).GetAtlasSpriteSheetBatch(m, &grpc.GenericServerStream[GetAtlasSpriteSheetBatchRequest, AtlasSpriteSheetMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CyberiaDataService_GetAtlasSpriteSheetBatchServer = grpc.ServerStreamingServer[AtlasSpriteSheetMessage]

func _CyberiaDataService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CyberiaDataService_GetObjectLayerManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectLayerManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CyberiaDataServiceServer).GetObjectLayerManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CyberiaDataService_GetObjectLayerManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CyberiaDataServiceServer).GetObjectLayerManifest(ctx, req.(*GetObjectLayerManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CyberiaDataService_ServiceDesc is the grpc.ServiceDesc for CyberiaDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CyberiaDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberia.CyberiaDataService",
	HandlerType: (*CyberiaDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFullInstance",
			Handler:    _CyberiaDataService_GetFullInstance_Handler,
		},
		{
			MethodName: "GetMapData",
			Handler:    _CyberiaDataService_GetMapData_Handler,
		},
		{
			MethodName: "GetObjectLayer",
			Handler:    _CyberiaDataService_GetObjectLayer_Handler,
		},
		{
			MethodName: "GetAtlasSpriteSheet",
			Handler:    _CyberiaDataService_GetAtlasSpriteSheet_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CyberiaDataService_Ping_Handler,
		},
		{
			MethodName: "GetObjectLayerManifest",
			Handler:    _CyberiaDataService_GetObjectLayerManifest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObjectLayerBatch",
			Handler:       _CyberiaDataService_GetObjectLayerBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAtlasSpriteSheetBatch",
			Handler:       _CyberiaDataService_GetAtlasSpriteSheetBatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cyberia.proto",
}
