// Protocol Buffers schema for Cyberia Online gRPC data pipeline.
//
// This service runs on the Engine-Cyberia (Node.js) side.
// The Cyberia-Server (Go) acts as the gRPC **client**, calling
// these RPCs to fetch game data for world reconstruction.
//
// Design rules:
//   1. Read-only — no create / update / delete.
//   2. Batch-friendly — large collections streamed or paginated.
//   3. Live-reload aware — version fields let the Go server detect
//      stale data and perform surgical in-memory replacement.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.14.0
// source: proto/cyberia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_cyberia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Vec2I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2I) Reset() {
	*x = Vec2I{}
	mi := &file_proto_cyberia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2I) ProtoMessage() {}

func (x *Vec2I) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2I.ProtoReflect.Descriptor instead.
func (*Vec2I) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{1}
}

func (x *Vec2I) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2I) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        int32                  `protobuf:"varint,1,opt,name=effect,proto3" json:"effect,omitempty"`
	Resistance    int32                  `protobuf:"varint,2,opt,name=resistance,proto3" json:"resistance,omitempty"`
	Agility       int32                  `protobuf:"varint,3,opt,name=agility,proto3" json:"agility,omitempty"`
	Range         int32                  `protobuf:"varint,4,opt,name=range,proto3" json:"range,omitempty"`
	Intelligence  int32                  `protobuf:"varint,5,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Utility       int32                  `protobuf:"varint,6,opt,name=utility,proto3" json:"utility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_cyberia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetEffect() int32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

func (x *Stats) GetResistance() int32 {
	if x != nil {
		return x.Resistance
	}
	return 0
}

func (x *Stats) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Stats) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *Stats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Stats) GetUtility() int32 {
	if x != nil {
		return x.Utility
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Activable     bool                   `protobuf:"varint,4,opt,name=activable,proto3" json:"activable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_proto_cyberia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{3}
}

func (x *ItemInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ItemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemInfo) GetActivable() bool {
	if x != nil {
		return x.Activable
	}
	return false
}

type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // ERC1155 | OFF_CHAIN
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_proto_cyberia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{4}
}

func (x *Ledger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ledger) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ledger) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type Render struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`                                    // IPFS CID atlas PNG
	MetadataCid   string                 `protobuf:"bytes,2,opt,name=metadata_cid,json=metadataCid,proto3" json:"metadata_cid,omitempty"` // IPFS CID atlas metadata JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Render) Reset() {
	*x = Render{}
	mi := &file_proto_cyberia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Render) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Render) ProtoMessage() {}

func (x *Render) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Render.ProtoReflect.Descriptor instead.
func (*Render) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{5}
}

func (x *Render) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Render) GetMetadataCid() string {
	if x != nil {
		return x.MetadataCid
	}
	return ""
}

type ObjectLayerMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MongoId string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"` // MongoDB _id
	Stats   *Stats                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Item    *ItemInfo              `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Ledger  *Ledger                `protobuf:"bytes,4,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Render  *Render                `protobuf:"bytes,5,opt,name=render,proto3" json:"render,omitempty"`
	Sha256  string                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Cid     string                 `protobuf:"bytes,7,opt,name=cid,proto3" json:"cid,omitempty"` // IPFS CID of the OL data JSON
	// Animation metadata (populated from ObjectLayerRenderFrames ref)
	FrameDuration int32 `protobuf:"varint,8,opt,name=frame_duration,json=frameDuration,proto3" json:"frame_duration,omitempty"` // ms per frame
	IsStateless   bool  `protobuf:"varint,9,opt,name=is_stateless,json=isStateless,proto3" json:"is_stateless,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerMessage) Reset() {
	*x = ObjectLayerMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerMessage) ProtoMessage() {}

func (x *ObjectLayerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerMessage.ProtoReflect.Descriptor instead.
func (*ObjectLayerMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectLayerMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *ObjectLayerMessage) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ObjectLayerMessage) GetItem() *ItemInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ObjectLayerMessage) GetLedger() *Ledger {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *ObjectLayerMessage) GetRender() *Render {
	if x != nil {
		return x.Render
	}
	return nil
}

func (x *ObjectLayerMessage) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ObjectLayerMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ObjectLayerMessage) GetFrameDuration() int32 {
	if x != nil {
		return x.FrameDuration
	}
	return 0
}

func (x *ObjectLayerMessage) GetIsStateless() bool {
	if x != nil {
		return x.IsStateless
	}
	return false
}

type GetObjectLayerBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by item type (e.g. "skin", "weapon").
	// Empty = return all.
	ItemTypeFilter string `protobuf:"bytes,1,opt,name=item_type_filter,json=itemTypeFilter,proto3" json:"item_type_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetObjectLayerBatchRequest) Reset() {
	*x = GetObjectLayerBatchRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerBatchRequest) ProtoMessage() {}

func (x *GetObjectLayerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerBatchRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectLayerBatchRequest) GetItemTypeFilter() string {
	if x != nil {
		return x.ItemTypeFilter
	}
	return ""
}

type GetObjectLayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerRequest) Reset() {
	*x = GetObjectLayerRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerRequest) ProtoMessage() {}

func (x *GetObjectLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{8}
}

func (x *GetObjectLayerRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type PortalEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceMapCode string                 `protobuf:"bytes,1,opt,name=source_map_code,json=sourceMapCode,proto3" json:"source_map_code,omitempty"`
	SourceCellX   int32                  `protobuf:"varint,2,opt,name=source_cell_x,json=sourceCellX,proto3" json:"source_cell_x,omitempty"`
	SourceCellY   int32                  `protobuf:"varint,3,opt,name=source_cell_y,json=sourceCellY,proto3" json:"source_cell_y,omitempty"`
	TargetMapCode string                 `protobuf:"bytes,4,opt,name=target_map_code,json=targetMapCode,proto3" json:"target_map_code,omitempty"`
	TargetCellX   int32                  `protobuf:"varint,5,opt,name=target_cell_x,json=targetCellX,proto3" json:"target_cell_x,omitempty"`
	TargetCellY   int32                  `protobuf:"varint,6,opt,name=target_cell_y,json=targetCellY,proto3" json:"target_cell_y,omitempty"`
	// Transport behaviour: inter-portal | inter-random | intra-random | intra-portal
	PortalMode    string `protobuf:"bytes,7,opt,name=portal_mode,json=portalMode,proto3" json:"portal_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortalEdge) Reset() {
	*x = PortalEdge{}
	mi := &file_proto_cyberia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalEdge) ProtoMessage() {}

func (x *PortalEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalEdge.ProtoReflect.Descriptor instead.
func (*PortalEdge) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{9}
}

func (x *PortalEdge) GetSourceMapCode() string {
	if x != nil {
		return x.SourceMapCode
	}
	return ""
}

func (x *PortalEdge) GetSourceCellX() int32 {
	if x != nil {
		return x.SourceCellX
	}
	return 0
}

func (x *PortalEdge) GetSourceCellY() int32 {
	if x != nil {
		return x.SourceCellY
	}
	return 0
}

func (x *PortalEdge) GetTargetMapCode() string {
	if x != nil {
		return x.TargetMapCode
	}
	return ""
}

func (x *PortalEdge) GetTargetCellX() int32 {
	if x != nil {
		return x.TargetCellX
	}
	return 0
}

func (x *PortalEdge) GetTargetCellY() int32 {
	if x != nil {
		return x.TargetCellY
	}
	return 0
}

func (x *PortalEdge) GetPortalMode() string {
	if x != nil {
		return x.PortalMode
	}
	return ""
}

type InstanceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	MapCodes      []string               `protobuf:"bytes,6,rep,name=map_codes,json=mapCodes,proto3" json:"map_codes,omitempty"` // vertex set
	Portals       []*PortalEdge          `protobuf:"bytes,7,rep,name=portals,proto3" json:"portals,omitempty"`                   // edge set
	TopologyMode  string                 `protobuf:"bytes,8,opt,name=topology_mode,json=topologyMode,proto3" json:"topology_mode,omitempty"`
	Seed          string                 `protobuf:"bytes,9,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceMessage) Reset() {
	*x = InstanceMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceMessage) ProtoMessage() {}

func (x *InstanceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceMessage.ProtoReflect.Descriptor instead.
func (*InstanceMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{10}
}

func (x *InstanceMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *InstanceMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstanceMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InstanceMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InstanceMessage) GetMapCodes() []string {
	if x != nil {
		return x.MapCodes
	}
	return nil
}

func (x *InstanceMessage) GetPortals() []*PortalEdge {
	if x != nil {
		return x.Portals
	}
	return nil
}

func (x *InstanceMessage) GetTopologyMode() string {
	if x != nil {
		return x.TopologyMode
	}
	return ""
}

func (x *InstanceMessage) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type GetFullInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceCode  string                 `protobuf:"bytes,1,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceRequest) Reset() {
	*x = GetFullInstanceRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceRequest) ProtoMessage() {}

func (x *GetFullInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetFullInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{11}
}

func (x *GetFullInstanceRequest) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

type GetFullInstanceResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Instance     *InstanceMessage       `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Maps         []*MapDataMessage      `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`
	ObjectLayers []*ObjectLayerMessage  `protobuf:"bytes,3,rep,name=object_layers,json=objectLayers,proto3" json:"object_layers,omitempty"`
	Config       *InstanceConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Opaque version string (e.g. combined updatedAt timestamps) for
	// change-detection.  The Go server compares this with the last known
	// value and skips a full rebuild when they match.
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFullInstanceResponse) Reset() {
	*x = GetFullInstanceResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFullInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFullInstanceResponse) ProtoMessage() {}

func (x *GetFullInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFullInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetFullInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{12}
}

func (x *GetFullInstanceResponse) GetInstance() *InstanceMessage {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetFullInstanceResponse) GetMaps() []*MapDataMessage {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *GetFullInstanceResponse) GetObjectLayers() []*ObjectLayerMessage {
	if x != nil {
		return x.ObjectLayers
	}
	return nil
}

func (x *GetFullInstanceResponse) GetConfig() *InstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetFullInstanceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ColorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	R             int32                  `protobuf:"varint,2,opt,name=r,proto3" json:"r,omitempty"`
	G             int32                  `protobuf:"varint,3,opt,name=g,proto3" json:"g,omitempty"`
	B             int32                  `protobuf:"varint,4,opt,name=b,proto3" json:"b,omitempty"`
	A             int32                  `protobuf:"varint,5,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorEntry) Reset() {
	*x = ColorEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorEntry) ProtoMessage() {}

func (x *ColorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorEntry.ProtoReflect.Descriptor instead.
func (*ColorEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{13}
}

func (x *ColorEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ColorEntry) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *ColorEntry) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *ColorEntry) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *ColorEntry) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

type DefaultObjectLayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultObjectLayerState) Reset() {
	*x = DefaultObjectLayerState{}
	mi := &file_proto_cyberia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultObjectLayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultObjectLayerState) ProtoMessage() {}

func (x *DefaultObjectLayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultObjectLayerState.ProtoReflect.Descriptor instead.
func (*DefaultObjectLayerState) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{14}
}

func (x *DefaultObjectLayerState) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DefaultObjectLayerState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DefaultObjectLayerState) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SkillDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LogicEventId         string                 `protobuf:"bytes,1,opt,name=logic_event_id,json=logicEventId,proto3" json:"logic_event_id,omitempty"`                           // skill handler key (e.g. "projectile", "doppelganger")
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                   // human-readable skill description shown in the inventory modal
	SummonedEntityItemId string                 `protobuf:"bytes,3,opt,name=summoned_entity_item_id,json=summonedEntityItemId,proto3" json:"summoned_entity_item_id,omitempty"` // ObjectLayer item ID of the entity summoned by this skill ("$active_skin" = dynamic)
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                                 // display name for the skill (e.g. "Projectile", "Doppelganger")
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SkillDetail) Reset() {
	*x = SkillDetail{}
	mi := &file_proto_cyberia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDetail) ProtoMessage() {}

func (x *SkillDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDetail.ProtoReflect.Descriptor instead.
func (*SkillDetail) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{15}
}

func (x *SkillDetail) GetLogicEventId() string {
	if x != nil {
		return x.LogicEventId
	}
	return ""
}

func (x *SkillDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillDetail) GetSummonedEntityItemId() string {
	if x != nil {
		return x.SummonedEntityItemId
	}
	return ""
}

func (x *SkillDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SkillConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerItemId string                 `protobuf:"bytes,1,opt,name=trigger_item_id,json=triggerItemId,proto3" json:"trigger_item_id,omitempty"` // item that triggers the skill
	Skills        []*SkillDetail         `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`                                      // per-logic-event skill definitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillConfigEntry) Reset() {
	*x = SkillConfigEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillConfigEntry) ProtoMessage() {}

func (x *SkillConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillConfigEntry.ProtoReflect.Descriptor instead.
func (*SkillConfigEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{16}
}

func (x *SkillConfigEntry) GetTriggerItemId() string {
	if x != nil {
		return x.TriggerItemId
	}
	return ""
}

func (x *SkillConfigEntry) GetSkills() []*SkillDetail {
	if x != nil {
		return x.Skills
	}
	return nil
}

// EconomyRules groups all Fountain & Sink economy parameters for one instance.
//
// Design: Fountain & Sink (EVE Online / WoW model)
//
//	Fountains   — inject new coins into the economy on every bot/player spawn.
//	Kill Transfer — zero-sum redistribution between participants on a kill event.
//	Sinks       — permanently destroy coins (alpha: all 0 / disabled by default).
//
// Off-chain fall-back: when a player has no on-chain session the server operates
// a purely in-memory wallet that resets on reconnect.  All balances map 1-to-1
// with the CKY ERC-1155 token (token ID 0) once the on-chain bridge is live.
type EconomyRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Fountains ──────────────────────────────────────────────────────────────
	// Coins bots carry at spawn and on every respawn (infinite mint source).
	// Guarantees PvE reward loops are never blocked by an empty bot wallet.
	BotSpawnCoins int32 `protobuf:"varint,1,opt,name=bot_spawn_coins,json=botSpawnCoins,proto3" json:"bot_spawn_coins,omitempty"`
	// Player starting wallet on connect (no persistence — resets on reconnect).
	// In guest mode this is the only coin source; persists only with on-chain auth.
	PlayerSpawnCoins int32 `protobuf:"varint,2,opt,name=player_spawn_coins,json=playerSpawnCoins,proto3" json:"player_spawn_coins,omitempty"`
	// ── Kill Transfer (zero-sum redistribution) ────────────────────────────────
	// Fraction [0,1] of the victim's coins transferred to the killer on a PvE kill
	// (player kills bot, or bot kills bot).  Higher than PvP rate to reward grinding.
	CoinKillPercentVsBot float64 `protobuf:"fixed64,3,opt,name=coin_kill_percent_vs_bot,json=coinKillPercentVsBot,proto3" json:"coin_kill_percent_vs_bot,omitempty"`
	// Fraction [0,1] transferred on a PvP kill.  Intentionally lower to reduce
	// griefing frustration while still making PvP economically meaningful.
	CoinKillPercentVsPlayer float64 `protobuf:"fixed64,4,opt,name=coin_kill_percent_vs_player,json=coinKillPercentVsPlayer,proto3" json:"coin_kill_percent_vs_player,omitempty"`
	// Hard floor per kill: guarantees every successful kill pays at least this many
	// coins regardless of the victim's wallet size or the percent rate.
	CoinKillMinAmount int32 `protobuf:"varint,5,opt,name=coin_kill_min_amount,json=coinKillMinAmount,proto3" json:"coin_kill_min_amount,omitempty"`
	// ── Sinks (alpha stubs — set to 0 to disable) ─────────────────────────────
	// Fraction [0,1] of the dying player's coins permanently burned on respawn.
	// Incentivises caution; 0 = disabled (recommended for alpha).
	RespawnCostPercent float64 `protobuf:"fixed64,6,opt,name=respawn_cost_percent,json=respawnCostPercent,proto3" json:"respawn_cost_percent,omitempty"`
	// Flat coins burned each time a player uses a portal (travel tax).
	// Drains coin hoarding; 0 = disabled.
	PortalFee int32 `protobuf:"varint,7,opt,name=portal_fee,json=portalFee,proto3" json:"portal_fee,omitempty"`
	// Fraction [0,1] of item value burned on any crafting action (production tax).
	// 0 = disabled until the crafting system is implemented.
	CraftingFeePercent float64 `protobuf:"fixed64,8,opt,name=crafting_fee_percent,json=craftingFeePercent,proto3" json:"crafting_fee_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EconomyRules) Reset() {
	*x = EconomyRules{}
	mi := &file_proto_cyberia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EconomyRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EconomyRules) ProtoMessage() {}

func (x *EconomyRules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EconomyRules.ProtoReflect.Descriptor instead.
func (*EconomyRules) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{17}
}

func (x *EconomyRules) GetBotSpawnCoins() int32 {
	if x != nil {
		return x.BotSpawnCoins
	}
	return 0
}

func (x *EconomyRules) GetPlayerSpawnCoins() int32 {
	if x != nil {
		return x.PlayerSpawnCoins
	}
	return 0
}

func (x *EconomyRules) GetCoinKillPercentVsBot() float64 {
	if x != nil {
		return x.CoinKillPercentVsBot
	}
	return 0
}

func (x *EconomyRules) GetCoinKillPercentVsPlayer() float64 {
	if x != nil {
		return x.CoinKillPercentVsPlayer
	}
	return 0
}

func (x *EconomyRules) GetCoinKillMinAmount() int32 {
	if x != nil {
		return x.CoinKillMinAmount
	}
	return 0
}

func (x *EconomyRules) GetRespawnCostPercent() float64 {
	if x != nil {
		return x.RespawnCostPercent
	}
	return 0
}

func (x *EconomyRules) GetPortalFee() int32 {
	if x != nil {
		return x.PortalFee
	}
	return 0
}

func (x *EconomyRules) GetCraftingFeePercent() float64 {
	if x != nil {
		return x.CraftingFeePercent
	}
	return 0
}

// SkillRules groups the numeric tuning parameters for each skill archetype.
// These are instance-level defaults; individual SkillConfigEntry entries define
// WHICH items trigger WHICH logic, while SkillRules defines HOW that logic behaves.
type SkillRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Projectile skill ──
	ProjectileSpawnChance     float64 `protobuf:"fixed64,1,opt,name=projectile_spawn_chance,json=projectileSpawnChance,proto3" json:"projectile_spawn_chance,omitempty"`             // base probability [0,1] per action tick
	ProjectileLifetimeMs      int32   `protobuf:"varint,2,opt,name=projectile_lifetime_ms,json=projectileLifetimeMs,proto3" json:"projectile_lifetime_ms,omitempty"`                 // base projectile TTL in ms (Range stat adds extra)
	ProjectileWidth           float64 `protobuf:"fixed64,3,opt,name=projectile_width,json=projectileWidth,proto3" json:"projectile_width,omitempty"`                                 // projectile entity width in grid cells
	ProjectileHeight          float64 `protobuf:"fixed64,4,opt,name=projectile_height,json=projectileHeight,proto3" json:"projectile_height,omitempty"`                              // projectile entity height in grid cells
	ProjectileSpeedMultiplier float64 `protobuf:"fixed64,5,opt,name=projectile_speed_multiplier,json=projectileSpeedMultiplier,proto3" json:"projectile_speed_multiplier,omitempty"` // multiplier applied on top of entity_base_speed
	// ── Doppelganger skill ──
	DoppelgangerSpawnChance         float64 `protobuf:"fixed64,6,opt,name=doppelganger_spawn_chance,json=doppelgangerSpawnChance,proto3" json:"doppelganger_spawn_chance,omitempty"`                           // base probability [0,1] per action tick
	DoppelgangerLifetimeMs          int32   `protobuf:"varint,7,opt,name=doppelganger_lifetime_ms,json=doppelgangerLifetimeMs,proto3" json:"doppelganger_lifetime_ms,omitempty"`                               // base doppelganger TTL in ms (Range adds extra)
	DoppelgangerSpawnRadius         float64 `protobuf:"fixed64,8,opt,name=doppelganger_spawn_radius,json=doppelgangerSpawnRadius,proto3" json:"doppelganger_spawn_radius,omitempty"`                           // wander radius around spawn point in cells
	DoppelgangerInitialLifeFraction float64 `protobuf:"fixed64,9,opt,name=doppelganger_initial_life_fraction,json=doppelgangerInitialLifeFraction,proto3" json:"doppelganger_initial_life_fraction,omitempty"` // fraction of entity_base_max_life at spawn
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *SkillRules) Reset() {
	*x = SkillRules{}
	mi := &file_proto_cyberia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRules) ProtoMessage() {}

func (x *SkillRules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRules.ProtoReflect.Descriptor instead.
func (*SkillRules) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{18}
}

func (x *SkillRules) GetProjectileSpawnChance() float64 {
	if x != nil {
		return x.ProjectileSpawnChance
	}
	return 0
}

func (x *SkillRules) GetProjectileLifetimeMs() int32 {
	if x != nil {
		return x.ProjectileLifetimeMs
	}
	return 0
}

func (x *SkillRules) GetProjectileWidth() float64 {
	if x != nil {
		return x.ProjectileWidth
	}
	return 0
}

func (x *SkillRules) GetProjectileHeight() float64 {
	if x != nil {
		return x.ProjectileHeight
	}
	return 0
}

func (x *SkillRules) GetProjectileSpeedMultiplier() float64 {
	if x != nil {
		return x.ProjectileSpeedMultiplier
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerSpawnChance() float64 {
	if x != nil {
		return x.DoppelgangerSpawnChance
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerLifetimeMs() int32 {
	if x != nil {
		return x.DoppelgangerLifetimeMs
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerSpawnRadius() float64 {
	if x != nil {
		return x.DoppelgangerSpawnRadius
	}
	return 0
}

func (x *SkillRules) GetDoppelgangerInitialLifeFraction() float64 {
	if x != nil {
		return x.DoppelgangerInitialLifeFraction
	}
	return 0
}

// EquipmentRules governs which ObjectLayer item types can be simultaneously
// active on a character entity and enforces the one-active-per-type constraint.
//
// The server validates every item_activation request against these rules:
//  1. Only item types listed in active_item_types may be activated.
//  2. When one_per_type is true, activating an item auto-deactivates
//     any other active item of the same type.
//  3. When require_skin is true, the player must always have at least
//     one active skin if they own any skin-type items.
type EquipmentRules struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Item types that players are allowed to activate (equip).
	// Types not in this list are non-activable (coins, floors, etc.).
	ActiveItemTypes []string `protobuf:"bytes,1,rep,name=active_item_types,json=activeItemTypes,proto3" json:"active_item_types,omitempty"`
	// Enforce at most one active item per item type.
	OnePerType bool `protobuf:"varint,2,opt,name=one_per_type,json=onePerType,proto3" json:"one_per_type,omitempty"`
	// Require at least one active skin when the player owns any skin.
	RequireSkin   bool `protobuf:"varint,3,opt,name=require_skin,json=requireSkin,proto3" json:"require_skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentRules) Reset() {
	*x = EquipmentRules{}
	mi := &file_proto_cyberia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRules) ProtoMessage() {}

func (x *EquipmentRules) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRules.ProtoReflect.Descriptor instead.
func (*EquipmentRules) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{19}
}

func (x *EquipmentRules) GetActiveItemTypes() []string {
	if x != nil {
		return x.ActiveItemTypes
	}
	return nil
}

func (x *EquipmentRules) GetOnePerType() bool {
	if x != nil {
		return x.OnePerType
	}
	return false
}

func (x *EquipmentRules) GetRequireSkin() bool {
	if x != nil {
		return x.RequireSkin
	}
	return false
}

type InstanceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Rendering / camera ──
	CellSize                  float64       `protobuf:"fixed64,1,opt,name=cell_size,json=cellSize,proto3" json:"cell_size,omitempty"`
	Fps                       int32         `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	InterpolationMs           int32         `protobuf:"varint,3,opt,name=interpolation_ms,json=interpolationMs,proto3" json:"interpolation_ms,omitempty"`
	DefaultObjWidth           float64       `protobuf:"fixed64,4,opt,name=default_obj_width,json=defaultObjWidth,proto3" json:"default_obj_width,omitempty"`
	DefaultObjHeight          float64       `protobuf:"fixed64,5,opt,name=default_obj_height,json=defaultObjHeight,proto3" json:"default_obj_height,omitempty"`
	CameraSmoothing           float64       `protobuf:"fixed64,6,opt,name=camera_smoothing,json=cameraSmoothing,proto3" json:"camera_smoothing,omitempty"`
	CameraZoom                float64       `protobuf:"fixed64,7,opt,name=camera_zoom,json=cameraZoom,proto3" json:"camera_zoom,omitempty"`
	DefaultWidthScreenFactor  float64       `protobuf:"fixed64,8,opt,name=default_width_screen_factor,json=defaultWidthScreenFactor,proto3" json:"default_width_screen_factor,omitempty"`
	DefaultHeightScreenFactor float64       `protobuf:"fixed64,9,opt,name=default_height_screen_factor,json=defaultHeightScreenFactor,proto3" json:"default_height_screen_factor,omitempty"`
	DevUi                     bool          `protobuf:"varint,10,opt,name=dev_ui,json=devUi,proto3" json:"dev_ui,omitempty"`
	Colors                    []*ColorEntry `protobuf:"bytes,11,rep,name=colors,proto3" json:"colors,omitempty"`
	// ── World / AOI ──
	AoiRadius         float64 `protobuf:"fixed64,12,opt,name=aoi_radius,json=aoiRadius,proto3" json:"aoi_radius,omitempty"`
	PortalHoldTimeMs  int32   `protobuf:"varint,13,opt,name=portal_hold_time_ms,json=portalHoldTimeMs,proto3" json:"portal_hold_time_ms,omitempty"`
	PortalSpawnRadius float64 `protobuf:"fixed64,14,opt,name=portal_spawn_radius,json=portalSpawnRadius,proto3" json:"portal_spawn_radius,omitempty"`
	// ── Entity base stats ──
	EntityBaseSpeed               float64 `protobuf:"fixed64,15,opt,name=entity_base_speed,json=entityBaseSpeed,proto3" json:"entity_base_speed,omitempty"`
	EntityBaseMaxLife             float64 `protobuf:"fixed64,16,opt,name=entity_base_max_life,json=entityBaseMaxLife,proto3" json:"entity_base_max_life,omitempty"`
	EntityBaseActionCooldownMs    int32   `protobuf:"varint,17,opt,name=entity_base_action_cooldown_ms,json=entityBaseActionCooldownMs,proto3" json:"entity_base_action_cooldown_ms,omitempty"`
	EntityBaseMinActionCooldownMs int32   `protobuf:"varint,18,opt,name=entity_base_min_action_cooldown_ms,json=entityBaseMinActionCooldownMs,proto3" json:"entity_base_min_action_cooldown_ms,omitempty"`
	// ── Bot defaults ──
	BotAggroRange float64 `protobuf:"fixed64,19,opt,name=bot_aggro_range,json=botAggroRange,proto3" json:"bot_aggro_range,omitempty"`
	// ── Player defaults ──
	DefaultPlayerWidth     float64 `protobuf:"fixed64,20,opt,name=default_player_width,json=defaultPlayerWidth,proto3" json:"default_player_width,omitempty"`
	DefaultPlayerHeight    float64 `protobuf:"fixed64,21,opt,name=default_player_height,json=defaultPlayerHeight,proto3" json:"default_player_height,omitempty"`
	PlayerBaseLifeRegenMin float64 `protobuf:"fixed64,22,opt,name=player_base_life_regen_min,json=playerBaseLifeRegenMin,proto3" json:"player_base_life_regen_min,omitempty"`
	PlayerBaseLifeRegenMax float64 `protobuf:"fixed64,23,opt,name=player_base_life_regen_max,json=playerBaseLifeRegenMax,proto3" json:"player_base_life_regen_max,omitempty"`
	SumStatsLimit          int32   `protobuf:"varint,24,opt,name=sum_stats_limit,json=sumStatsLimit,proto3" json:"sum_stats_limit,omitempty"`
	MaxActiveLayers        int32   `protobuf:"varint,25,opt,name=max_active_layers,json=maxActiveLayers,proto3" json:"max_active_layers,omitempty"`
	InitialLifeFraction    float64 `protobuf:"fixed64,26,opt,name=initial_life_fraction,json=initialLifeFraction,proto3" json:"initial_life_fraction,omitempty"`
	// ── Combat / death ──
	RespawnDurationMs int32   `protobuf:"varint,28,opt,name=respawn_duration_ms,json=respawnDurationMs,proto3" json:"respawn_duration_ms,omitempty"`
	CollisionLifeLoss float64 `protobuf:"fixed64,30,opt,name=collision_life_loss,json=collisionLifeLoss,proto3" json:"collision_life_loss,omitempty"`
	// ── Regen ──
	LifeRegenChance float64 `protobuf:"fixed64,33,opt,name=life_regen_chance,json=lifeRegenChance,proto3" json:"life_regen_chance,omitempty"`
	MaxChance       float64 `protobuf:"fixed64,34,opt,name=max_chance,json=maxChance,proto3" json:"max_chance,omitempty"`
	// ── Skill map (trigger → logic + items) ──
	SkillConfig []*SkillConfigEntry `protobuf:"bytes,45,rep,name=skill_config,json=skillConfig,proto3" json:"skill_config,omitempty"`
	// ── Skill tuning parameters ──
	SkillRules *SkillRules `protobuf:"bytes,47,opt,name=skill_rules,json=skillRules,proto3" json:"skill_rules,omitempty"`
	// ── Economy parameters (Fountain & Sink model) ──
	EconomyRules *EconomyRules `protobuf:"bytes,62,opt,name=economy_rules,json=economyRules,proto3" json:"economy_rules,omitempty"`
	// ── Equipment rules (activation constraints) ──
	EquipmentRules *EquipmentRules `protobuf:"bytes,63,opt,name=equipment_rules,json=equipmentRules,proto3" json:"equipment_rules,omitempty"`
	// ── Entity type rendering defaults ─────────────────────────────────────────
	// Structured per-entity-type configuration replacing the former flat item ID
	// fields.  Each entry defines the live OL, dead OL, and palette colour key
	// for one entity type ('player', 'bot', 'skill', 'coin', 'floor', …).
	// The Go server derives ghost/coin/floor item IDs from this repeated field.
	EntityDefaults []*EntityTypeDefault `protobuf:"bytes,52,rep,name=entity_defaults,json=entityDefaults,proto3" json:"entity_defaults,omitempty"`
	// ── Entity Status Indicators (overhead icon mapping) ───────────────────────
	// Dynamic u8→icon_id mapping — the single source of truth for which icon
	// filename to render for each server-assigned status ID.  Eliminates the
	// need for hardcoded tables in the C client.
	StatusIcons   []*StatusIconEntry `protobuf:"bytes,64,rep,name=status_icons,json=statusIcons,proto3" json:"status_icons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceConfig) Reset() {
	*x = InstanceConfig{}
	mi := &file_proto_cyberia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceConfig) ProtoMessage() {}

func (x *InstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceConfig.ProtoReflect.Descriptor instead.
func (*InstanceConfig) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{20}
}

func (x *InstanceConfig) GetCellSize() float64 {
	if x != nil {
		return x.CellSize
	}
	return 0
}

func (x *InstanceConfig) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *InstanceConfig) GetInterpolationMs() int32 {
	if x != nil {
		return x.InterpolationMs
	}
	return 0
}

func (x *InstanceConfig) GetDefaultObjWidth() float64 {
	if x != nil {
		return x.DefaultObjWidth
	}
	return 0
}

func (x *InstanceConfig) GetDefaultObjHeight() float64 {
	if x != nil {
		return x.DefaultObjHeight
	}
	return 0
}

func (x *InstanceConfig) GetCameraSmoothing() float64 {
	if x != nil {
		return x.CameraSmoothing
	}
	return 0
}

func (x *InstanceConfig) GetCameraZoom() float64 {
	if x != nil {
		return x.CameraZoom
	}
	return 0
}

func (x *InstanceConfig) GetDefaultWidthScreenFactor() float64 {
	if x != nil {
		return x.DefaultWidthScreenFactor
	}
	return 0
}

func (x *InstanceConfig) GetDefaultHeightScreenFactor() float64 {
	if x != nil {
		return x.DefaultHeightScreenFactor
	}
	return 0
}

func (x *InstanceConfig) GetDevUi() bool {
	if x != nil {
		return x.DevUi
	}
	return false
}

func (x *InstanceConfig) GetColors() []*ColorEntry {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *InstanceConfig) GetAoiRadius() float64 {
	if x != nil {
		return x.AoiRadius
	}
	return 0
}

func (x *InstanceConfig) GetPortalHoldTimeMs() int32 {
	if x != nil {
		return x.PortalHoldTimeMs
	}
	return 0
}

func (x *InstanceConfig) GetPortalSpawnRadius() float64 {
	if x != nil {
		return x.PortalSpawnRadius
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseSpeed() float64 {
	if x != nil {
		return x.EntityBaseSpeed
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseMaxLife() float64 {
	if x != nil {
		return x.EntityBaseMaxLife
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseActionCooldownMs() int32 {
	if x != nil {
		return x.EntityBaseActionCooldownMs
	}
	return 0
}

func (x *InstanceConfig) GetEntityBaseMinActionCooldownMs() int32 {
	if x != nil {
		return x.EntityBaseMinActionCooldownMs
	}
	return 0
}

func (x *InstanceConfig) GetBotAggroRange() float64 {
	if x != nil {
		return x.BotAggroRange
	}
	return 0
}

func (x *InstanceConfig) GetDefaultPlayerWidth() float64 {
	if x != nil {
		return x.DefaultPlayerWidth
	}
	return 0
}

func (x *InstanceConfig) GetDefaultPlayerHeight() float64 {
	if x != nil {
		return x.DefaultPlayerHeight
	}
	return 0
}

func (x *InstanceConfig) GetPlayerBaseLifeRegenMin() float64 {
	if x != nil {
		return x.PlayerBaseLifeRegenMin
	}
	return 0
}

func (x *InstanceConfig) GetPlayerBaseLifeRegenMax() float64 {
	if x != nil {
		return x.PlayerBaseLifeRegenMax
	}
	return 0
}

func (x *InstanceConfig) GetSumStatsLimit() int32 {
	if x != nil {
		return x.SumStatsLimit
	}
	return 0
}

func (x *InstanceConfig) GetMaxActiveLayers() int32 {
	if x != nil {
		return x.MaxActiveLayers
	}
	return 0
}

func (x *InstanceConfig) GetInitialLifeFraction() float64 {
	if x != nil {
		return x.InitialLifeFraction
	}
	return 0
}

func (x *InstanceConfig) GetRespawnDurationMs() int32 {
	if x != nil {
		return x.RespawnDurationMs
	}
	return 0
}

func (x *InstanceConfig) GetCollisionLifeLoss() float64 {
	if x != nil {
		return x.CollisionLifeLoss
	}
	return 0
}

func (x *InstanceConfig) GetLifeRegenChance() float64 {
	if x != nil {
		return x.LifeRegenChance
	}
	return 0
}

func (x *InstanceConfig) GetMaxChance() float64 {
	if x != nil {
		return x.MaxChance
	}
	return 0
}

func (x *InstanceConfig) GetSkillConfig() []*SkillConfigEntry {
	if x != nil {
		return x.SkillConfig
	}
	return nil
}

func (x *InstanceConfig) GetSkillRules() *SkillRules {
	if x != nil {
		return x.SkillRules
	}
	return nil
}

func (x *InstanceConfig) GetEconomyRules() *EconomyRules {
	if x != nil {
		return x.EconomyRules
	}
	return nil
}

func (x *InstanceConfig) GetEquipmentRules() *EquipmentRules {
	if x != nil {
		return x.EquipmentRules
	}
	return nil
}

func (x *InstanceConfig) GetEntityDefaults() []*EntityTypeDefault {
	if x != nil {
		return x.EntityDefaults
	}
	return nil
}

func (x *InstanceConfig) GetStatusIcons() []*StatusIconEntry {
	if x != nil {
		return x.StatusIcons
	}
	return nil
}

// ── Entity type defaults (per-entity visual + color configuration) ──────────
// Replaces the former flat string fields: ghost_item_id (29), coin_item_id (31),
// default_floor_item_id (44), bot_default_item_id (48), user_default_item_id (49).
type EntityTypeDefault struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EntityType  string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`      // matches entity_type_str / bot Behavior in game engine
	LiveItemIds []string               `protobuf:"bytes,2,rep,name=live_item_ids,json=liveItemIds,proto3" json:"live_item_ids,omitempty"` // OL item IDs for the alive/active state
	DeadItemIds []string               `protobuf:"bytes,3,rep,name=dead_item_ids,json=deadItemIds,proto3" json:"dead_item_ids,omitempty"` // OL item IDs for the dead/ghost/respawning state
	ColorKey    string                 `protobuf:"bytes,4,opt,name=color_key,json=colorKey,proto3" json:"color_key,omitempty"`            // palette key for solid-color fallback (no OL items)
	// Full default ObjectLayer inventory for this entity type.
	// Supersedes live_item_ids for inventory initialization when non-empty.
	// The canonical source of truth — shared across all entity config simulation.
	DefaultObjectLayers []*DefaultObjectLayerState `protobuf:"bytes,5,rep,name=default_object_layers,json=defaultObjectLayers,proto3" json:"default_object_layers,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntityTypeDefault) Reset() {
	*x = EntityTypeDefault{}
	mi := &file_proto_cyberia_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityTypeDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityTypeDefault) ProtoMessage() {}

func (x *EntityTypeDefault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityTypeDefault.ProtoReflect.Descriptor instead.
func (*EntityTypeDefault) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{21}
}

func (x *EntityTypeDefault) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityTypeDefault) GetLiveItemIds() []string {
	if x != nil {
		return x.LiveItemIds
	}
	return nil
}

func (x *EntityTypeDefault) GetDeadItemIds() []string {
	if x != nil {
		return x.DeadItemIds
	}
	return nil
}

func (x *EntityTypeDefault) GetColorKey() string {
	if x != nil {
		return x.ColorKey
	}
	return ""
}

func (x *EntityTypeDefault) GetDefaultObjectLayers() []*DefaultObjectLayerState {
	if x != nil {
		return x.DefaultObjectLayers
	}
	return nil
}

// ── Entity Status Indicator entry (overhead icon config) ────────────────────
// Maps a server-computed u8 status ID to a ui-icon filename stem and whether
// the icon should use bounce animation.  Sent in InitPayload.statusIcons so
// the C client resolves icons dynamically — no hardcoded lookup tables.
//
// border_color_* fields define the interaction-bubble border colour for
// entities that carry this status — fully server-driven, no client-side
// hardcoded colour tables.
type StatusIconEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // u8 status ID (0 = none, 1 = passive, …)
	IconId        string                 `protobuf:"bytes,2,opt,name=icon_id,json=iconId,proto3" json:"icon_id,omitempty"`                      // ui-icon filename stem (e.g. "arrow-down-red", "skull"); empty = no icon
	BorderColorR  int32                  `protobuf:"varint,3,opt,name=border_color_r,json=borderColorR,proto3" json:"border_color_r,omitempty"` // border colour red   [0-255]
	BorderColorG  int32                  `protobuf:"varint,4,opt,name=border_color_g,json=borderColorG,proto3" json:"border_color_g,omitempty"` // border colour green  [0-255]
	BorderColorB  int32                  `protobuf:"varint,5,opt,name=border_color_b,json=borderColorB,proto3" json:"border_color_b,omitempty"` // border colour blue   [0-255]
	BorderColorA  int32                  `protobuf:"varint,6,opt,name=border_color_a,json=borderColorA,proto3" json:"border_color_a,omitempty"` // border colour alpha  [0-255]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusIconEntry) Reset() {
	*x = StatusIconEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusIconEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusIconEntry) ProtoMessage() {}

func (x *StatusIconEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusIconEntry.ProtoReflect.Descriptor instead.
func (*StatusIconEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{22}
}

func (x *StatusIconEntry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusIconEntry) GetIconId() string {
	if x != nil {
		return x.IconId
	}
	return ""
}

func (x *StatusIconEntry) GetBorderColorR() int32 {
	if x != nil {
		return x.BorderColorR
	}
	return 0
}

func (x *StatusIconEntry) GetBorderColorG() int32 {
	if x != nil {
		return x.BorderColorG
	}
	return 0
}

func (x *StatusIconEntry) GetBorderColorB() int32 {
	if x != nil {
		return x.BorderColorB
	}
	return 0
}

func (x *StatusIconEntry) GetBorderColorA() int32 {
	if x != nil {
		return x.BorderColorA
	}
	return 0
}

type EntityMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityType         string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	InitCellX          int32                  `protobuf:"varint,2,opt,name=init_cell_x,json=initCellX,proto3" json:"init_cell_x,omitempty"`
	InitCellY          int32                  `protobuf:"varint,3,opt,name=init_cell_y,json=initCellY,proto3" json:"init_cell_y,omitempty"`
	DimX               int32                  `protobuf:"varint,4,opt,name=dim_x,json=dimX,proto3" json:"dim_x,omitempty"`
	DimY               int32                  `protobuf:"varint,5,opt,name=dim_y,json=dimY,proto3" json:"dim_y,omitempty"`
	Color              string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	ObjectLayerItemIds []string               `protobuf:"bytes,7,rep,name=object_layer_item_ids,json=objectLayerItemIds,proto3" json:"object_layer_item_ids,omitempty"`
	// Bot-specific fields
	SpawnRadius float64 `protobuf:"fixed64,8,opt,name=spawn_radius,json=spawnRadius,proto3" json:"spawn_radius,omitempty"` // wandering radius (0 = use server default)
	AggroRange  float64 `protobuf:"fixed64,9,opt,name=aggro_range,json=aggroRange,proto3" json:"aggro_range,omitempty"`    // aggro detection range (0 = use server default)
	MaxLife     float64 `protobuf:"fixed64,10,opt,name=max_life,json=maxLife,proto3" json:"max_life,omitempty"`            // base max life (0 = use server default)
	LifeRegen   float64 `protobuf:"fixed64,11,opt,name=life_regen,json=lifeRegen,proto3" json:"life_regen,omitempty"`      // life regen rate (0 = use server default)
	// Portal-specific field
	PortalSubtype string `protobuf:"bytes,12,opt,name=portal_subtype,json=portalSubtype,proto3" json:"portal_subtype,omitempty"` // inter-portal | inter-random | intra-random | intra-portal
	// Parsed RGBA colour from the DB entity document.
	// When color_a > 0, the Go server uses these values as the entity's fallback
	// colour (when it has no ObjectLayer items) instead of the palette default.
	ColorR        int32 `protobuf:"varint,13,opt,name=color_r,json=colorR,proto3" json:"color_r,omitempty"`
	ColorG        int32 `protobuf:"varint,14,opt,name=color_g,json=colorG,proto3" json:"color_g,omitempty"`
	ColorB        int32 `protobuf:"varint,15,opt,name=color_b,json=colorB,proto3" json:"color_b,omitempty"`
	ColorA        int32 `protobuf:"varint,16,opt,name=color_a,json=colorA,proto3" json:"color_a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMessage) Reset() {
	*x = EntityMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMessage) ProtoMessage() {}

func (x *EntityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMessage.ProtoReflect.Descriptor instead.
func (*EntityMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{23}
}

func (x *EntityMessage) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityMessage) GetInitCellX() int32 {
	if x != nil {
		return x.InitCellX
	}
	return 0
}

func (x *EntityMessage) GetInitCellY() int32 {
	if x != nil {
		return x.InitCellY
	}
	return 0
}

func (x *EntityMessage) GetDimX() int32 {
	if x != nil {
		return x.DimX
	}
	return 0
}

func (x *EntityMessage) GetDimY() int32 {
	if x != nil {
		return x.DimY
	}
	return 0
}

func (x *EntityMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EntityMessage) GetObjectLayerItemIds() []string {
	if x != nil {
		return x.ObjectLayerItemIds
	}
	return nil
}

func (x *EntityMessage) GetSpawnRadius() float64 {
	if x != nil {
		return x.SpawnRadius
	}
	return 0
}

func (x *EntityMessage) GetAggroRange() float64 {
	if x != nil {
		return x.AggroRange
	}
	return 0
}

func (x *EntityMessage) GetMaxLife() float64 {
	if x != nil {
		return x.MaxLife
	}
	return 0
}

func (x *EntityMessage) GetLifeRegen() float64 {
	if x != nil {
		return x.LifeRegen
	}
	return 0
}

func (x *EntityMessage) GetPortalSubtype() string {
	if x != nil {
		return x.PortalSubtype
	}
	return ""
}

func (x *EntityMessage) GetColorR() int32 {
	if x != nil {
		return x.ColorR
	}
	return 0
}

func (x *EntityMessage) GetColorG() int32 {
	if x != nil {
		return x.ColorG
	}
	return 0
}

func (x *EntityMessage) GetColorB() int32 {
	if x != nil {
		return x.ColorB
	}
	return 0
}

func (x *EntityMessage) GetColorA() int32 {
	if x != nil {
		return x.ColorA
	}
	return 0
}

type MapDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MongoId       string                 `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongo_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GridX         int32                  `protobuf:"varint,4,opt,name=grid_x,json=gridX,proto3" json:"grid_x,omitempty"`
	GridY         int32                  `protobuf:"varint,5,opt,name=grid_y,json=gridY,proto3" json:"grid_y,omitempty"`
	CellWidth     int32                  `protobuf:"varint,6,opt,name=cell_width,json=cellWidth,proto3" json:"cell_width,omitempty"`
	CellHeight    int32                  `protobuf:"varint,7,opt,name=cell_height,json=cellHeight,proto3" json:"cell_height,omitempty"`
	Entities      []*EntityMessage       `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDataMessage) Reset() {
	*x = MapDataMessage{}
	mi := &file_proto_cyberia_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDataMessage) ProtoMessage() {}

func (x *MapDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDataMessage.ProtoReflect.Descriptor instead.
func (*MapDataMessage) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{24}
}

func (x *MapDataMessage) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *MapDataMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MapDataMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapDataMessage) GetGridX() int32 {
	if x != nil {
		return x.GridX
	}
	return 0
}

func (x *MapDataMessage) GetGridY() int32 {
	if x != nil {
		return x.GridY
	}
	return 0
}

func (x *MapDataMessage) GetCellWidth() int32 {
	if x != nil {
		return x.CellWidth
	}
	return 0
}

func (x *MapDataMessage) GetCellHeight() int32 {
	if x != nil {
		return x.CellHeight
	}
	return 0
}

func (x *MapDataMessage) GetEntities() []*EntityMessage {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetMapDataRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MapCode string                 `protobuf:"bytes,1,opt,name=map_code,json=mapCode,proto3" json:"map_code,omitempty"`
	// Code of the Go instance making the request — used by the Engine
	// to update the cyberia-global-map-code-registry live tracking table.
	InstanceCode  string `protobuf:"bytes,2,opt,name=instance_code,json=instanceCode,proto3" json:"instance_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataRequest) Reset() {
	*x = GetMapDataRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataRequest) ProtoMessage() {}

func (x *GetMapDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataRequest.ProtoReflect.Descriptor instead.
func (*GetMapDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{25}
}

func (x *GetMapDataRequest) GetMapCode() string {
	if x != nil {
		return x.MapCode
	}
	return ""
}

func (x *GetMapDataRequest) GetInstanceCode() string {
	if x != nil {
		return x.InstanceCode
	}
	return ""
}

type GetMapDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapDataMessage        `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapDataResponse) Reset() {
	*x = GetMapDataResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapDataResponse) ProtoMessage() {}

func (x *GetMapDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapDataResponse.ProtoReflect.Descriptor instead.
func (*GetMapDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{26}
}

func (x *GetMapDataResponse) GetMap() *MapDataMessage {
	if x != nil {
		return x.Map
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{27}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeMs  int64                  `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{28}
}

func (x *PingResponse) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type ObjectLayerManifestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectLayerManifestEntry) Reset() {
	*x = ObjectLayerManifestEntry{}
	mi := &file_proto_cyberia_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectLayerManifestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectLayerManifestEntry) ProtoMessage() {}

func (x *ObjectLayerManifestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectLayerManifestEntry.ProtoReflect.Descriptor instead.
func (*ObjectLayerManifestEntry) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{29}
}

func (x *ObjectLayerManifestEntry) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ObjectLayerManifestEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type GetObjectLayerManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestRequest) Reset() {
	*x = GetObjectLayerManifestRequest{}
	mi := &file_proto_cyberia_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestRequest) ProtoMessage() {}

func (x *GetObjectLayerManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{30}
}

type GetObjectLayerManifestResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*ObjectLayerManifestEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLayerManifestResponse) Reset() {
	*x = GetObjectLayerManifestResponse{}
	mi := &file_proto_cyberia_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLayerManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLayerManifestResponse) ProtoMessage() {}

func (x *GetObjectLayerManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberia_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLayerManifestResponse.ProtoReflect.Descriptor instead.
func (*GetObjectLayerManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberia_proto_rawDescGZIP(), []int{31}
}

func (x *GetObjectLayerManifestResponse) GetEntries() []*ObjectLayerManifestEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_cyberia_proto protoreflect.FileDescriptor

const file_proto_cyberia_proto_rawDesc = "" +
	"\n" +
	"\x13proto/cyberia.proto\x12\acyberia\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"#\n" +
	"\x05Vec2I\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xad\x01\n" +
	"\x05Stats\x12\x16\n" +
	"\x06effect\x18\x01 \x01(\x05R\x06effect\x12\x1e\n" +
	"\n" +
	"resistance\x18\x02 \x01(\x05R\n" +
	"resistance\x12\x18\n" +
	"\aagility\x18\x03 \x01(\x05R\aagility\x12\x14\n" +
	"\x05range\x18\x04 \x01(\x05R\x05range\x12\"\n" +
	"\fintelligence\x18\x05 \x01(\x05R\fintelligence\x12\x18\n" +
	"\autility\x18\x06 \x01(\x05R\autility\"n\n" +
	"\bItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tactivable\x18\x04 \x01(\bR\tactivable\"Q\n" +
	"\x06Ledger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"=\n" +
	"\x06Render\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12!\n" +
	"\fmetadata_cid\x18\x02 \x01(\tR\vmetadataCid\"\xc2\x02\n" +
	"\x12ObjectLayerMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12$\n" +
	"\x05stats\x18\x02 \x01(\v2\x0e.cyberia.StatsR\x05stats\x12%\n" +
	"\x04item\x18\x03 \x01(\v2\x11.cyberia.ItemInfoR\x04item\x12'\n" +
	"\x06ledger\x18\x04 \x01(\v2\x0f.cyberia.LedgerR\x06ledger\x12'\n" +
	"\x06render\x18\x05 \x01(\v2\x0f.cyberia.RenderR\x06render\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03cid\x18\a \x01(\tR\x03cid\x12%\n" +
	"\x0eframe_duration\x18\b \x01(\x05R\rframeDuration\x12!\n" +
	"\fis_stateless\x18\t \x01(\bR\visStateless\"F\n" +
	"\x1aGetObjectLayerBatchRequest\x12(\n" +
	"\x10item_type_filter\x18\x01 \x01(\tR\x0eitemTypeFilter\"0\n" +
	"\x15GetObjectLayerRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\x8d\x02\n" +
	"\n" +
	"PortalEdge\x12&\n" +
	"\x0fsource_map_code\x18\x01 \x01(\tR\rsourceMapCode\x12\"\n" +
	"\rsource_cell_x\x18\x02 \x01(\x05R\vsourceCellX\x12\"\n" +
	"\rsource_cell_y\x18\x03 \x01(\x05R\vsourceCellY\x12&\n" +
	"\x0ftarget_map_code\x18\x04 \x01(\tR\rtargetMapCode\x12\"\n" +
	"\rtarget_cell_x\x18\x05 \x01(\x05R\vtargetCellX\x12\"\n" +
	"\rtarget_cell_y\x18\x06 \x01(\x05R\vtargetCellY\x12\x1f\n" +
	"\vportal_mode\x18\a \x01(\tR\n" +
	"portalMode\"\x8f\x02\n" +
	"\x0fInstanceMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tmap_codes\x18\x06 \x03(\tR\bmapCodes\x12-\n" +
	"\aportals\x18\a \x03(\v2\x13.cyberia.PortalEdgeR\aportals\x12#\n" +
	"\rtopology_mode\x18\b \x01(\tR\ftopologyMode\x12\x12\n" +
	"\x04seed\x18\t \x01(\tR\x04seed\"=\n" +
	"\x16GetFullInstanceRequest\x12#\n" +
	"\rinstance_code\x18\x01 \x01(\tR\finstanceCode\"\x89\x02\n" +
	"\x17GetFullInstanceResponse\x124\n" +
	"\binstance\x18\x01 \x01(\v2\x18.cyberia.InstanceMessageR\binstance\x12+\n" +
	"\x04maps\x18\x02 \x03(\v2\x17.cyberia.MapDataMessageR\x04maps\x12@\n" +
	"\robject_layers\x18\x03 \x03(\v2\x1b.cyberia.ObjectLayerMessageR\fobjectLayers\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.cyberia.InstanceConfigR\x06config\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"V\n" +
	"\n" +
	"ColorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\f\n" +
	"\x01r\x18\x02 \x01(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x03 \x01(\x05R\x01g\x12\f\n" +
	"\x01b\x18\x04 \x01(\x05R\x01b\x12\f\n" +
	"\x01a\x18\x05 \x01(\x05R\x01a\"f\n" +
	"\x17DefaultObjectLayerState\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xa0\x01\n" +
	"\vSkillDetail\x12$\n" +
	"\x0elogic_event_id\x18\x01 \x01(\tR\flogicEventId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\x17summoned_entity_item_id\x18\x03 \x01(\tR\x14summonedEntityItemId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xdf\x01\n" +
	"\x10SkillConfigEntry\x12&\n" +
	"\x0ftrigger_item_id\x18\x01 \x01(\tR\rtriggerItemId\x12,\n" +
	"\x06skills\x18\a \x03(\v2\x14.cyberia.SkillDetailR\x06skillsJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aR\x10spawned_item_idsR\x0elogic_event_idR\x0flogic_event_idsR\vdescriptionR\x17summoned_entity_item_id\"\x8e\x03\n" +
	"\fEconomyRules\x12&\n" +
	"\x0fbot_spawn_coins\x18\x01 \x01(\x05R\rbotSpawnCoins\x12,\n" +
	"\x12player_spawn_coins\x18\x02 \x01(\x05R\x10playerSpawnCoins\x126\n" +
	"\x18coin_kill_percent_vs_bot\x18\x03 \x01(\x01R\x14coinKillPercentVsBot\x12<\n" +
	"\x1bcoin_kill_percent_vs_player\x18\x04 \x01(\x01R\x17coinKillPercentVsPlayer\x12/\n" +
	"\x14coin_kill_min_amount\x18\x05 \x01(\x05R\x11coinKillMinAmount\x120\n" +
	"\x14respawn_cost_percent\x18\x06 \x01(\x01R\x12respawnCostPercent\x12\x1d\n" +
	"\n" +
	"portal_fee\x18\a \x01(\x05R\tportalFee\x120\n" +
	"\x14crafting_fee_percent\x18\b \x01(\x01R\x12craftingFeePercent\"\x91\x04\n" +
	"\n" +
	"SkillRules\x126\n" +
	"\x17projectile_spawn_chance\x18\x01 \x01(\x01R\x15projectileSpawnChance\x124\n" +
	"\x16projectile_lifetime_ms\x18\x02 \x01(\x05R\x14projectileLifetimeMs\x12)\n" +
	"\x10projectile_width\x18\x03 \x01(\x01R\x0fprojectileWidth\x12+\n" +
	"\x11projectile_height\x18\x04 \x01(\x01R\x10projectileHeight\x12>\n" +
	"\x1bprojectile_speed_multiplier\x18\x05 \x01(\x01R\x19projectileSpeedMultiplier\x12:\n" +
	"\x19doppelganger_spawn_chance\x18\x06 \x01(\x01R\x17doppelgangerSpawnChance\x128\n" +
	"\x18doppelganger_lifetime_ms\x18\a \x01(\x05R\x16doppelgangerLifetimeMs\x12:\n" +
	"\x19doppelganger_spawn_radius\x18\b \x01(\x01R\x17doppelgangerSpawnRadius\x12K\n" +
	"\"doppelganger_initial_life_fraction\x18\t \x01(\x01R\x1fdoppelgangerInitialLifeFraction\"\x81\x01\n" +
	"\x0eEquipmentRules\x12*\n" +
	"\x11active_item_types\x18\x01 \x03(\tR\x0factiveItemTypes\x12 \n" +
	"\fone_per_type\x18\x02 \x01(\bR\n" +
	"onePerType\x12!\n" +
	"\frequire_skin\x18\x03 \x01(\bR\vrequireSkin\"\xa9\x12\n" +
	"\x0eInstanceConfig\x12\x1b\n" +
	"\tcell_size\x18\x01 \x01(\x01R\bcellSize\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x05R\x03fps\x12)\n" +
	"\x10interpolation_ms\x18\x03 \x01(\x05R\x0finterpolationMs\x12*\n" +
	"\x11default_obj_width\x18\x04 \x01(\x01R\x0fdefaultObjWidth\x12,\n" +
	"\x12default_obj_height\x18\x05 \x01(\x01R\x10defaultObjHeight\x12)\n" +
	"\x10camera_smoothing\x18\x06 \x01(\x01R\x0fcameraSmoothing\x12\x1f\n" +
	"\vcamera_zoom\x18\a \x01(\x01R\n" +
	"cameraZoom\x12=\n" +
	"\x1bdefault_width_screen_factor\x18\b \x01(\x01R\x18defaultWidthScreenFactor\x12?\n" +
	"\x1cdefault_height_screen_factor\x18\t \x01(\x01R\x19defaultHeightScreenFactor\x12\x15\n" +
	"\x06dev_ui\x18\n" +
	" \x01(\bR\x05devUi\x12+\n" +
	"\x06colors\x18\v \x03(\v2\x13.cyberia.ColorEntryR\x06colors\x12\x1d\n" +
	"\n" +
	"aoi_radius\x18\f \x01(\x01R\taoiRadius\x12-\n" +
	"\x13portal_hold_time_ms\x18\r \x01(\x05R\x10portalHoldTimeMs\x12.\n" +
	"\x13portal_spawn_radius\x18\x0e \x01(\x01R\x11portalSpawnRadius\x12*\n" +
	"\x11entity_base_speed\x18\x0f \x01(\x01R\x0fentityBaseSpeed\x12/\n" +
	"\x14entity_base_max_life\x18\x10 \x01(\x01R\x11entityBaseMaxLife\x12B\n" +
	"\x1eentity_base_action_cooldown_ms\x18\x11 \x01(\x05R\x1aentityBaseActionCooldownMs\x12I\n" +
	"\"entity_base_min_action_cooldown_ms\x18\x12 \x01(\x05R\x1dentityBaseMinActionCooldownMs\x12&\n" +
	"\x0fbot_aggro_range\x18\x13 \x01(\x01R\rbotAggroRange\x120\n" +
	"\x14default_player_width\x18\x14 \x01(\x01R\x12defaultPlayerWidth\x122\n" +
	"\x15default_player_height\x18\x15 \x01(\x01R\x13defaultPlayerHeight\x12:\n" +
	"\x1aplayer_base_life_regen_min\x18\x16 \x01(\x01R\x16playerBaseLifeRegenMin\x12:\n" +
	"\x1aplayer_base_life_regen_max\x18\x17 \x01(\x01R\x16playerBaseLifeRegenMax\x12&\n" +
	"\x0fsum_stats_limit\x18\x18 \x01(\x05R\rsumStatsLimit\x12*\n" +
	"\x11max_active_layers\x18\x19 \x01(\x05R\x0fmaxActiveLayers\x122\n" +
	"\x15initial_life_fraction\x18\x1a \x01(\x01R\x13initialLifeFraction\x12.\n" +
	"\x13respawn_duration_ms\x18\x1c \x01(\x05R\x11respawnDurationMs\x12.\n" +
	"\x13collision_life_loss\x18\x1e \x01(\x01R\x11collisionLifeLoss\x12*\n" +
	"\x11life_regen_chance\x18! \x01(\x01R\x0flifeRegenChance\x12\x1d\n" +
	"\n" +
	"max_chance\x18\" \x01(\x01R\tmaxChance\x12<\n" +
	"\fskill_config\x18- \x03(\v2\x19.cyberia.SkillConfigEntryR\vskillConfig\x124\n" +
	"\vskill_rules\x18/ \x01(\v2\x13.cyberia.SkillRulesR\n" +
	"skillRules\x12:\n" +
	"\reconomy_rules\x18> \x01(\v2\x15.cyberia.EconomyRulesR\feconomyRules\x12@\n" +
	"\x0fequipment_rules\x18? \x01(\v2\x17.cyberia.EquipmentRulesR\x0eequipmentRules\x12C\n" +
	"\x0fentity_defaults\x184 \x03(\v2\x1a.cyberia.EntityTypeDefaultR\x0eentityDefaults\x12;\n" +
	"\fstatus_icons\x18@ \x03(\v2\x18.cyberia.StatusIconEntryR\vstatusIconsJ\x04\b\x1b\x10\x1cJ\x04\b \x10!J\x04\b5\x106J\x04\b6\x107J\x04\b7\x108J\x04\b8\x109J\x04\b9\x10:J\x04\b:\x10;J\x04\b;\x10<J\x04\b<\x10=J\x04\b=\x10>J\x04\b#\x10$J\x04\b$\x10%J\x04\b%\x10&J\x04\b&\x10'J\x04\b'\x10(J\x04\b(\x10)J\x04\b)\x10*J\x04\b*\x10+J\x04\b+\x10,J\x04\b.\x10/J\x04\b\x1d\x10\x1eJ\x04\b\x1f\x10 J\x04\b,\x10-J\x04\b0\x101J\x04\b1\x102J\x04\b2\x103J\x04\b3\x104R\x1cdefault_player_object_layersR\x13bullet_spawn_chanceR\x12bullet_lifetime_msR\fbullet_widthR\rbullet_heightR\x17bullet_speed_multiplierR\x19doppelganger_spawn_chanceR\x18doppelganger_lifetime_msR\x19doppelganger_spawn_radiusR\"doppelganger_initial_life_fractionR\x14default_player_colorR\rghost_item_idR\fcoin_item_idR\x15default_floor_item_idR\x13bot_default_item_idR\x14user_default_item_idR\x16weapon_default_item_idR\x16bullet_default_item_id\"\xef\x01\n" +
	"\x11EntityTypeDefault\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\"\n" +
	"\rlive_item_ids\x18\x02 \x03(\tR\vliveItemIds\x12\"\n" +
	"\rdead_item_ids\x18\x03 \x03(\tR\vdeadItemIds\x12\x1b\n" +
	"\tcolor_key\x18\x04 \x01(\tR\bcolorKey\x12T\n" +
	"\x15default_object_layers\x18\x05 \x03(\v2 .cyberia.DefaultObjectLayerStateR\x13defaultObjectLayers\"\xd2\x01\n" +
	"\x0fStatusIconEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\aicon_id\x18\x02 \x01(\tR\x06iconId\x12$\n" +
	"\x0eborder_color_r\x18\x03 \x01(\x05R\fborderColorR\x12$\n" +
	"\x0eborder_color_g\x18\x04 \x01(\x05R\fborderColorG\x12$\n" +
	"\x0eborder_color_b\x18\x05 \x01(\x05R\fborderColorB\x12$\n" +
	"\x0eborder_color_a\x18\x06 \x01(\x05R\fborderColorA\"\xec\x03\n" +
	"\rEntityMessage\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1e\n" +
	"\vinit_cell_x\x18\x02 \x01(\x05R\tinitCellX\x12\x1e\n" +
	"\vinit_cell_y\x18\x03 \x01(\x05R\tinitCellY\x12\x13\n" +
	"\x05dim_x\x18\x04 \x01(\x05R\x04dimX\x12\x13\n" +
	"\x05dim_y\x18\x05 \x01(\x05R\x04dimY\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x121\n" +
	"\x15object_layer_item_ids\x18\a \x03(\tR\x12objectLayerItemIds\x12!\n" +
	"\fspawn_radius\x18\b \x01(\x01R\vspawnRadius\x12\x1f\n" +
	"\vaggro_range\x18\t \x01(\x01R\n" +
	"aggroRange\x12\x19\n" +
	"\bmax_life\x18\n" +
	" \x01(\x01R\amaxLife\x12\x1d\n" +
	"\n" +
	"life_regen\x18\v \x01(\x01R\tlifeRegen\x12%\n" +
	"\x0eportal_subtype\x18\f \x01(\tR\rportalSubtype\x12\x17\n" +
	"\acolor_r\x18\r \x01(\x05R\x06colorR\x12\x17\n" +
	"\acolor_g\x18\x0e \x01(\x05R\x06colorG\x12\x17\n" +
	"\acolor_b\x18\x0f \x01(\x05R\x06colorB\x12\x17\n" +
	"\acolor_a\x18\x10 \x01(\x05R\x06colorA\"\xf5\x01\n" +
	"\x0eMapDataMessage\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06grid_x\x18\x04 \x01(\x05R\x05gridX\x12\x15\n" +
	"\x06grid_y\x18\x05 \x01(\x05R\x05gridY\x12\x1d\n" +
	"\n" +
	"cell_width\x18\x06 \x01(\x05R\tcellWidth\x12\x1f\n" +
	"\vcell_height\x18\a \x01(\x05R\n" +
	"cellHeight\x122\n" +
	"\bentities\x18\b \x03(\v2\x16.cyberia.EntityMessageR\bentities\"S\n" +
	"\x11GetMapDataRequest\x12\x19\n" +
	"\bmap_code\x18\x01 \x01(\tR\amapCode\x12#\n" +
	"\rinstance_code\x18\x02 \x01(\tR\finstanceCode\"?\n" +
	"\x12GetMapDataResponse\x12)\n" +
	"\x03map\x18\x01 \x01(\v2\x17.cyberia.MapDataMessageR\x03map\"\r\n" +
	"\vPingRequest\"4\n" +
	"\fPingResponse\x12$\n" +
	"\x0eserver_time_ms\x18\x01 \x01(\x03R\fserverTimeMs\"K\n" +
	"\x18ObjectLayerManifestEntry\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\x1f\n" +
	"\x1dGetObjectLayerManifestRequest\"]\n" +
	"\x1eGetObjectLayerManifestResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.cyberia.ObjectLayerManifestEntryR\aentries2\xfb\x03\n" +
	"\x12CyberiaDataService\x12T\n" +
	"\x0fGetFullInstance\x12\x1f.cyberia.GetFullInstanceRequest\x1a .cyberia.GetFullInstanceResponse\x12E\n" +
	"\n" +
	"GetMapData\x12\x1a.cyberia.GetMapDataRequest\x1a\x1b.cyberia.GetMapDataResponse\x12Y\n" +
	"\x13GetObjectLayerBatch\x12#.cyberia.GetObjectLayerBatchRequest\x1a\x1b.cyberia.ObjectLayerMessage0\x01\x12M\n" +
	"\x0eGetObjectLayer\x12\x1e.cyberia.GetObjectLayerRequest\x1a\x1b.cyberia.ObjectLayerMessage\x123\n" +
	"\x04Ping\x12\x14.cyberia.PingRequest\x1a\x15.cyberia.PingResponse\x12i\n" +
	"\x16GetObjectLayerManifest\x12&.cyberia.GetObjectLayerManifestRequest\x1a'.cyberia.GetObjectLayerManifestResponseB\x16Z\x14cyberia-server/protob\x06proto3"

var (
	file_proto_cyberia_proto_rawDescOnce sync.Once
	file_proto_cyberia_proto_rawDescData []byte
)

func file_proto_cyberia_proto_rawDescGZIP() []byte {
	file_proto_cyberia_proto_rawDescOnce.Do(func() {
		file_proto_cyberia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)))
	})
	return file_proto_cyberia_proto_rawDescData
}

var file_proto_cyberia_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_cyberia_proto_goTypes = []any{
	(*Vec2)(nil),                           // 0: cyberia.Vec2
	(*Vec2I)(nil),                          // 1: cyberia.Vec2I
	(*Stats)(nil),                          // 2: cyberia.Stats
	(*ItemInfo)(nil),                       // 3: cyberia.ItemInfo
	(*Ledger)(nil),                         // 4: cyberia.Ledger
	(*Render)(nil),                         // 5: cyberia.Render
	(*ObjectLayerMessage)(nil),             // 6: cyberia.ObjectLayerMessage
	(*GetObjectLayerBatchRequest)(nil),     // 7: cyberia.GetObjectLayerBatchRequest
	(*GetObjectLayerRequest)(nil),          // 8: cyberia.GetObjectLayerRequest
	(*PortalEdge)(nil),                     // 9: cyberia.PortalEdge
	(*InstanceMessage)(nil),                // 10: cyberia.InstanceMessage
	(*GetFullInstanceRequest)(nil),         // 11: cyberia.GetFullInstanceRequest
	(*GetFullInstanceResponse)(nil),        // 12: cyberia.GetFullInstanceResponse
	(*ColorEntry)(nil),                     // 13: cyberia.ColorEntry
	(*DefaultObjectLayerState)(nil),        // 14: cyberia.DefaultObjectLayerState
	(*SkillDetail)(nil),                    // 15: cyberia.SkillDetail
	(*SkillConfigEntry)(nil),               // 16: cyberia.SkillConfigEntry
	(*EconomyRules)(nil),                   // 17: cyberia.EconomyRules
	(*SkillRules)(nil),                     // 18: cyberia.SkillRules
	(*EquipmentRules)(nil),                 // 19: cyberia.EquipmentRules
	(*InstanceConfig)(nil),                 // 20: cyberia.InstanceConfig
	(*EntityTypeDefault)(nil),              // 21: cyberia.EntityTypeDefault
	(*StatusIconEntry)(nil),                // 22: cyberia.StatusIconEntry
	(*EntityMessage)(nil),                  // 23: cyberia.EntityMessage
	(*MapDataMessage)(nil),                 // 24: cyberia.MapDataMessage
	(*GetMapDataRequest)(nil),              // 25: cyberia.GetMapDataRequest
	(*GetMapDataResponse)(nil),             // 26: cyberia.GetMapDataResponse
	(*PingRequest)(nil),                    // 27: cyberia.PingRequest
	(*PingResponse)(nil),                   // 28: cyberia.PingResponse
	(*ObjectLayerManifestEntry)(nil),       // 29: cyberia.ObjectLayerManifestEntry
	(*GetObjectLayerManifestRequest)(nil),  // 30: cyberia.GetObjectLayerManifestRequest
	(*GetObjectLayerManifestResponse)(nil), // 31: cyberia.GetObjectLayerManifestResponse
}
var file_proto_cyberia_proto_depIdxs = []int32{
	2,  // 0: cyberia.ObjectLayerMessage.stats:type_name -> cyberia.Stats
	3,  // 1: cyberia.ObjectLayerMessage.item:type_name -> cyberia.ItemInfo
	4,  // 2: cyberia.ObjectLayerMessage.ledger:type_name -> cyberia.Ledger
	5,  // 3: cyberia.ObjectLayerMessage.render:type_name -> cyberia.Render
	9,  // 4: cyberia.InstanceMessage.portals:type_name -> cyberia.PortalEdge
	10, // 5: cyberia.GetFullInstanceResponse.instance:type_name -> cyberia.InstanceMessage
	24, // 6: cyberia.GetFullInstanceResponse.maps:type_name -> cyberia.MapDataMessage
	6,  // 7: cyberia.GetFullInstanceResponse.object_layers:type_name -> cyberia.ObjectLayerMessage
	20, // 8: cyberia.GetFullInstanceResponse.config:type_name -> cyberia.InstanceConfig
	15, // 9: cyberia.SkillConfigEntry.skills:type_name -> cyberia.SkillDetail
	13, // 10: cyberia.InstanceConfig.colors:type_name -> cyberia.ColorEntry
	16, // 11: cyberia.InstanceConfig.skill_config:type_name -> cyberia.SkillConfigEntry
	18, // 12: cyberia.InstanceConfig.skill_rules:type_name -> cyberia.SkillRules
	17, // 13: cyberia.InstanceConfig.economy_rules:type_name -> cyberia.EconomyRules
	19, // 14: cyberia.InstanceConfig.equipment_rules:type_name -> cyberia.EquipmentRules
	21, // 15: cyberia.InstanceConfig.entity_defaults:type_name -> cyberia.EntityTypeDefault
	22, // 16: cyberia.InstanceConfig.status_icons:type_name -> cyberia.StatusIconEntry
	14, // 17: cyberia.EntityTypeDefault.default_object_layers:type_name -> cyberia.DefaultObjectLayerState
	23, // 18: cyberia.MapDataMessage.entities:type_name -> cyberia.EntityMessage
	24, // 19: cyberia.GetMapDataResponse.map:type_name -> cyberia.MapDataMessage
	29, // 20: cyberia.GetObjectLayerManifestResponse.entries:type_name -> cyberia.ObjectLayerManifestEntry
	11, // 21: cyberia.CyberiaDataService.GetFullInstance:input_type -> cyberia.GetFullInstanceRequest
	25, // 22: cyberia.CyberiaDataService.GetMapData:input_type -> cyberia.GetMapDataRequest
	7,  // 23: cyberia.CyberiaDataService.GetObjectLayerBatch:input_type -> cyberia.GetObjectLayerBatchRequest
	8,  // 24: cyberia.CyberiaDataService.GetObjectLayer:input_type -> cyberia.GetObjectLayerRequest
	27, // 25: cyberia.CyberiaDataService.Ping:input_type -> cyberia.PingRequest
	30, // 26: cyberia.CyberiaDataService.GetObjectLayerManifest:input_type -> cyberia.GetObjectLayerManifestRequest
	12, // 27: cyberia.CyberiaDataService.GetFullInstance:output_type -> cyberia.GetFullInstanceResponse
	26, // 28: cyberia.CyberiaDataService.GetMapData:output_type -> cyberia.GetMapDataResponse
	6,  // 29: cyberia.CyberiaDataService.GetObjectLayerBatch:output_type -> cyberia.ObjectLayerMessage
	6,  // 30: cyberia.CyberiaDataService.GetObjectLayer:output_type -> cyberia.ObjectLayerMessage
	28, // 31: cyberia.CyberiaDataService.Ping:output_type -> cyberia.PingResponse
	31, // 32: cyberia.CyberiaDataService.GetObjectLayerManifest:output_type -> cyberia.GetObjectLayerManifestResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_cyberia_proto_init() }
func file_proto_cyberia_proto_init() {
	if File_proto_cyberia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberia_proto_rawDesc), len(file_proto_cyberia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cyberia_proto_goTypes,
		DependencyIndexes: file_proto_cyberia_proto_depIdxs,
		MessageInfos:      file_proto_cyberia_proto_msgTypes,
	}.Build()
	File_proto_cyberia_proto = out.File
	file_proto_cyberia_proto_goTypes = nil
	file_proto_cyberia_proto_depIdxs = nil
}
